--- <auto-generated>
---     Generated by the moonfly tool.  DO NOT EDIT!
--- </auto-generated>


---@class PBActivityData
---@field public activity_id integer
---@field public beg_ts integer
---@field public end_ts integer


---@class PBGetActivityInfoReqCmd
---@field public uid integer


---@class PBGetActivityInfoRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public activity_datas PBActivityData[]


---@class PBUserLoginData
---@field public uid integer
---@field public steam_id integer
---@field public authkey string
---@field public auth_ticket string
---@field public macid integer
---@field public version string @客户端版本号
---@field public pb_version string @协议版本号


---@class PBClientLoginReqCmd
---@field public login_data PBUserLoginData
---@field public is_register boolean
---@field public password string


---@class PBClientLoginRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer @用户ID
---@field public net_id integer @用户网络id
---@field public reconn_key string @用户重连key


---@class PBDSLoginData
---@field public authkey string
---@field public auth_ticket string
---@field public version string @客户端版本号
---@field public pb_version string @协议版本号
---@field public ds_type integer @ds类型 1-主城 2-副本
---@field public ds_id integer


---@class PBDSLoginReqCmd
---@field public login_data PBDSLoginData


---@class PBDSLoginRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public dsid integer @服务器ID
---@field public net_id integer @DS网络id


---@class PBBag
---@field public bag_item_type integer
---@field public capacity integer
---@field public items table<integer, PBItemData>


---@class PBBags
---@field public bags table<string, PBBag>


---@class PBBagGetDataReqCmd
---@field public uid integer
---@field public bags_name string[]


---@class PBBagGetDataRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public bag_datas table<string, PBBag>


---@class PBBagGetCoinsReqCmd
---@field public uid integer


---@class PBBagGetCoinsRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public coin_datas PBUserCoins


---@class PBBagUpdateSyncCmd
---@field public update_items table<string, PBBag>
---@field public update_coins table<integer, PBCoin>


---@class PBBagOperateItemReqCmd
---@field public uid integer
---@field public operate_type integer @1--堆叠,2--拆分,3--移动
---@field public src_bag string
---@field public src_pos integer
---@field public dest_bag string
---@field public dest_pos integer
---@field public splitCount integer


---@class PBBagOperateItemRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer


---@class PBChatMsgInfo
---@field public channel_type integer @频道类型
---@field public uid integer @发送者uid
---@field public name string @发送者昵称
---@field public msg_content string @消息内容
---@field public send_time integer @发送时间
---@field public to_uid integer @接收者uid


---@class PBChatReqCmd
---@field public channel_type integer @频道类型
---@field public msg_content string @消息内容
---@field public to_uid integer @接收者uid


---@class PBChatRspCmd
---@field public code integer @错误码


---@class PBChatSynCmd
---@field public infos PBChatMsgInfo[]


---@class PBSyncWorldChatCmd
---@field public world_index integer[] @世界索引


---@class PBChooseWorldChatReqCmd
---@field public world_index integer @世界索引


---@class PBChooseWorldChatRespCmd
---@field public code integer @错误码
---@field public world_index integer @世界索引


---@class PBNotifyWorldChatCmd
---@field public world_index integer @世界索引


---@class PBApplyLoginCityReqCmd
---@field public uid integer


---@class PBApplyLoginCityRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public cityid integer
---@field public region string
---@field public ds_address string
---@field public ds_ip string


---@class PBMessagePack
---@field public net_id integer
---@field public broadcast integer
---@field public stub_id integer
---@field public msg_type integer
---@field public msg_body string


---@class PBDsCreateData
---@field public ds_id integer
---@field public chapter integer
---@field public difficulty integer
---@field public map_id integer
---@field public boss_id integer
---@field public server_ip string
---@field public server_port integer
---@field public uids integer[]


---@class PBPacketCmd
---@field public messages PBMessagePack[]


---@class PBPingCmd
---@field public time number @用户统计服务器之间延时


---@class PBPongCmd
---@field public time number @用户统计服务器之间延时


---@class PBEnterCityReqCmd
---@field public uid integer
---@field public cityid integer


---@class PBEnterCityRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息


---@class PBExitCityReqCmd
---@field public uid integer
---@field public cityid integer


---@class PBExitCityRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息


---@class PBUpdateCityReqCmd
---@field public cityid integer
---@field public player_num integer


---@class PBUpdateCityRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息


---@class PBAddItemsCityPlayerReqCmd
---@field public uid integer
---@field public cityid integer
---@field public simple_items PBItemSimple[]


---@class PBAddItemsCityPlayerRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息


---@class PBGetDsUserAttrReqCmd
---@field public dsid integer
---@field public quest_uid integer @请求的玩家uid


---@class PBGetDsUserAttrRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public dsid integer
---@field public quest_uid integer
---@field public info PBUserAttr


---@class PBGetDsUserBagsReqCmd
---@field public dsid integer
---@field public quest_uid integer @请求的玩家uid
---@field public bags_name string[] @背包类型


---@class PBGetDsUserBagsRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public dsid integer
---@field public quest_uid integer
---@field public bag_datas table<string, PBBag>


---@class PBGetDsUserRolesReqCmd
---@field public dsid integer
---@field public quest_uid integer @请求的玩家uid
---@field public roleids integer[] @角色id


---@class PBGetDsUserRolesRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public dsid integer
---@field public quest_uid integer
---@field public role_datas table<integer, PBRoleData>


---@class PBGetDsCreateDataReqCmd
---@field public roomid integer


---@class PBGetDsCreateDataRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public roomid integer
---@field public room_str string


---@class PBGetDsUserImageReqCmd
---@field public dsid integer
---@field public quest_uid integer @请求的玩家uid


---@class PBGetDsUserImageRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public dsid integer
---@field public quest_uid integer
---@field public image_data PBUserImage


---@class PBFriendData
---@field public uid integer
---@field public notes string @备注


---@class PBApplyFriendData
---@field public uid integer
---@field public head_id integer @头像id
---@field public nick_name string @昵称
---@field public account_level integer @账号等级
---@field public head_frame integer @头像框
---@field public title integer @称号
---@field public guild_id integer @公会id
---@field public guild_name string @公会名


---@class PBFriendGroupData
---@field public group_id integer @分组id
---@field public group_name string @分组名称
---@field public group_friends table<integer, PBFriendData> @分组内的好友


---@class PBUserFriendDatas
---@field public friend_groups table<integer, PBFriendGroupData> @好友分组
---@field public apply_friends table<integer, PBApplyFriendData> @申请好友


---@class PBGetFriendInfoReqCmd
---@field public uid integer


---@class PBGetFriendInfoRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public friend_datas PBUserFriendDatas
---@field public friends_simple_attr table<integer, PBUserAttr> @申请好友


---@class PBApplyFriendReqCmd
---@field public uid integer
---@field public apply_data PBApplyFriendData @申请数据
---@field public target_uid integer @目标uid


---@class PBApplyFriendRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public target_uid integer @目标uid


---@class PBSimpleGhostData
---@field public config_id integer @配置ID
---@field public skin_id integer @穿戴皮肤


---@class PBGhostData
---@field public config_id integer @配置ID
---@field public uniqid integer @唯一ID
---@field public star_level integer @星级
---@field public exp integer @经验值
---@field public digrams_cards table<integer, PBItemData> @八卦牌
---@field public passive_skills PBSkill[] @被动技能
---@field public active_skills PBSkill[] @主动技能
---@field public attrs PBAttribute[] @属性
---@field public nature integer @性格


---@class PBGhostImage
---@field public config_id integer @配置ID
---@field public star_level integer @星级
---@field public exp integer @经验值
---@field public cur_skin_id integer @当前装备皮肤
---@field public skin_id_list integer[] @拥有皮肤


---@class PBUserGhostDatas
---@field public battle_ghost_id integer @出战的鬼宠配置id
---@field public battle_ghost_uniqid integer @出战的鬼宠唯一id
---@field public ghost_list table<integer, PBGhostData>
---@field public ghost_image_list table<integer, PBGhostImage>


---@class PBGourd
---@field public gourd_id integer @葫芦id
---@field public nick_name string @葫芦昵称
---@field public up_level integer @葫芦等级
---@field public up_exp integer @葫芦经验
---@field public total_talent integer @总天赋点
---@field public cur_talent integer @当前天赋点
---@field public talent_attr PBAttribute[] @天赋属性
---@field public cd_end_ts integer @葫芦冷却时间


---@class PBGourdS
---@field public gourd_list PBGourd[]


---@class PBClientGetUsrGhostsInfoReqCmd
---@field public uid integer


---@class PBClientGetUsrGhostsInfoRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer @用户ID
---@field public ghosts_info PBUserGhostDatas @所有鬼宠数据


---@class PBGhostInfoSyncCmd
---@field public ghosts_info PBUserGhostDatas @变更的鬼宠数据


---@class PBGhostWearEquipReqCmd
---@field public uid integer
---@field public ghost_uniqid integer @鬼宠唯一id
---@field public bag_name string @背包名
---@field public pos integer @准备穿戴的装备在背包中的格子号
---@field public equip_config_id integer @准备穿戴的装备配置id
---@field public equip_uniqid integer @准备穿戴的装备唯一id
---@field public equip_idx integer @装备的位置


---@class PBGhostWearEquipRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public ghost_uniqid integer
---@field public bag_name string
---@field public pos integer
---@field public equip_config_id integer
---@field public equip_uniqid integer
---@field public equip_idx integer


---@class PBGhostTakeOffEquipReqCmd
---@field public uid integer
---@field public ghost_uniqid integer @宠唯一id
---@field public bag_name string @背包名
---@field public takeoff_config_id integer @准备卸下的装备配置id
---@field public takeoff_uniqid integer @准备卸下的装备唯一id
---@field public takeoff_idx integer @卸下的位置


---@class PBGhostTakeOffEquipRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public ghost_uniqid integer @角色id
---@field public bag_name string @背包名
---@field public takeoff_config_id integer @准备卸下的装备配置id
---@field public takeoff_uniqid integer @准备卸下的装备唯一id
---@field public takeoff_idx integer @卸下的位置


---@class PBGhostWearSkinReqCmd
---@field public uid integer
---@field public ghost_config_id integer @鬼宠id
---@field public skin integer @穿戴皮肤


---@class PBGhostWearSkinRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public ghost_config_id integer @鬼宠id
---@field public skin integer @穿戴皮肤


---@class Any
---@field public type_url string
---@field public value string


---@class PBGuildItemData
---@field public grid_id integer @背包格子ID
---@field public item_uid integer @物品实例ID
---@field public item_id integer @配置文件ID
---@field public item_num integer @数量


---@class PBGuildItemListData
---@field public item_list PBGuildItemData[]


---@class PBGuildApplyUserBaseInfo
---@field public playerSimpleInfo PBUserAttr
---@field public apply_time integer @申请时间


---@class PBGuildUserApplyList
---@field public apply_list PBGuildApplyUserBaseInfo[]


---@class PBGuildMemberData
---@field public uid integer @玩家uID
---@field public nickname string @玩家昵称
---@field public duty_id integer @玩家职务Id
---@field public contribute integer @玩家贡献
---@field public week_contribute integer @玩家本周贡献
---@field public online boolean @玩家在线状态 true 在线 false 不在线
---@field public last_get_salary_time integer @上一次获取工资的时间戳
---@field public join_time integer @加入公会时间
---@field public dkp integer @个人的DKP值
---@field public b_spoils_mgr boolean @是否战利品管理员
---@field public last_send_spoil integer @上次发放战利品的时间戳


---@class PBGuildUserData
---@field public uid integer @玩家uID
---@field public guild_data PBGuildMemberData @玩家公会的数据


---@class PBGuildRecordInfo
---@field public record_type integer
---@field public nickname string @目标玩家昵称
---@field public record_time integer
---@field public duty_name string @只在 eRT_DUTY_CHANGE 有用（表示职位名称)
---@field public guild_level integer @只在 eRT_GUILD_LV_UP 有用
---@field public guild_name string @只在 eRT_CHANGE_GUILD_NAME 有用
---@field public target_uid integer @目标玩家UID
---@field public duty_id integer @只在 eRT_DUTY_CHANGE 有用 （表示职位ID)
---@field public gkd_change_num integer @eRT_GuildGKD变化记录 ,
---@field public gkd_cur_num integer @eRT_GuildGKD GKD当前值
---@field public gkd_desc string @eRT_GuildGKD 备注
---@field public item_id integer @只在ERT_JUANZENG时使用
---@field public gubi_num integer @只在ERT_JUANZENG时使用，古币数量
---@field public contribute integer @贡献值
---@field public spoils_item PBItemData[] @只在战利品发放时使用，物品id
---@field public season_point integer @只在ERT_SEASON_POINT时使用
---@field public op_mgr_name string @发放管理员名字
---@field public rechage_num integer @玩家充值的灵石数量
---@field public operater_uid integer @操作玩家UID


---@class PBGuildDutyInfo
---@field public duty_id integer
---@field public duty_name string
---@field public duty_right integer @按位读取
---@field public duty_level integer @职位等级


---@class PBGuidJoinCon
---@field public can_join boolean @允许加入
---@field public min_rank integer @最低段位（品阶<<16+品级）
---@field public min_level integer @最低等级
---@field public notice string @宣传语
---@field public join_check boolean @加入工会需要审核


---@class PBGuildSimpleInfo
---@field public node_name string @所属节点名称
---@field public guild_id integer @公会uid
---@field public name string @公会名
---@field public level integer @公会等级
---@field public president_id integer @公会长ID
---@field public president_name string @公会长名称
---@field public build_time integer @创建时间
---@field public exp integer @公会经验
---@field public contribute integer @公会贡献值
---@field public activeness integer @公会活跃度
---@field public status integer @公会状态（正常，冻结或者销毁）
---@field public accouncenment string @公会公告
---@field public member_count integer @公会成员人数（当前）
---@field public member_max_count integer @公会人数上限
---@field public join_con PBGuidJoinCon @公会加入条件
---@field public recommend_endtime integer @公会推荐到期时间
---@field public item_headid integer @公会头像ID
---@field public item_frameid integer @公会头像框ID


---@class PBGuildSimpleList
---@field public guild_list PBGuildSimpleInfo[] @公会列表


---@class PBGuildMemberList
---@field public member_list PBGuildUserData[] @成员列表


---@class PBGuildDutyList
---@field public duty_list PBGuildDutyInfo[] @职位列表


---@class PBGuildRewardInfo
---@field public reward_id integer @奖励物品ID
---@field public reward_num integer @奖励数量


---@class PBGuildRewardList
---@field public rewards PBGuildRewardInfo[] @奖励列表


---@class PBGuildTaskInfo
---@field public task_id integer @任务配置表ID
---@field public start_time integer @接受任务时间
---@field public cur_num integer @当前完成数量（任务进度）
---@field public state integer @任务状态。0表示未接受，1表示已接受未完成，2表示已完成未领奖，3表示已领奖。


---@class PBGuildTaskList
---@field public items PBGuildTaskInfo[] @


---@class PBGuildShopItemPrice
---@field public priclog_type integer
---@field public price_count integer


---@class PBGuildShopItemInfo
---@field public s_id integer @唯一ID
---@field public item_price PBGuildShopItemPrice @价格
---@field public buy_count integer @已购买的数量
---@field public item_id integer @物品id
---@field public pre_time integer @上次刷新时间


---@class PBGuildShopItemInfoList
---@field public items PBGuildShopItemInfo[]


---@class PBGuildInfoDB
---@field public guild_id integer @公会uid
---@field public name string @公会名
---@field public level integer @公会等级
---@field public president_id integer @公会长ID
---@field public president_name string @公会长名称
---@field public build_time integer @创建时间
---@field public exp integer @公会经验
---@field public contribute integer @公会贡献值
---@field public activeness integer @公会活跃度
---@field public status integer @公会状态（正常，冻结或者销毁）
---@field public master_ids integer[] @公会管理员列表
---@field public members table<integer, PBGuildMemberData> @玩家列表
---@field public member_count integer @公会成员人数（当前）
---@field public member_num_level integer @成员人数等级(第几等级）
---@field public member_max_num integer @最大成员人数
---@field public accouncenment string @公会公告
---@field public apply_list PBGuildUserApplyList @公会申请列表
---@field public freeze_time integer @冻结开始时间
---@field public apply_count integer @公会申请数量
---@field public destory_time integer @销毁时间
---@field public duty_list PBGuildDutyList @职位列表
---@field public announcenment_modify_time integer @公告上次修改时间
---@field public season_activeness integer @本赛季活跃度
---@field public join_con PBGuidJoinCon @公会加入条件
---@field public name_modify_time integer @公会名字上次修改时间
---@field public spoilsmgr_ids integer[] @公会战利品管理员
---@field public recommend_endtime integer @公会推荐到期时间
---@field public item_headid integer @公会头像ID
---@field public item_frameid integer @公会头像框ID
---@field public open_juanzeng boolean @打开捐赠


---@class PBGuildShopDB
---@field public guild_id integer @公会uid
---@field public shop_item_list PBGuildShopItemInfoList @商店物品信息
---@field public last_refresh_time integer @上次刷新时间


---@class PBGuildBagDB
---@field public guild_id integer @公会uid
---@field public bag_item_list PBItemData[] @公会仓库（包含货币、普通物品、皮肤等）


---@class PBGuildRecordDB
---@field public guild_id integer @公会uid
---@field public record_list PBGuildRecordInfo[] @记录列表


---@class PBGuildUserGuildFullData
---@field public guild_info PBGuildInfoDB
---@field public self_guild_data PBGuildMemberData @玩家自己的信息


---@class PBGuildInviteRecordInfo
---@field public invite_uid integer
---@field public invite_name string
---@field public invite_guild_simple PBGuildSimpleInfo


---@class PBGuildInviteList
---@field public invites PBGuildInviteRecordInfo[]


---@class PBGuildSpoilsItem
---@field public item_id integer @道具ID为配置文件中的ID 使用分段来区分道具类型 [货币/普通道具/皮肤]
---@field public item_count integer


---@class PBGuildSpoilsItemList
---@field public item_list PBGuildSpoilsItem[]


---@class PBUserApplyInfo
---@field public guild_id integer
---@field public apply_time integer


---@class PBUserGuildApplyList
---@field public apply_list PBUserApplyInfo[] @已申请的公会列表


---@class PBGuildAddItems2BagCmd
---@field public guild_id integer @公会ID
---@field public items PBItemData[] @添加物品列表
---@field public add_or_del boolean @加操作还是减操作


---@class PBGuildAddItemsCmd
---@field public items PBItemData[] @添加物品列表


---@class PBGuildDelItemsCmd
---@field public items PBItemData[] @添加物品列表


---@class PBGuildUpdateGuildUserDataCmd
---@field public user_data PBGuildMemberData @自己的最新公会数据


---@class PBGuildUpdateGuildBagCmd
---@field public items PBItemData[] @变化的仓库物品列表


---@class PBGuildUpdateGuildLevelCmd
---@field public new_level integer @最新等级


---@class PBGuildUpgradeMemberMaxcountReqCmd
---@field public uid integer


---@class PBGuildUpgradeMemberMaxcountRspCmd
---@field public cur_member_maxcount integer
---@field public sucucess integer @1成功 0提示灵币不足


---@class PBGuildDonateReqCmd
---@field public uid integer
---@field public num integer @捐赠数量（只能灵石）
---@field public item_id integer @注意这个值如果不为0就是捐灵石，否则就是战利品


---@class PBGuildDonateRspCmd
---@field public num integer @捐赠数量（只能灵石）
---@field public item_id integer @注意这个值如果不为0就是捐灵石，否则就是战利品


---@class PBGuildGetSalaryReqCmd
---@field public uid integer


---@class PBGuildGetSalaryRspCmd
---@field public get_items PBItemData[] @获得的物品（列表）


---@class PBGuildUpdateDutyListCmd
---@field public duty_list PBGuildDutyList @职位列表


---@class PBGuildUpdateGuildRecordInfoCmd
---@field public record_list PBGuildRecordDB


---@class PBGuildGetMembersReqCmd
---@field public page_index integer
---@field public uid integer


---@class PBGuildGetMembersRspCmd
---@field public page_index integer @分页索引
---@field public member_count integer @成员总数
---@field public members PBGuildMemberList


---@class PBGuildBoardcastPlayerApplyCmd
---@field public apply_count integer @申请消息数量


---@class PBGuildBoardcastPlayerJoinCmd
---@field public user_info PBGuildUserData
---@field public guild_id integer @公会ID


---@class PBGuildBoardcastPlayerExitCmd
---@field public uid integer
---@field public guild_id integer @公会ID


---@class PBGuildBoardcastGuildDismissCmd
---@field public guild_id integer @公会ID


---@class PBGuildUpdateMeApplyGuildListCmd
---@field public me_apply_list PBUserGuildApplyList
---@field public b_apply boolean @申请还是取消？


---@class PBGuildFullDataUpdateCmd
---@field public full_data PBGuildUserGuildFullData


---@class PBGuildPlayerSetGuildInfoCmd
---@field public node_id integer @公会所在节点ID
---@field public guild_id integer @公会id
---@field public guild_name string @公会name
---@field public guild_level integer @公会等级
---@field public guild_prosperity integer @公会繁荣度


---@class PBGuildGetGuildListReqCmd
---@field public idx integer
---@field public uid integer
---@field public sort_type integer @排序类型。1
---@field public b_asc boolean @是否升序
---@field public min_level integer @最低等级
---@field public max_level integer @最高等级
---@field public min_member_count integer @最低人数
---@field public max_member_count integer @最高人数
---@field public page_count integer @固定每页多少条记录
---@field public brecomment boolean @只搜索推荐列表
---@field public bjoin_con boolean @只搜索可以加入的公会


---@class PBGuildGetGuildListRspCmd
---@field public guild_list PBGuildSimpleList @公会列表
---@field public sort_type integer @排序类型。1
---@field public b_asc boolean @是否升序
---@field public min_level integer @最低等级
---@field public max_level integer @最高等级
---@field public min_member_count integer @最低人数
---@field public max_member_count integer @最高人数
---@field public max_count integer @总人数
---@field public page_count integer @固定每页多少条记录
---@field public brecomment boolean @只搜索推荐列表
---@field public bjoin_con boolean @只搜索可以加入的公会


---@class PBGuildCreateGuildReqCmd
---@field public uid integer
---@field public guild_name string @公会名


---@class PBGuildCreateGuildRspCmd
---@field public code integer @错误码
---@field public guild_id integer @公会id
---@field public guild_name string @公会名


---@class PBGuildApplyJoinGuildReqCmd
---@field public guild_id integer @公会id
---@field public uid integer
---@field public b_apply boolean @是否申请。false为取消申请
---@field public applyer_uid integer @申请人uid


---@class PBGuildApplyJoinGuildRspCmd
---@field public code integer @错误码
---@field public guild_id integer @公会id
---@field public guild_name string @公会名


---@class PBGuildAnswerApplyJoinGuildReqCmd
---@field public applyer_uid integer @申请人uid
---@field public b_agree boolean @是否同意
---@field public uid integer


---@class PBGuildAnswerApplyJoinGuildRspCmd
---@field public applyer_uid integer @申请人uid
---@field public b_agree boolean @是否同意


---@class PBGuildSearchGuildReqCmd
---@field public key string
---@field public uid integer


---@class PBGuildSearchGuildRspCmd
---@field public guid_info PBGuildSimpleInfo @公会简略信息


---@class PBGuildInviteJoinGuildReqCmd
---@field public uid integer
---@field public invited_key string @被邀请人的名称、uid或steam_id
---@field public be_invite_uid integer @被邀请人uid


---@class PBGuildInviteJoinGuildRspCmd
---@field public invited_uid integer @被邀请人uid


---@class PBGuildAnswerInviteJoinGuildReqCmd
---@field public inviter_uid integer @邀请人uid
---@field public b_agree boolean @是否同意
---@field public uid integer @回复人uid
---@field public applyer_uid integer @回复人uid


---@class PBGuildQuitReqCmd
---@field public uid integer


---@class PBGuildQuitRspCmd
---@field public code integer


---@class PBGuildExpelQuitReqCmd
---@field public expel_uid integer @被踢玩家uid
---@field public uid integer


---@class PBGuildExpelQuitRspCmd
---@field public code integer
---@field public expel_uid integer @被踢玩家uid


---@class PBGuildGrantReqCmd
---@field public target_uid integer @目标玩家uid
---@field public duty_id integer @职务ID
---@field public uid integer


---@class PBGuildGrantRspCmd
---@field public target_uid integer @目标玩家uid
---@field public duty_id integer @职务ID


---@class PBGuildDemiseReqCmd
---@field public target_uid integer @目标玩家uid
---@field public uid integer


---@class PBGuildDemiseRspCmd
---@field public new_master_uid integer @新会长ID
---@field public new_master_name string @新会长名称


---@class PBGuildDismissReqCmd
---@field public uid integer


---@class PBGuildDismissRspCmd


---@class PBGuildThawReqCmd
---@field public uid integer


---@class PBGuildThawRspCmd


---@class PBGuildModifyAnnouncementReqCmd
---@field public new_announcement string
---@field public uid integer


---@class PBGuildModifyAnnouncementRspCmd
---@field public new_announcement string
---@field public modify_time integer


---@class PBGuildAddDutyReqCmd
---@field public duty_name string @职位名称
---@field public uid integer


---@class PBGuildAddDutyRspCmd
---@field public new_duty_id integer @新职位ID
---@field public duty_name string @职位名称


---@class PBGuildDelDutyReqCmd
---@field public duty_id integer
---@field public uid integer


---@class PBGuildDelDutyRspCmd
---@field public duty_id integer


---@class PBGuildModifyDutyRightReqCmd
---@field public uid integer
---@field public duty integer @职位ID
---@field public new_right integer @新增或删除的权限
---@field public b_set boolean @true为设置，false为取消


---@class PBGuildModifyDutyRightRspCmd
---@field public duty integer @职位ID
---@field public new_right integer @最新的权限


---@class PBGuildModifyDutyNameReqCmd
---@field public duty_id integer
---@field public new_name string
---@field public uid integer


---@class PBGuildModifyDutyNameRspCmd
---@field public duty_id integer
---@field public new_name string


---@class PBGuildModifyDutyLevelReqCmd
---@field public duty_id integer
---@field public new_level integer
---@field public uid integer


---@class PBGuildModifyDutyLevelRspCmd
---@field public duty_id integer
---@field public new_level integer


---@class PBGuildUpgradeReqCmd
---@field public uid integer


---@class PBGuildUpgradeRspCmd
---@field public new_level integer @新等级


---@class PBGuildModifyHeadIconReqCmd
---@field public head_icon integer
---@field public uid integer


---@class PBGuildModifyHeadIconRspCmd
---@field public head_icon integer


---@class PBGuildGetApplyListReqCmd
---@field public uid integer


---@class PBGuildGetApplyListRspCmd
---@field public apply_list PBGuildUserApplyList
---@field public total_count integer @总申请数


---@class PBGuildModifyGuildNameReqCmd
---@field public new_name string
---@field public uid integer


---@class PBGuildModifyGuildNameRspCmd
---@field public new_name string
---@field public uid integer


---@class PBGuildExchangeItemReqCmd
---@field public uid integer
---@field public item_id integer @兑换物品ID
---@field public item_num integer @兑换物品数量


---@class PBGuildExchangeItemRspCmd
---@field public item_id integer @兑换物品ID
---@field public item_num integer @兑换物品数量


---@class PBGuildAcceptTaskReqCmd
---@field public uid integer
---@field public task_id integer @任务ID


---@class PBGuildAcceptTaskRspCmd
---@field public task_id integer @任务ID


---@class PBGuildGetTaskRewardReqCmd
---@field public uid integer
---@field public task_id integer @任务ID


---@class PBGuildGetTaskRewardRspCmd
---@field public task_id integer @任务ID
---@field public reward_list PBGuildRewardList @任务奖励信息


---@class PBGuildUpdateTaskInfoRspCmd
---@field public task_info PBGuildTaskInfo @任务奖励信息


---@class PBGuildUpdateTaskListRspCmd
---@field public all_tasks PBGuildTaskList


---@class PBGuildUpdateGuildInfoRspCmd
---@field public guild_info PBGuildUserGuildFullData


---@class PBSetGuildJoinConditionReqCmd
---@field public uid integer
---@field public join_con PBGuidJoinCon


---@class PBSetGuildJoinConditionRspCmd
---@field public join_con PBGuidJoinCon


---@class PBGuildUpdateMeInviteGuildListCmd
---@field public me_invite_list PBGuildInviteList


---@class PBGuildRecordListReqCmd
---@field public log_type integer @1
---@field public idx integer @
---@field public uid integer
---@field public sort_type integer @排序类型。1按记录时间 2按玩家昵称
---@field public b_asc boolean @是否升序
---@field public b_manager boolean
---@field public des_uid integer @制定用户记录 如果des_uid=0,查询所有玩家
---@field public page_count integer @固定每页多少条记录


---@class PBGuildRecordListRspCmd
---@field public log_type integer @
---@field public idx integer @
---@field public uid integer
---@field public sort_type integer @排序类型。1
---@field public b_asc boolean @是否升序
---@field public record_list PBGuildRecordDB
---@field public total_count integer @总记录条数
---@field public page_count integer @固定每页多少条记录


---@class PBGuildSetSpoilsMgrReqCmd
---@field public uid integer
---@field public b_set boolean @true任命，false为取消
---@field public des_uid integer @目标uid


---@class PBGuildSetSpoilsMgrRspCmd
---@field public sucess boolean @成功true,失败false
---@field public b_set boolean @true任命，false为取消
---@field public des_uid integer @目标uid


---@class PBGuildDkpChangeReqCmd
---@field public uid integer
---@field public change_num integer @修改的值
---@field public des_uid integer @目标uid
---@field public desc string @备注


---@class PBGuildDkpChangeRspCmd
---@field public change_num integer @修改的值
---@field public des_uid integer @目标uid
---@field public cur_dkp integer @当前dkp的值
---@field public desc string @备注


---@class PBGuildSendSpoilsReqCmd
---@field public uid integer
---@field public des_uid integer @目标uid
---@field public slist PBGuildSpoilsItemList @发送的物品


---@class PBGuildSendSpoilsRspCmd
---@field public sucess boolean


---@class PBGuildUpdateShopReqCmd
---@field public uid integer
---@field public tab_index integer @所在标签页


---@class PBGuildUpdateShopInfoCmd
---@field public tab_index integer @所在标签页
---@field public item_list PBGuildShopItemInfoList @物品列表


---@class PBGuildShopBuyItemReqCmd
---@field public uid integer
---@field public tab_index integer @所在标签页
---@field public s_id integer @商店物品id
---@field public item_count integer @物品数量


---@class PBGuildShopBuyItemRspCmd
---@field public tab_index integer @所在标签页
---@field public s_id integer @商店物品id
---@field public item_count integer @物品数量
---@field public sucess boolean @是否成功


---@class PBGuildDayMissionAwardReqCmd
---@field public uid integer
---@field public day_mission boolean
---@field public mission_id integer


---@class PBGuildDayMissionAwardRspCmd
---@field public code integer
---@field public item_list PBItemData[]
---@field public day_mission boolean


---@class PBGuildBuyRecommentReqCmd
---@field public uid integer


---@class PBGuildBuyRecommentRspCmd
---@field public uid integer
---@field public sucess boolean @是否成功
---@field public recommend_endtime integer @推荐位到期时间


---@class PBGuildSetHeadReqCmd
---@field public uid integer
---@field public item_headid integer
---@field public item_frameid integer


---@class PBGuildSetHeadRspCmd
---@field public item_headid integer
---@field public item_frameid integer


---@class PBSetGuildStatusCmd
---@field public guild_id integer @公会ID
---@field public status integer @状态


---@class PBOpenGuildJuanZengCmd
---@field public guild_id integer @公会ID
---@field public open_juanzeng boolean @是否开启捐赠


---@class PBCoin
---@field public coin_id integer
---@field public coin_count integer


---@class PBUserCoins
---@field public coins table<integer, PBCoin>


---@class PBBlessing
---@field public bless_id integer
---@field public idx integer


---@class PBAttribute
---@field public id integer
---@field public val integer


---@class PBTag
---@field public id integer
---@field public val integer


---@class PBSkill
---@field public config_id integer
---@field public star integer


---@class PBDurabItem
---@field public cur_durability integer @当前耐久度
---@field public strong_value integer @坚固值


---@class PBMagicItem
---@field public cur_durability integer @当前耐久度
---@field public strong_value integer @耐久度上限
---@field public tabooword_id integer @讳字id
---@field public light_cnt integer @开光次数
---@field public tags PBTag[] @随机词条id,最大10条
---@field public ability_tag PBTag[] @能力词条


---@class PBDiagramsCard
---@field public cur_durability integer @当前耐久度
---@field public strong_value integer @耐久度上限
---@field public tabooword_id integer @讳字id
---@field public light_cnt integer @开光次数
---@field public tags PBTag[] @随机词条id,最大10条
---@field public ability_tag PBTag[] @能力词条


---@class PBAweItem
---@field public idx integer
---@field public up_lv_fail_cnt integer @当前等级升级失败次数


---@class PBAntique
---@field public price PBCoin @价格
---@field public remain_identify_num integer @剩余鉴定次数
---@field public tags PBTag[] @词条数量,最大10个
---@field public is_fake integer
---@field public identify_histroy integer[] @历史鉴定结果


---@class PBItemCommon
---@field public config_id integer
---@field public uniqid integer
---@field public item_count integer
---@field public item_type integer @道具类型
---@field public trade_cnt integer @可交易次数


---@class PBItemSpecial
---@field public durab_item PBDurabItem
---@field public magic_item PBMagicItem
---@field public diagrams_item PBDiagramsCard
---@field public awe_item PBAweItem
---@field public antique_item PBAntique


---@class PBItemData
---@field public itype integer
---@field public common_info PBItemCommon
---@field public special_info PBItemSpecial


---@class PBItemSimple
---@field public config_id integer
---@field public item_count integer
---@field public uniqid integer


---@class PBAuctionExtra
---@field public up_level integer @升级
---@field public up_exp integer
---@field public star_level integer @升星
---@field public exattr_list PBAttribute[] @额外属性
---@field public element_tags PBTag[] @元素词条id
---@field public tags PBTag[] @普通词条id
---@field public life integer @阴寿
---@field public ghost_air integer @阴气
---@field public monster_skills PBSkill[] @鬼怪技能
---@field public unlock_equip_num integer @解锁装备数量
---@field public nick_name string @怪物昵称


---@class PBPlayedGodsData
---@field public idx integer @槽位
---@field public gods_id integer @神明id


---@class PBPlayedGodsDataS
---@field public played_gods_list PBPlayedGodsData[]


---@class PBGodsDataS
---@field public gods_list integer[] @神明列表
---@field public played_gods_data PBPlayedGodsDataS @出战的神明数据


---@class PBImage
---@field public config_id integer @配置ID
---@field public star_level integer @星级
---@field public exp integer @经验值


---@class PBSkinImage
---@field public config_id integer @配置ID


---@class PBUserImage
---@field public item_image table<integer, PBImage> @道具图鉴
---@field public magic_item_image table<integer, PBImage> @法器图鉴
---@field public human_diagrams_image table<integer, PBImage> @角色八卦牌图鉴
---@field public ghost_diagrams_image table<integer, PBImage> @鬼宠八卦牌图鉴
---@field public skin_image table<integer, PBSkinImage> @皮肤动作表情图鉴


---@class PBImageGetDataReqCmd
---@field public uid integer


---@class PBImageGetDataRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public image_data PBUserImage


---@class PBImageUpdateSyncCmd
---@field public update_images PBUserImage


---@class PBMailItem
---@field public item_id integer @道具ID为配置文件中的ID 使用分段来区分道具类型 [货币/普通道具/皮肤]
---@field public item_count integer


---@class PBMailData
---@field public mail_id integer
---@field public mail_type integer
---@field public beg_ts integer
---@field public end_ts integer
---@field public mail_title string
---@field public mail_content string
---@field public is_read integer
---@field public is_get integer
---@field public is_del integer
---@field public items PBMailItem[]


---@class PBGetMailItemReqCmd
---@field public uid integer
---@field public mail_id integer


---@class PBGetMailItemRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public mail_data PBMailData


---@class PBUserSelectionOpt
---@field public op_type integer
---@field public uid integer
---@field public target_id integer
---@field public target_pos integer
---@field public confirm_role boolean
---@field public ban_roleids integer[]


---@class PBUserSelection
---@field public uid integer
---@field public camp_type integer
---@field public disable_map_id integer
---@field public disable_role_ids integer[]
---@field public selection_map_id integer
---@field public confirm_role_ok boolean


---@class PBUserSelectionS
---@field public cur_state integer
---@field public human_select_index integer
---@field public human_disable_map integer
---@field public human_disable_roles integer[]
---@field public ghost_disable_map integer
---@field public ghost_disable_roles integer[]
---@field public rand_map_id integer
---@field public ghost PBUserSelection
---@field public humans table<integer, PBUserSelection>
---@field public system_ban_config_ids integer[]


---@class PBMatchCreateRoomReqCmd
---@field public uid integer
---@field public match_type integer
---@field public camp_type integer
---@field public map_id integer


---@class PBMatchReqCmd
---@field public uid integer
---@field public match_type integer
---@field public camp_type integer
---@field public need_ai boolean


---@class PBMatchRspCmd
---@field public code integer


---@class PBNotifyMatchAckCmd
---@field public room_id integer


---@class PBMatchAckReqCmd
---@field public uid integer
---@field public room_id integer
---@field public is_agree boolean


---@class PBMatchSelectionOptReqCmd
---@field public uid integer
---@field public room_id integer
---@field public opt PBUserSelectionOpt


---@class PBMatchSelectionOptRspCmd
---@field public code integer


---@class PBMatchNotifyEnterDSCmd
---@field public ds_ip string
---@field public ds_port integer
---@field public room_key string


---@class PBMatchNotifyGameOverCmd
---@field public room_id integer
---@field public code integer


---@class PBMatchCancelReqCmd
---@field public uid integer
---@field public room_id integer


---@class PBMatchCancelRspCmd
---@field public code integer


---@class PBMatchNotifyFailCmd
---@field public room_id integer
---@field public code integer


---@class PBMatchNotifyPlayerNumCmd
---@field public room_id integer
---@field public human_num integer
---@field public ghost_num integer
---@field public red_team_num integer
---@field public blue_team_num integer


---@class PBConditionData
---@field public cond_id integer
---@field public cond_type integer
---@field public cond_target integer
---@field public progress integer
---@field public is_complete integer


---@class PBMissionData
---@field public mission_id integer
---@field public mission_type integer
---@field public is_complete integer
---@field public is_get integer
---@field public beg_ts integer
---@field public end_ts integer
---@field public cond_datas PBConditionData[]


---@class PBUpdateMissionSeverSyncCmd
---@field public uid integer
---@field public cond_id integer
---@field public cond_type integer
---@field public update_progress integer


---@class PBUpdateMissionClientSyncCmd
---@field public update_mission_datas PBMissionData[] @好友数据


---@class PBRankData
---@field public id integer @宗门id或者玩家id
---@field public idx integer
---@field public score integer
---@field public rank_data string


---@class PBRankInfo
---@field public rank_id integer
---@field public beg_ts integer
---@field public end_ts integer
---@field public datas PBRankData[]


---@class PBGetRankInfoReqCmd
---@field public uid integer
---@field public rank_id integer


---@class PBGetRankInfoRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public rank_info PBRankInfo @排行榜数据
---@field public self_data PBRankData @本榜中玩家自身数据


---@class PBPinchFaceData
---@field public setting_data string


---@class PBStudyBook
---@field public book_id integer
---@field public start_time integer
---@field public end_time integer
---@field public now_time integer


---@class PBSimpleRoleData
---@field public config_id integer @配置ID
---@field public skins table<integer, integer> @穿戴皮肤
---@field public magic_item_id integer @携带法器id


---@class PBRoleData
---@field public config_id integer @配置ID
---@field public star_level integer @星级
---@field public exp integer @经验值
---@field public magic_item PBItemData @法器
---@field public digrams_cards table<integer, PBItemData> @八卦牌
---@field public equip_books table<integer, integer> @已装备真经
---@field public study_books table<integer, PBStudyBook> @学习中真经
---@field public last_check_time integer @上次检测时间
---@field public skins table<integer, integer> @穿戴皮肤
---@field public cur_main_skill_id integer @选定主技能id
---@field public main_skill table<integer, PBSkill> @可选主技能
---@field public cur_minor_skill1_id integer @选定小技能1id
---@field public minor_skill1 table<integer, PBSkill> @可选小技能1
---@field public cur_minor_skill2_id integer @选定小技能2id
---@field public minor_skill2 table<integer, PBSkill> @可选小技能2
---@field public cur_passive_skill_id integer @选定被动技能id
---@field public passive_skill table<integer, PBSkill> @可选被动技能
---@field public emoji integer[] @表情槽
---@field public up_lv_rewards table<integer, integer> @已领取的升级奖励


---@class PBUserRoleDatas
---@field public battle_role_id integer
---@field public role_list table<integer, PBRoleData>


---@class PBClientGetUsrRolesInfoReqCmd
---@field public uid integer


---@class PBClientGetUsrRolesInfoRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer @用户ID
---@field public roles_info PBUserRoleDatas @所有角色数据


---@class PBRoleInfoSyncCmd
---@field public roles_info PBUserRoleDatas @变更的角色数据


---@class PBRoleWearEquipReqCmd
---@field public uid integer
---@field public roleid integer @角色id
---@field public bag_name string @背包名
---@field public pos integer @准备穿戴的装备在背包中的格子号
---@field public equip_config_id integer @准备穿戴的装备配置id
---@field public equip_uniqid integer @准备穿戴的装备唯一id
---@field public equip_idx integer @装备的位置


---@class PBRoleWearEquipRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer
---@field public bag_name string
---@field public pos integer
---@field public equip_config_id integer
---@field public equip_uniqid integer
---@field public equip_idx integer


---@class PBRoleTakeOffEquipReqCmd
---@field public uid integer
---@field public roleid integer @角色id
---@field public bag_name string @背包名
---@field public takeoff_config_id integer @准备卸下的装备配置id
---@field public takeoff_uniqid integer @准备卸下的装备唯一id
---@field public takeoff_idx integer @卸下的位置


---@class PBRoleTakeOffEquipRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer @角色id
---@field public bag_name string @背包名
---@field public takeoff_config_id integer @准备卸下的装备配置id
---@field public takeoff_uniqid integer @准备卸下的装备唯一id
---@field public takeoff_idx integer @卸下的位置


---@class PBRoleWearSkinReqCmd
---@field public uid integer
---@field public roleid integer @角色id
---@field public skins table<integer, integer> @穿戴皮肤


---@class PBRoleWearSkinRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer @角色id
---@field public skins table<integer, integer> @穿戴皮肤


---@class PBRoleChangeEmojiReqCmd
---@field public uid integer
---@field public roleid integer @角色id
---@field public emoji integer[] @表情


---@class PBRoleChangeEmojiRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer @角色id
---@field public emoji integer[] @表情


---@class PBChangeBattleRoleReqCmd
---@field public uid integer
---@field public roleid integer @角色id


---@class PBChangeBattleRoleRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer @角色id


---@class PBRoleSkillUpStarReqCmd
---@field public uid integer
---@field public roleid integer
---@field public skill_id integer


---@class PBRoleSkillUpStarRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer
---@field public skill_id integer


---@class PBRoleGetUpLvRewardReqCmd
---@field public uid integer
---@field public roleid integer
---@field public reward_id integer


---@class PBRoleGetUpLvRewardRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer
---@field public reward_id integer


---@class PBRoleStudyBookReqCmd
---@field public uid integer
---@field public roleid integer
---@field public book_id integer


---@class PBRoleStudyBookRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer
---@field public book_id integer


---@class PBRoleSkillCompositeReqCmd
---@field public uid integer
---@field public roleid integer
---@field public composite_id integer @合成id


---@class PBRoleSkillCompositeRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer
---@field public composite_id integer @合成id


---@class PBRoleSkillSwitchReqCmd
---@field public uid integer
---@field public roleid integer
---@field public skill_type integer @技能类型
---@field public skill_id integer @技能id


---@class PBRoleSkillSwitchRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer
---@field public skill_type integer @技能类型
---@field public skill_id integer @技能id


---@class PBRoomSearchInfo
---@field public roomid integer
---@field public chapter integer @章节
---@field public difficulty integer @难度
---@field public playercnt integer @当前玩家人数
---@field public master_id integer @房主id
---@field public master_name string @房主昵称
---@field public isopen integer @是否公开
---@field public needpwd integer @是否需要密码
---@field public describe string @房间描述


---@class PBRoomMemberInfo
---@field public seat_idx integer
---@field public is_ready integer @0未准备 1已准备
---@field public mem_info PBUserAttr


---@class PBRoomInfo
---@field public roomid integer
---@field public isopen integer
---@field public needpwd integer
---@field public pwd string
---@field public chapter integer
---@field public difficulty integer
---@field public state integer
---@field public describe string
---@field public map_id integer
---@field public boss_id integer
---@field public master_id integer @房主id


---@class PBRoomApplyInfo
---@field public uid integer
---@field public apply_info PBUserAttr
---@field public apply_time integer


---@class PBRoomInviteInfo
---@field public invite_uid integer
---@field public mem_uid integer


---@class PBRoomWholeInfo
---@field public room_data PBRoomInfo
---@field public master_id integer @房主id
---@field public master_name string @房主昵称
---@field public players PBRoomMemberInfo[] @成员信息
---@field public apply_list PBRoomApplyInfo[] @申请信息
---@field public invite_list PBRoomInviteInfo[] @邀请信息


---@class PBCreateRoomReqCmd
---@field public uid integer
---@field public isopen integer @是否开放
---@field public needpwd integer
---@field public pwd string
---@field public chapter integer
---@field public difficulty integer
---@field public describe string


---@class PBCreateRoomRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public roomid integer


---@class PBSearchRoomReqCmd
---@field public uid integer
---@field public roomid integer
---@field public chapter integer
---@field public difficulty integer
---@field public start_idx integer @搜索的起始序号


---@class PBSearchRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public roomid integer
---@field public chapter integer
---@field public difficulty integer
---@field public start_idx integer @搜索的起始序号
---@field public search_data PBRoomSearchInfo[]


---@class PBModRoomReqCmd
---@field public uid integer
---@field public roomid integer
---@field public isopen integer
---@field public needpwd integer
---@field public pwd string
---@field public chapter integer
---@field public difficulty integer
---@field public describe string


---@class PBModRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public isopen integer
---@field public needpwd integer
---@field public pwd string
---@field public chapter integer
---@field public difficulty integer


---@class PBRoomSyncCmd
---@field public roomid integer
---@field public sync_type integer @1--修改房间信息 2--玩家加入 3--玩家退出 4--玩家被踢出 5--玩家改变准备状态 6--有玩家申请
---@field public sync_info PBRoomWholeInfo


---@class PBApplyRoomReqCmd
---@field public uid integer
---@field public roomid integer


---@class PBApplyRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public roomid integer


---@class PBDealApplyRoomReqCmd
---@field public deal_uid integer
---@field public deal_op integer


---@class PBDealApplyRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public deal_uid integer
---@field public deal_op integer


---@class PBEnterRoomReqCmd
---@field public uid integer
---@field public roomid integer
---@field public pwd string


---@class PBEnterRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roomid integer


---@class PBEnterRoomSyncCmd
---@field public roomid integer
---@field public member_data PBRoomMemberInfo


---@class PBExitRoomReqCmd
---@field public uid integer
---@field public roomid integer


---@class PBExitRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roomid integer


---@class PBExitRoomSyncCmd
---@field public uid integer
---@field public roomid integer


---@class PBKickRoomReqCmd
---@field public self_uid integer
---@field public roomid integer
---@field public kick_uid integer


---@class PBKickRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public self_uid integer
---@field public roomid integer
---@field public kick_uid integer


---@class PBKickRoomSyncCmd
---@field public roomid integer
---@field public kick_uid integer


---@class PBInviteRoomReqCmd
---@field public uid integer
---@field public roomid integer
---@field public invite_uid integer


---@class PBInviteRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roomid integer
---@field public invite_uid integer


---@class PBInviteRoomSyncCmd
---@field public roomid integer
---@field public mem_uid integer
---@field public mem_name string
---@field public room_info PBRoomInfo


---@class PBDealInviteRoomReqCmd
---@field public uid integer
---@field public roomid integer
---@field public deal_op integer @1--同意, 2--拒绝


---@class PBDealInviteRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roomid integer
---@field public deal_op integer


---@class PBDealInviteRoomSyncCmd
---@field public invite_uid integer
---@field public deal_op integer


---@class PBReadyRoomReqCmd
---@field public uid integer
---@field public roomid integer
---@field public ready_op integer @1--准备, 2--取消准备


---@class PBReadyRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roomid integer
---@field public is_ready integer


---@class PBReadyRoomSyncCmd
---@field public uid integer
---@field public roomid integer
---@field public is_ready integer


---@class PBGetRoomInfoReqCmd
---@field public uid integer
---@field public roomid integer


---@class PBGetRoomInfoRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public room_data PBRoomInfo
---@field public member_datas PBRoomMemberInfo[]


---@class PBStartGameRoomReqCmd
---@field public uid integer
---@field public roomid integer


---@class PBStartGameRoomRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roomid integer


---@class PBEnterDsRoomSyncCmd
---@field public roomid integer
---@field public ds_address string
---@field public ds_ip string


---@class PBTeamInfo
---@field public team_id integer
---@field public master_id integer @队长id
---@field public user_list PBUserAttr[] @
---@field public is_del boolean @是否解散
---@field public match_type integer @游戏模式


---@class PBTeamStatusCmd
---@field public team_id integer @team_id
---@field public team_status boolean @team status


---@class PBTeamInfoReqCmd
---@field public team_id integer @team_id


---@class PBTeamInfoRspCmd
---@field public code integer
---@field public team_info PBTeamInfo @队伍信息


---@class PBTeamCreateReqCmd
---@field public uid integer
---@field public base_data PBUserAttr @游戏基础数据
---@field public match_type integer @


---@class PBTeamCreateRspCmd
---@field public code integer
---@field public team_id integer @队伍ID


---@class PBTeamExitReqCmd
---@field public uid integer


---@class PBTeamExitRspCmd
---@field public code integer @fail 1 success 0


---@class PBTeamKickoutReqCmd
---@field public uid integer
---@field public target_uid integer @uid


---@class PBTeamKickoutRspCmd
---@field public code integer
---@field public target_uid integer @uid


---@class PBTeamJoinReqCmd
---@field public uid integer
---@field public master_uid integer @uid（队长的ID)
---@field public team_id integer @队伍id
---@field public base_data PBUserAttr @游戏基础数据


---@class PBTeamJoinRspCmd
---@field public code integer
---@field public master_uid integer @uid（队长的ID)
---@field public team_id integer @队伍id


---@class PBTradeBankProductData
---@field public trade_id integer @交易id
---@field public product_id integer @商品id(道具的配置id)
---@field public cur_num integer @当前剩余数量
---@field public book_num integer @被预订数量
---@field public sale_num integer @售出数量
---@field public price integer @单价
---@field public uid integer @卖家id
---@field public beg_ts integer @本商品创建时间
---@field public end_ts integer @本商品下架时间
---@field public state integer @当前商品状态


---@class PBSelfTradeBankData
---@field public box_capacity integer @交易行货架数
---@field public product_list PBTradeBankProductData[]


---@class PBGetTradeBankInfoReqCmd
---@field public uid integer


---@class PBGetTradeBankInfoRspCmd
---@field public code integer @服务器返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public self_trade_bank_info PBSelfTradeBankData @自己的交易行数据


---@class PBRankNode
---@field public grade integer @品阶
---@field public level integer @品级
---@field public star integer @当前星星数量
---@field public score integer @隐藏分
---@field public zhu_ji_points integer @筑基点（用于升星或抵扣星星）
---@field public all_stars integer @所有星星数（记录玩家所有的星星数量，用于换算品阶、品级这些）


---@class PBRankLevel
---@field public ghost_rank PBRankNode
---@field public human_rank PBRankNode
---@field public ghost_top_rank PBRankNode
---@field public human_top_rank PBRankNode


---@class PBUserAttr
---@field public uid integer
---@field public plateform_id string
---@field public nick_name string
---@field public head_icon integer
---@field public sex integer @0-未选 1-男 2-女
---@field public praise_num integer @点赞
---@field public head_frame integer @头像框
---@field public account_create_time integer @账户创建时间
---@field public account_level integer
---@field public account_exp integer
---@field public guild_id integer
---@field public guild_name string
---@field public rank_level PBRankLevel
---@field public cur_show_role PBSimpleRoleData
---@field public pinch_face_data PBPinchFaceData @捏脸数据
---@field public title integer @当前佩戴的称号
---@field public player_flag integer @玩家标签
---@field public online_time integer @最后一次在线时间
---@field public sum_online_time integer @累计在线时长 单位秒
---@field public pa_flag integer @是否禁言等操作
---@field public cur_show_ghost PBSimpleGhostData
---@field public is_online integer @是否在线


---@class PBClientGetUsrSimInfoReqCmd
---@field public uid integer


---@class PBClientGetUsrSimInfoRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer @用户ID
---@field public info PBUserAttr @简略信息


---@class PBClientGetAllUserAttrReqCmd
---@field public uid integer


---@class PBClientGetAllUserAttrRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer @用户ID
---@field public info PBUserAttr @简略信息


---@class PBSetUserAttrReqCmd
---@field public uid integer
---@field public type integer @个人信息类型 @see PBPersonInfoType
---@field public value integer @个人信息值


---@class PBSetUserAttrRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public type integer @个人信息类型 @see PBPersonInfoType
---@field public value integer @个人信息值


---@class PBUserAttrSyncCmd
---@field public attr PBUserAttr


---@class PBClientGetUsrBagsInfoReqCmd
---@field public uid integer


---@class PBClientGetUsrBagsInfoRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer @用户ID
---@field public bags_info PBBags @所有背包数据
---@field public coins_info PBUserCoins @所有货币数据


---@class PBClientLightReqCmd
---@field public uid integer
---@field public roleid integer
---@field public ghostid integer
---@field public bag_name string
---@field public pos integer
---@field public config_id integer
---@field public uniqid integer


---@class PBClientLightRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer
---@field public ghostid integer
---@field public bag_name string
---@field public pos integer
---@field public config_id integer
---@field public uniqid integer


---@class PBClientItemUpLvReqCmd
---@field public uid integer
---@field public config_id integer
---@field public add_exp integer


---@class PBClientItemUpLvRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public config_id integer
---@field public add_exp integer


---@class PBUseItemUpLvReqCmd
---@field public uid integer
---@field public target_id integer
---@field public cost_id integer
---@field public cost_num integer


---@class PBUseItemUpLvRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public target_id integer
---@field public cost_id integer
---@field public cost_num integer


---@class PBClientItemUpStarReqCmd
---@field public uid integer
---@field public config_id integer


---@class PBClientItemUpStarRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public config_id integer


---@class PBClientItemRepairReqCmd
---@field public uid integer
---@field public repair_uniqid integer @要修复的装备唯一id
---@field public pos integer @装备所在的格子号


---@class PBClientItemRepairRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public repair_uniqid integer
---@field public pos integer @装备所在的格子号


---@class PBGetOtherDetailReqCmd
---@field public uid integer
---@field public quest_uid integer


---@class PBGetOtherDetailRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer @自己的uid
---@field public quest_uid integer @他人uid
---@field public info PBUserAttr @简略信息


---@class PBUseSkinGiftReqCmd
---@field public uid integer @自己的uid
---@field public gift_id integer @礼包id


---@class PBUseSkinGiftRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer @自己的uid
---@field public gift_id integer @礼包id


---@class PBSureCompositeReqCmd
---@field public uid integer
---@field public composite_id integer @合成id


---@class PBSureCompositeRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public composite_id integer @合成id


---@class PBRandomCompositeReqCmd
---@field public uid integer
---@field public composite_id integer @合成id


---@class PBRandomCompositeRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public composite_id integer @合成id


---@class PBInlayTabooWordReqCmd
---@field public uid integer
---@field public roleid integer @角色id
---@field public ghost_uniqid integer @鬼宠唯一id
---@field public inlay_type integer @1-法器 2-八卦牌
---@field public uniqid integer @道具id
---@field public tabooword_id integer @讳字id


---@class PBInlayTabooWordRspCmd
---@field public code integer @服务器验证返回,0成功,其他失败
---@field public error string @错误信息
---@field public uid integer
---@field public roleid integer @角色id
---@field public ghost_uniqid integer @鬼宠唯一id
---@field public inlay_type integer @1-法器 2-八卦牌
---@field public uniqid integer @道具id
---@field public tabooword_id integer @讳字id








---@class auth_scripts
---@field Auth Auth


---@class center_scripts
---@field Center Center


---@class dgate_scripts
---@field DGate DGate


---@class dsnode_scripts
---@field DsNode DsNode


---@class gate_scripts
---@field Gate Gate


---@class mail_scripts
---@field Mail Mail


---@class room_scripts
---@field Aoi Aoi
---@field Room Room


---@class user_scripts
---@field Bag Bag
---@field ChatProxy ChatProxy
---@field City City
---@field Friend Friend
---@field Ghost Ghost
---@field GuildProxy GuildProxy
---@field Hello Hello
---@field Item Item
---@field ItemDefine ItemDefine
---@field ItemImage ItemImage
---@field MatchProxy MatchProxy
---@field Role Role
---@field Room Room
---@field Team Team
---@field User User
---@field UserModel UserModel




---@class agent_scripts
---@field Agent Agent


---@class guild_scripts
---@field Guild Guild
---@field GuildModel GuildModel
---@field GuildRecord GuildRecord
---@field GuildShop GuildShop
---@field GuildTask GuildTask
---@field GuildTreasury GuildTreasury




---@class matchhelp_scripts
---@field MatchHelp MatchHelp


---@class matchmgr_scripts
---@field MatchMgr MatchMgr


---@class matchroom_scripts
---@field CreateDS CreateDS
---@field Matching Matching
---@field MatchRoom MatchRoom
---@field Selection Selection
---@field Settle Settle




---@class chatchannel_scripts
---@field ChatChannel ChatChannel


---@class chatmgr_scripts
---@field ChatMgr ChatMgr




---@class citymgr_scripts
---@field Citymgr Citymgr


---@class friendmgr_scripts
---@field Friendmgr Friendmgr


---@class guildmgr_scripts
---@field GuildMgr GuildMgr


---@class guildnamemgr_scripts
---@field GuildNameMgr GuildNameMgr


---@class nodemgr_scripts
---@field Nodemgr Nodemgr


---@class roommgr_scripts
---@field Roommgr Roommgr


---@class teammgr_scripts
---@field Teammgr Teammgr


---@class usermgr_scripts
---@field Usermgr Usermgr




---@class node_scripts
---@field Console Console


---@class static_conf
---@field AllTag AllTag_cfg[]
---@field AllTagPool AllTagPool_cfg[]
---@field BaGuaBrand BaGuaBrand_cfg[]
---@field BaGuaBrandUpLv BaGuaBrandUpLv_cfg[]
---@field Book Book_cfg[]
---@field CommonConfig CommonConfig_cfg[]
---@field Composite Composite_cfg[]
---@field EquipmentTagPool EquipmentTagPool_cfg[]
---@field FriendConfig FriendConfig_cfg[]
---@field GameChapter GameChapter_cfg[]
---@field GamePropUpLv GamePropUpLv_cfg[]
---@field GhostEquipmentUpLv GhostEquipmentUpLv_cfg[]
---@field GhostInfo GhostInfo_cfg[]
---@field GhostUpLv GhostUpLv_cfg[]
---@field HumanRole HumanRole_cfg[]
---@field HumanSkill HumanSkill_cfg[]
---@field Init Init_cfg[]
---@field Item Item_cfg[]
---@field LightConvert LightConvert_cfg[]
---@field LightCost LightCost_cfg[]
---@field MagicItem MagicItem_cfg[]
---@field MagicItemUpLv MagicItemUpLv_cfg[]
---@field RandomComposite RandomComposite_cfg[]
---@field RankLevel RankLevel_cfg[]
---@field RoleLvAward RoleLvAward_cfg[]
---@field RoleUpLv RoleUpLv_cfg[]
---@field Skin Skin_cfg[]
---@field UniqueItem UniqueItem_cfg[]
---@field UpLvCostIDMapping UpLvCostIDMapping_cfg[]
---@field UpStar UpStar_cfg[]
