syntax = "proto3";
import "item.proto";

message PBAuctionData
{
	int32 start_price = 1;	// 起拍价格
	int32 buyout_price = 2;	// 一口价
	int32 cur_price = 3;	// 当前价格
	int64 buyer_uid = 4;	// 当前买家id
}

message PBAuctionProductBaseData
{
	int64 auction_id		= 1;	//交易id
	int64 seller_uid	= 2;	//卖家id
	int32 config_id		= 3;	//道具配置id
	int64 uniqid		= 4;	//道具唯一id
	PBItemData item_data = 5;	//商品信息
	int64 beg_ts		= 6;	//商品上架时间
	int64 end_ts		= 7;	//商品下架时间
	int32 delay_cnt		= 8;	//延期次数
	int32 state			= 9;	//当前状态
	PBAuctionData auction_data = 10;	//拍卖数据
}

message PBAuctionLogData
{
	int64 log_id	= 1;
	int64 auction_id	= 2;
	int32 config_id		= 3;
	int64 uniqid		= 4;
	PBItemData item_data = 5;	//商品信息
	int32 deal_price	= 6;	//成交价
	int64 seller_uid	= 7;	//卖家id
	int64 buyer_uid		= 8;	//买家id
	int64 auction_ts	= 9;	//交易时间
	int32 auction_tax	= 10;	//交易税
	int32 send_seller_mail	= 11;	//是否已发送邮件
	int32 send_buyer_mail	= 12;	//是否已发送邮件
}

message PBSelfAuctionInfo
{
	int32 box_capacity	= 1;	//交易行货架数
	int32 can_onsale_cnt	= 2;	//当前可上架次数
	int64 update_ts			= 3;	//上架次数刷新时间
	repeated int64 auction_ids	= 4;
	repeated int64 log_ids	= 5;
	map<int64, int64> focus_auctionid_ts	= 6;	//关注id-关注时间
}

message PBSelfAuctionData
{
	PBSelfAuctionInfo simple_info	= 1;
	map<int64, PBAuctionProductBaseData> product_list	= 2;
	repeated PBAuctionLogData log_list	= 3;
}

// 客户端请求自己的交易行数据
message PBGetAuctionInfoReqCmd
{
    int64 uid		= 1;
}

// 客户端请求自己的交易行数据 返回信息
message PBGetAuctionInfoRspCmd
{
    int32 code = 1; // 服务器返回,0成功,其他失败
    string error = 2; // 错误信息
    int64 uid	= 3;
    PBSelfAuctionData self_auction_info	= 4; //自己的交易行数据
}

// 客户端搜索拍卖行商品
message PBSearchAuctionProductReqCmd
{
	int64 uid	= 1;
	repeated int32 config_ids	= 2;	//搜索的道具配置id,可以为空
	int32 condition1	= 3;	//条件1
	int32 condition2	= 4;	//条件2
	int32 condition3	= 5;	//条件3
	int32 condition4	= 6;	//条件4
	int32 condition5	= 7;	//条件5
	repeated int32 custom_conditions1	= 8;	//自定义条件组1
	int32 custom_condition2	= 9;	//自定义条件2
	int32 sort_type		= 10;	//排序类型
	int32 start_idx		= 11;	//起始序号
}

message PBSearchAuctionProductRspCmd
{
	int32 code = 1; // 服务器返回,0成功,其他失败
    string error = 2; // 错误信息
    int64 uid	= 3;
	repeated PBAuctionProductBaseData	search_products = 4;	//搜索到的商品信息 key为auction_id
}

// 上架拍卖行商品
message PBAuctionSaleReqCmd
{
	int64 uid	= 1;
	int32 config_id	= 2;
	int64 uniqid	= 3;
	int32 pos	= 4;
	int32 start_price	= 5;	// 起拍价格
	int32 buyout_price	= 6;	// 一口价
	int64 sale_ts	= 7;
}

message PBAuctionSaleRspCmd
{
	int32 code = 1; // 服务器返回,0成功,其他失败
    string error = 2; // 错误信息
    int64 uid	= 3;
	int64 auction_id	= 4;	//交易号
}

// 购买交易行商品
message PBAuctionBuyReqCmd
{
	int64 uid	= 1;
	int64 auction_id	= 2;
	int64 uniqid	= 3;
	int32 buy_price	= 4;
}

message PBAuctionBuyRspCmd
{
	int32 code = 1; // 服务器返回,0成功,其他失败
    string error = 2; // 错误信息
	int64 uid	= 3;
	int32 real_buy_price = 4;
}

// 下架交易行商品
message PBAuctionTakeOffProductReqCmd
{
	int64 uid	= 1;
	int64 auction_id	= 2;
}

message PBAuctionTakeOffProductRspCmd
{
	int32 code = 1; // 服务器返回,0成功,其他失败
    string error = 2; // 错误信息
	int64 uid	= 3;
	int64 auction_id	= 4;
}

message PBAuctionChangeFocusIdReqCmd
{
	int64 uid	= 1;
	int32 focus_op	= 2;	//0--取消 1--关注
	int64 focus_id	= 3;
}

message PBAuctionChangeFocusIdRspCmd
{
	int32 code = 1; // 服务器返回,0成功,其他失败
    string error = 2; // 错误信息
	int64 uid	= 3;
	map<int64, int64> focus_id_ts	= 4;
}