syntax = "proto3";



// The serialized message and the context of it.
message PBMessagePack {
    // 收发包时表示目标ID[nodeid + 自增id]
    // a.小于0x1000000: 0全局服务器(GlobalServer) 1-254：指定一个网关服务器 255: 系统服务器(由当前网关根据消息号处理)
    // b.大于0x1000000时候：高位BYTE代表目标服务器节点id
    int32 net_id = 1;

    // 保留字段，暂时都为 0
    int32 broadcast = 2;

    // The stub for RPC callbacks.
    // 0 means the message is not a RPC message.
    int32 stub_id = 3;

    // The MessageType either defined in @MessageType enum, or defined in user space.
    int32 msg_type = 4;

    // The serialized message. It's Protobuf-marshalled byte array if the message is defined in @MessageType.
    bytes  msg_body = 5;

}

// DS创建数据
message PBDsCreateData
{
	int64 ds_id         = 1;
	int32 chapter		= 2;
	int32 difficulty	= 3;
	int32 map_id		= 4;
	int32 boss_id		= 5;
	string server_ip    = 6;
	int32 server_port	= 7;
	repeated int32 uids = 8;
}

// 客户端和服务器直接通信的消息
message PBPacketCmd {
    repeated PBMessagePack messages = 1;
}

// 客户端发起ping
message PBPingCmd
{
    double time = 1;   // 用户统计服务器之间延时
}

// 服务器回复pong
message PBPongCmd
{
    double time = 1;   // 用户统计服务器之间延时
}

// 账户Buff效果类型枚举
enum AccountBuffType
{
    Buff_None            = 0;  // 无效果
    Buff_RoleExp         = 1;  // 结算加成_角色经验
    Buff_AccExp          = 2;  // 结算加成_账户经验
    Buff_Currency1       = 3;  // 结算加成_货币加成1（货币id=1）
    Buff_Weight          = 4;  // 增加局内负重
    Buff_TradeSlot       = 5;  // 交易行同时上架栏位增加
    Buff_AuctionLimit    = 6;  // 每日寄售总次数上限增加
    Buff_Warehouse       = 7;  // 局外基础仓库存储容量扩充
    Buff_DurabilityCost  = 8;  // 修复耐久度货币消耗百分比降低
    Buff_RoleExpPct      = 9;  // 结算时角色经验值百分比加成
    Buff_DeathLoss       = 10; // 局内死亡时耐久度损失比例降低
    Buff_EvacLoss        = 11; // 撤离失败时耐久度损失比例降低
}

// 账户buff加成
message PBBuffData
{
	int32 buff_id	= 1;
	int32 buff_effect	= 2;
	int32 period_type	= 3;
	int64 end_ts		= 4;
	int32 surplus_cnt	= 5;
	int32 coefficient	= 6;
}