syntax = "proto3";

message PBConditionData
{
	int32 cond_id		= 1;
	int32 target_cnt	= 2;
	int32 now_cnt		= 3;
	int32 is_complete	= 4;
	repeated int32 params	= 5;
}

message PBMissionData
{
    int32 mission_id	= 1;
    int32 mission_type	= 2;
	int32 mission_state	= 3;
	int64 beg_ts		= 4;
	int64 end_ts		= 5;
	repeated PBConditionData cond_datas = 6;
}

// 更新任务进度
message PBUpdateMissionSeverSyncCmd
{
    // 协议数据
    int64 uid				= 1;
	int32 cond_id			= 2;
	int32 cond_type			= 3;
	int32 update_progress	= 4;
}

// 更新任务进度 通知玩家
message PBUpdateMissionClientSyncCmd
{
    repeated PBMissionData update_mission_datas	= 1; //好友数据
}





