#pragma once
#include "CoreMinimal.h"
#include "Net/ProtobufMessage.h"
#include "activity.generated.h"

// Generated by Proto3 to UE5 Struct Converter



USTRUCT(BlueprintType)
struct FPBActivityData
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 ActivityId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 BegTs = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 EndTs = 0LL;
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasActivityId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasBegTs = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasEndTs = false;
};
// 客户端请求活动数据
UCLASS(BlueprintType)
class UPBGetActivityInfoReqCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	// 协议数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 Uid = 0LL;
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUid = false;
};
// 客户端请求活动数据返回信息
UCLASS(BlueprintType)
class UPBGetActivityInfoRspCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	// 服务器返回,0成功,其他失败
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 Code = 0;
	// 错误信息
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	FString Error = TEXT("");
	// 协议数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 Uid = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	TArray<FPBActivityData> ActivityDatas = {};
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCode = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasError = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUid = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasActivityDatas = false;
};
