#pragma once
#include "CoreMinimal.h"
#include "Net/ProtobufMessage.h"
#include "common.generated.h"

// Generated by Proto3 to UE5 Struct Converter


// The serialized message and the context of it.
USTRUCT(BlueprintType)
struct FPBMessagePack
{
	GENERATED_BODY()

	// 收发包时表示目标ID[nodeid + 自增id]
	// a.小于0x1000000: 0全局服务器(GlobalServer) 1-254：指定一个网关服务器 255: 系统服务器(由当前网关根据消息号处理)
	// b.大于0x1000000时候：高位BYTE代表目标服务器节点id
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 NetId = 0;
	// 保留字段，暂时都为 0
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 Broadcast = 0;
	// The stub for RPC callbacks.
	// 0 means the message is not a RPC message.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 StubId = 0;
	// The MessageType either defined in @MessageType enum, or defined in user space.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 MsgType = 0;
	// The serialized message. It's Protobuf-marshalled byte array if the message is defined in @MessageType.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	TArray<uint8> MsgBody = {};
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasNetId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasBroadcast = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasStubId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasMsgType = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasMsgBody = false;
};
// 客户端和服务器直接通信的消息
UCLASS(BlueprintType)
class UPBPacketCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	TArray<FPBMessagePack> Messages = {};
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasMessages = false;
};
// 客户端发起ping
UCLASS(BlueprintType)
class UPBPingCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	// 用户统计服务器之间延时
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	double Time = 0.0;
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasTime = false;
};
// 服务器回复pong
UCLASS(BlueprintType)
class UPBPongCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	// 用户统计服务器之间延时
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	double Time = 0.0;
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasTime = false;
};
