// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend.proto

#ifdef _MSC_VER
#	pragma warning(disable: 4125)
#	pragma warning(disable: 4647)
#	pragma warning(disable: 4668)
#	pragma warning(disable: 4800)
#	pragma warning(disable: 4946)
#endif

#include "friend.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR PBFriendData::PBFriendData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nick_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.guild_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.name_remark_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_.head_id_)*/0
  , /*decltype(_impl_.account_level_)*/0
  , /*decltype(_impl_.online_state_)*/0
  , /*decltype(_impl_.group_id_)*/0
  , /*decltype(_impl_.friend_time_)*/int64_t{0}
  , /*decltype(_impl_.head_frame_)*/0
  , /*decltype(_impl_.title_)*/0
  , /*decltype(_impl_.guild_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBFriendDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBFriendDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBFriendDataDefaultTypeInternal() {}
  union {
    PBFriendData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBFriendDataDefaultTypeInternal _PBFriendData_default_instance_;
PROTOBUF_CONSTEXPR PBApplyFriendData::PBApplyFriendData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nick_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.guild_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_.head_id_)*/0
  , /*decltype(_impl_.account_level_)*/0
  , /*decltype(_impl_.head_frame_)*/0
  , /*decltype(_impl_.title_)*/0
  , /*decltype(_impl_.guild_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBApplyFriendDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBApplyFriendDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBApplyFriendDataDefaultTypeInternal() {}
  union {
    PBApplyFriendData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBApplyFriendDataDefaultTypeInternal _PBApplyFriendData_default_instance_;
PROTOBUF_CONSTEXPR PBGetFriendInfoReqCmd::PBGetFriendInfoReqCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBGetFriendInfoReqCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBGetFriendInfoReqCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBGetFriendInfoReqCmdDefaultTypeInternal() {}
  union {
    PBGetFriendInfoReqCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBGetFriendInfoReqCmdDefaultTypeInternal _PBGetFriendInfoReqCmd_default_instance_;
PROTOBUF_CONSTEXPR PBGetFriendInfoRspCmd::PBGetFriendInfoRspCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.friend_datas_)*/{}
  , /*decltype(_impl_.apply_datas_)*/{}
  , /*decltype(_impl_.error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBGetFriendInfoRspCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBGetFriendInfoRspCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBGetFriendInfoRspCmdDefaultTypeInternal() {}
  union {
    PBGetFriendInfoRspCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBGetFriendInfoRspCmdDefaultTypeInternal _PBGetFriendInfoRspCmd_default_instance_;
PROTOBUF_CONSTEXPR PBApplyFriendReqCmd::PBApplyFriendReqCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.apply_data_)*/nullptr
  , /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBApplyFriendReqCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBApplyFriendReqCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBApplyFriendReqCmdDefaultTypeInternal() {}
  union {
    PBApplyFriendReqCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBApplyFriendReqCmdDefaultTypeInternal _PBApplyFriendReqCmd_default_instance_;
PROTOBUF_CONSTEXPR PBApplyFriendRspCmd::PBApplyFriendRspCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBApplyFriendRspCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBApplyFriendRspCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBApplyFriendRspCmdDefaultTypeInternal() {}
  union {
    PBApplyFriendRspCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBApplyFriendRspCmdDefaultTypeInternal _PBApplyFriendRspCmd_default_instance_;
static ::_pb::Metadata file_level_metadata_friend_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_friend_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_friend_2eproto = nullptr;

const uint32_t TableStruct_friend_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.uid_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.head_id_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.nick_name_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.account_level_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.online_state_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.group_id_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.friend_time_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.head_frame_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.title_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.guild_id_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.guild_name_),
  PROTOBUF_FIELD_OFFSET(::PBFriendData, _impl_.name_remark_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendData, _impl_.uid_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendData, _impl_.head_id_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendData, _impl_.nick_name_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendData, _impl_.account_level_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendData, _impl_.head_frame_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendData, _impl_.title_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendData, _impl_.guild_id_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendData, _impl_.guild_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBGetFriendInfoReqCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBGetFriendInfoReqCmd, _impl_.uid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBGetFriendInfoRspCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBGetFriendInfoRspCmd, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::PBGetFriendInfoRspCmd, _impl_.error_),
  PROTOBUF_FIELD_OFFSET(::PBGetFriendInfoRspCmd, _impl_.uid_),
  PROTOBUF_FIELD_OFFSET(::PBGetFriendInfoRspCmd, _impl_.friend_datas_),
  PROTOBUF_FIELD_OFFSET(::PBGetFriendInfoRspCmd, _impl_.apply_datas_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendReqCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendReqCmd, _impl_.uid_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendReqCmd, _impl_.apply_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendRspCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendRspCmd, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendRspCmd, _impl_.error_),
  PROTOBUF_FIELD_OFFSET(::PBApplyFriendRspCmd, _impl_.uid_),
};
static const ::_pbi::MigrationSchema schemas_friend_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::PBFriendData)},
  { 18, -1, -1, sizeof(::PBApplyFriendData)},
  { 32, -1, -1, sizeof(::PBGetFriendInfoReqCmd)},
  { 39, -1, -1, sizeof(::PBGetFriendInfoRspCmd)},
  { 50, -1, -1, sizeof(::PBApplyFriendReqCmd)},
  { 58, -1, -1, sizeof(::PBApplyFriendRspCmd)},
};

static const ::_pb::Message* const file_default_instances_friend_2eproto[] = {
  &::_PBFriendData_default_instance_._instance,
  &::_PBApplyFriendData_default_instance_._instance,
  &::_PBGetFriendInfoReqCmd_default_instance_._instance,
  &::_PBGetFriendInfoRspCmd_default_instance_._instance,
  &::_PBApplyFriendReqCmd_default_instance_._instance,
  &::_PBApplyFriendRspCmd_default_instance_._instance,
};

const char descriptor_table_protodef_friend_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014friend.proto\"\361\001\n\014PBFriendData\022\013\n\003uid\030\001"
  " \001(\003\022\017\n\007head_id\030\002 \001(\005\022\021\n\tnick_name\030\003 \001(\t"
  "\022\025\n\raccount_level\030\004 \001(\005\022\024\n\014online_state\030"
  "\005 \001(\005\022\020\n\010group_id\030\006 \001(\005\022\023\n\013friend_time\030\007"
  " \001(\003\022\022\n\nhead_frame\030\010 \001(\005\022\r\n\005title\030\t \001(\005\022"
  "\020\n\010guild_id\030\n \001(\005\022\022\n\nguild_name\030\013 \001(\t\022\023\n"
  "\013name_remark\030\014 \001(\t\"\244\001\n\021PBApplyFriendData"
  "\022\013\n\003uid\030\001 \001(\003\022\017\n\007head_id\030\002 \001(\005\022\021\n\tnick_n"
  "ame\030\003 \001(\t\022\025\n\raccount_level\030\004 \001(\005\022\022\n\nhead"
  "_frame\030\005 \001(\005\022\r\n\005title\030\006 \001(\005\022\020\n\010guild_id\030"
  "\007 \001(\005\022\022\n\nguild_name\030\010 \001(\t\"$\n\025PBGetFriend"
  "InfoReqCmd\022\013\n\003uid\030\001 \001(\003\"\217\001\n\025PBGetFriendI"
  "nfoRspCmd\022\014\n\004code\030\001 \001(\005\022\r\n\005error\030\002 \001(\t\022\013"
  "\n\003uid\030\003 \001(\003\022#\n\014friend_datas\030\004 \003(\0132\r.PBFr"
  "iendData\022\'\n\013apply_datas\030\005 \003(\0132\022.PBApplyF"
  "riendData\"J\n\023PBApplyFriendReqCmd\022\013\n\003uid\030"
  "\001 \001(\003\022&\n\napply_data\030\002 \001(\0132\022.PBApplyFrien"
  "dData\"\?\n\023PBApplyFriendRspCmd\022\014\n\004code\030\001 \001"
  "(\005\022\r\n\005error\030\002 \001(\t\022\013\n\003uid\030\003 \001(\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_friend_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_friend_2eproto = {
    false, false, 758, descriptor_table_protodef_friend_2eproto,
    "friend.proto",
    &descriptor_table_friend_2eproto_once, nullptr, 0, 6,
    schemas_friend_2eproto, file_default_instances_friend_2eproto, TableStruct_friend_2eproto::offsets,
    file_level_metadata_friend_2eproto, file_level_enum_descriptors_friend_2eproto,
    file_level_service_descriptors_friend_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_friend_2eproto_getter() {
  return &descriptor_table_friend_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_friend_2eproto(&descriptor_table_friend_2eproto);

// ===================================================================

class PBFriendData::_Internal {
 public:
};

PBFriendData::PBFriendData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBFriendData)
}
PBFriendData::PBFriendData(const PBFriendData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBFriendData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nick_name_){}
    , decltype(_impl_.guild_name_){}
    , decltype(_impl_.name_remark_){}
    , decltype(_impl_.uid_){}
    , decltype(_impl_.head_id_){}
    , decltype(_impl_.account_level_){}
    , decltype(_impl_.online_state_){}
    , decltype(_impl_.group_id_){}
    , decltype(_impl_.friend_time_){}
    , decltype(_impl_.head_frame_){}
    , decltype(_impl_.title_){}
    , decltype(_impl_.guild_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.nick_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nick_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_nick_name().empty()) {
    _this->_impl_.nick_name_.Set(from._internal_nick_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.guild_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.guild_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_guild_name().empty()) {
    _this->_impl_.guild_name_.Set(from._internal_guild_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.name_remark_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_remark_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name_remark().empty()) {
    _this->_impl_.name_remark_.Set(from._internal_name_remark(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.uid_, &from._impl_.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.guild_id_) -
    reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.guild_id_));
  // @@protoc_insertion_point(copy_constructor:PBFriendData)
}

inline void PBFriendData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nick_name_){}
    , decltype(_impl_.guild_name_){}
    , decltype(_impl_.name_remark_){}
    , decltype(_impl_.uid_){int64_t{0}}
    , decltype(_impl_.head_id_){0}
    , decltype(_impl_.account_level_){0}
    , decltype(_impl_.online_state_){0}
    , decltype(_impl_.group_id_){0}
    , decltype(_impl_.friend_time_){int64_t{0}}
    , decltype(_impl_.head_frame_){0}
    , decltype(_impl_.title_){0}
    , decltype(_impl_.guild_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.nick_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nick_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.guild_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.guild_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.name_remark_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_remark_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PBFriendData::~PBFriendData() {
  // @@protoc_insertion_point(destructor:PBFriendData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBFriendData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.nick_name_.Destroy();
  _impl_.guild_name_.Destroy();
  _impl_.name_remark_.Destroy();
}

void PBFriendData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBFriendData::Clear() {
// @@protoc_insertion_point(message_clear_start:PBFriendData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nick_name_.ClearToEmpty();
  _impl_.guild_name_.ClearToEmpty();
  _impl_.name_remark_.ClearToEmpty();
  ::memset(&_impl_.uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.guild_id_) -
      reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.guild_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBFriendData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 head_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.head_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string nick_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_nick_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBFriendData.nick_name"));
        } else
          goto handle_unusual;
        continue;
      // int32 account_level = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.account_level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 online_state = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.online_state_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 group_id = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.group_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 friend_time = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.friend_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 head_frame = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.head_frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 title = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.title_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 guild_id = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.guild_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string guild_name = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_guild_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBFriendData.guild_name"));
        } else
          goto handle_unusual;
        continue;
      // string name_remark = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_name_remark();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBFriendData.name_remark"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBFriendData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBFriendData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_uid(), target);
  }

  // int32 head_id = 2;
  if (this->_internal_head_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_head_id(), target);
  }

  // string nick_name = 3;
  if (!this->_internal_nick_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nick_name().data(), static_cast<int>(this->_internal_nick_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBFriendData.nick_name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_nick_name(), target);
  }

  // int32 account_level = 4;
  if (this->_internal_account_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_account_level(), target);
  }

  // int32 online_state = 5;
  if (this->_internal_online_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_online_state(), target);
  }

  // int32 group_id = 6;
  if (this->_internal_group_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_group_id(), target);
  }

  // int64 friend_time = 7;
  if (this->_internal_friend_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(7, this->_internal_friend_time(), target);
  }

  // int32 head_frame = 8;
  if (this->_internal_head_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_head_frame(), target);
  }

  // int32 title = 9;
  if (this->_internal_title() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_title(), target);
  }

  // int32 guild_id = 10;
  if (this->_internal_guild_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_guild_id(), target);
  }

  // string guild_name = 11;
  if (!this->_internal_guild_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_guild_name().data(), static_cast<int>(this->_internal_guild_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBFriendData.guild_name");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_guild_name(), target);
  }

  // string name_remark = 12;
  if (!this->_internal_name_remark().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name_remark().data(), static_cast<int>(this->_internal_name_remark().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBFriendData.name_remark");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_name_remark(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBFriendData)
  return target;
}

size_t PBFriendData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBFriendData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string nick_name = 3;
  if (!this->_internal_nick_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_nick_name());
  }

  // string guild_name = 11;
  if (!this->_internal_guild_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_guild_name());
  }

  // string name_remark = 12;
  if (!this->_internal_name_remark().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name_remark());
  }

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  // int32 head_id = 2;
  if (this->_internal_head_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_head_id());
  }

  // int32 account_level = 4;
  if (this->_internal_account_level() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_account_level());
  }

  // int32 online_state = 5;
  if (this->_internal_online_state() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_online_state());
  }

  // int32 group_id = 6;
  if (this->_internal_group_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_group_id());
  }

  // int64 friend_time = 7;
  if (this->_internal_friend_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_friend_time());
  }

  // int32 head_frame = 8;
  if (this->_internal_head_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_head_frame());
  }

  // int32 title = 9;
  if (this->_internal_title() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_title());
  }

  // int32 guild_id = 10;
  if (this->_internal_guild_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_guild_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBFriendData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBFriendData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBFriendData::GetClassData() const { return &_class_data_; }


void PBFriendData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBFriendData*>(&to_msg);
  auto& from = static_cast<const PBFriendData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBFriendData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nick_name().empty()) {
    _this->_internal_set_nick_name(from._internal_nick_name());
  }
  if (!from._internal_guild_name().empty()) {
    _this->_internal_set_guild_name(from._internal_guild_name());
  }
  if (!from._internal_name_remark().empty()) {
    _this->_internal_set_name_remark(from._internal_name_remark());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (from._internal_head_id() != 0) {
    _this->_internal_set_head_id(from._internal_head_id());
  }
  if (from._internal_account_level() != 0) {
    _this->_internal_set_account_level(from._internal_account_level());
  }
  if (from._internal_online_state() != 0) {
    _this->_internal_set_online_state(from._internal_online_state());
  }
  if (from._internal_group_id() != 0) {
    _this->_internal_set_group_id(from._internal_group_id());
  }
  if (from._internal_friend_time() != 0) {
    _this->_internal_set_friend_time(from._internal_friend_time());
  }
  if (from._internal_head_frame() != 0) {
    _this->_internal_set_head_frame(from._internal_head_frame());
  }
  if (from._internal_title() != 0) {
    _this->_internal_set_title(from._internal_title());
  }
  if (from._internal_guild_id() != 0) {
    _this->_internal_set_guild_id(from._internal_guild_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBFriendData::CopyFrom(const PBFriendData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBFriendData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBFriendData::IsInitialized() const {
  return true;
}

void PBFriendData::InternalSwap(PBFriendData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.nick_name_, lhs_arena,
      &other->_impl_.nick_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.guild_name_, lhs_arena,
      &other->_impl_.guild_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_remark_, lhs_arena,
      &other->_impl_.name_remark_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBFriendData, _impl_.guild_id_)
      + sizeof(PBFriendData::_impl_.guild_id_)
      - PROTOBUF_FIELD_OFFSET(PBFriendData, _impl_.uid_)>(
          reinterpret_cast<char*>(&_impl_.uid_),
          reinterpret_cast<char*>(&other->_impl_.uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBFriendData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_friend_2eproto_getter, &descriptor_table_friend_2eproto_once,
      file_level_metadata_friend_2eproto[0]);
}

// ===================================================================

class PBApplyFriendData::_Internal {
 public:
};

PBApplyFriendData::PBApplyFriendData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBApplyFriendData)
}
PBApplyFriendData::PBApplyFriendData(const PBApplyFriendData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBApplyFriendData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nick_name_){}
    , decltype(_impl_.guild_name_){}
    , decltype(_impl_.uid_){}
    , decltype(_impl_.head_id_){}
    , decltype(_impl_.account_level_){}
    , decltype(_impl_.head_frame_){}
    , decltype(_impl_.title_){}
    , decltype(_impl_.guild_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.nick_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nick_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_nick_name().empty()) {
    _this->_impl_.nick_name_.Set(from._internal_nick_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.guild_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.guild_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_guild_name().empty()) {
    _this->_impl_.guild_name_.Set(from._internal_guild_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.uid_, &from._impl_.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.guild_id_) -
    reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.guild_id_));
  // @@protoc_insertion_point(copy_constructor:PBApplyFriendData)
}

inline void PBApplyFriendData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nick_name_){}
    , decltype(_impl_.guild_name_){}
    , decltype(_impl_.uid_){int64_t{0}}
    , decltype(_impl_.head_id_){0}
    , decltype(_impl_.account_level_){0}
    , decltype(_impl_.head_frame_){0}
    , decltype(_impl_.title_){0}
    , decltype(_impl_.guild_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.nick_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nick_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.guild_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.guild_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PBApplyFriendData::~PBApplyFriendData() {
  // @@protoc_insertion_point(destructor:PBApplyFriendData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBApplyFriendData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.nick_name_.Destroy();
  _impl_.guild_name_.Destroy();
}

void PBApplyFriendData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBApplyFriendData::Clear() {
// @@protoc_insertion_point(message_clear_start:PBApplyFriendData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nick_name_.ClearToEmpty();
  _impl_.guild_name_.ClearToEmpty();
  ::memset(&_impl_.uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.guild_id_) -
      reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.guild_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBApplyFriendData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 head_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.head_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string nick_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_nick_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBApplyFriendData.nick_name"));
        } else
          goto handle_unusual;
        continue;
      // int32 account_level = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.account_level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 head_frame = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.head_frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 title = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.title_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 guild_id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.guild_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string guild_name = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_guild_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBApplyFriendData.guild_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBApplyFriendData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBApplyFriendData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_uid(), target);
  }

  // int32 head_id = 2;
  if (this->_internal_head_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_head_id(), target);
  }

  // string nick_name = 3;
  if (!this->_internal_nick_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nick_name().data(), static_cast<int>(this->_internal_nick_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBApplyFriendData.nick_name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_nick_name(), target);
  }

  // int32 account_level = 4;
  if (this->_internal_account_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_account_level(), target);
  }

  // int32 head_frame = 5;
  if (this->_internal_head_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_head_frame(), target);
  }

  // int32 title = 6;
  if (this->_internal_title() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_title(), target);
  }

  // int32 guild_id = 7;
  if (this->_internal_guild_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_guild_id(), target);
  }

  // string guild_name = 8;
  if (!this->_internal_guild_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_guild_name().data(), static_cast<int>(this->_internal_guild_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBApplyFriendData.guild_name");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_guild_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBApplyFriendData)
  return target;
}

size_t PBApplyFriendData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBApplyFriendData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string nick_name = 3;
  if (!this->_internal_nick_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_nick_name());
  }

  // string guild_name = 8;
  if (!this->_internal_guild_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_guild_name());
  }

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  // int32 head_id = 2;
  if (this->_internal_head_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_head_id());
  }

  // int32 account_level = 4;
  if (this->_internal_account_level() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_account_level());
  }

  // int32 head_frame = 5;
  if (this->_internal_head_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_head_frame());
  }

  // int32 title = 6;
  if (this->_internal_title() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_title());
  }

  // int32 guild_id = 7;
  if (this->_internal_guild_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_guild_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBApplyFriendData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBApplyFriendData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBApplyFriendData::GetClassData() const { return &_class_data_; }


void PBApplyFriendData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBApplyFriendData*>(&to_msg);
  auto& from = static_cast<const PBApplyFriendData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBApplyFriendData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nick_name().empty()) {
    _this->_internal_set_nick_name(from._internal_nick_name());
  }
  if (!from._internal_guild_name().empty()) {
    _this->_internal_set_guild_name(from._internal_guild_name());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (from._internal_head_id() != 0) {
    _this->_internal_set_head_id(from._internal_head_id());
  }
  if (from._internal_account_level() != 0) {
    _this->_internal_set_account_level(from._internal_account_level());
  }
  if (from._internal_head_frame() != 0) {
    _this->_internal_set_head_frame(from._internal_head_frame());
  }
  if (from._internal_title() != 0) {
    _this->_internal_set_title(from._internal_title());
  }
  if (from._internal_guild_id() != 0) {
    _this->_internal_set_guild_id(from._internal_guild_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBApplyFriendData::CopyFrom(const PBApplyFriendData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBApplyFriendData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBApplyFriendData::IsInitialized() const {
  return true;
}

void PBApplyFriendData::InternalSwap(PBApplyFriendData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.nick_name_, lhs_arena,
      &other->_impl_.nick_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.guild_name_, lhs_arena,
      &other->_impl_.guild_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBApplyFriendData, _impl_.guild_id_)
      + sizeof(PBApplyFriendData::_impl_.guild_id_)
      - PROTOBUF_FIELD_OFFSET(PBApplyFriendData, _impl_.uid_)>(
          reinterpret_cast<char*>(&_impl_.uid_),
          reinterpret_cast<char*>(&other->_impl_.uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBApplyFriendData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_friend_2eproto_getter, &descriptor_table_friend_2eproto_once,
      file_level_metadata_friend_2eproto[1]);
}

// ===================================================================

class PBGetFriendInfoReqCmd::_Internal {
 public:
};

PBGetFriendInfoReqCmd::PBGetFriendInfoReqCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBGetFriendInfoReqCmd)
}
PBGetFriendInfoReqCmd::PBGetFriendInfoReqCmd(const PBGetFriendInfoReqCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBGetFriendInfoReqCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.uid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.uid_ = from._impl_.uid_;
  // @@protoc_insertion_point(copy_constructor:PBGetFriendInfoReqCmd)
}

inline void PBGetFriendInfoReqCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.uid_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PBGetFriendInfoReqCmd::~PBGetFriendInfoReqCmd() {
  // @@protoc_insertion_point(destructor:PBGetFriendInfoReqCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBGetFriendInfoReqCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PBGetFriendInfoReqCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBGetFriendInfoReqCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PBGetFriendInfoReqCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uid_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBGetFriendInfoReqCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBGetFriendInfoReqCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBGetFriendInfoReqCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_uid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBGetFriendInfoReqCmd)
  return target;
}

size_t PBGetFriendInfoReqCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBGetFriendInfoReqCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBGetFriendInfoReqCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBGetFriendInfoReqCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBGetFriendInfoReqCmd::GetClassData() const { return &_class_data_; }


void PBGetFriendInfoReqCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBGetFriendInfoReqCmd*>(&to_msg);
  auto& from = static_cast<const PBGetFriendInfoReqCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBGetFriendInfoReqCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBGetFriendInfoReqCmd::CopyFrom(const PBGetFriendInfoReqCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBGetFriendInfoReqCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBGetFriendInfoReqCmd::IsInitialized() const {
  return true;
}

void PBGetFriendInfoReqCmd::InternalSwap(PBGetFriendInfoReqCmd* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.uid_, other->_impl_.uid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PBGetFriendInfoReqCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_friend_2eproto_getter, &descriptor_table_friend_2eproto_once,
      file_level_metadata_friend_2eproto[2]);
}

// ===================================================================

class PBGetFriendInfoRspCmd::_Internal {
 public:
};

PBGetFriendInfoRspCmd::PBGetFriendInfoRspCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBGetFriendInfoRspCmd)
}
PBGetFriendInfoRspCmd::PBGetFriendInfoRspCmd(const PBGetFriendInfoRspCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBGetFriendInfoRspCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.friend_datas_){from._impl_.friend_datas_}
    , decltype(_impl_.apply_datas_){from._impl_.apply_datas_}
    , decltype(_impl_.error_){}
    , decltype(_impl_.uid_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error().empty()) {
    _this->_impl_.error_.Set(from._internal_error(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.uid_, &from._impl_.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.code_) -
    reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.code_));
  // @@protoc_insertion_point(copy_constructor:PBGetFriendInfoRspCmd)
}

inline void PBGetFriendInfoRspCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.friend_datas_){arena}
    , decltype(_impl_.apply_datas_){arena}
    , decltype(_impl_.error_){}
    , decltype(_impl_.uid_){int64_t{0}}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PBGetFriendInfoRspCmd::~PBGetFriendInfoRspCmd() {
  // @@protoc_insertion_point(destructor:PBGetFriendInfoRspCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBGetFriendInfoRspCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.friend_datas_.~RepeatedPtrField();
  _impl_.apply_datas_.~RepeatedPtrField();
  _impl_.error_.Destroy();
}

void PBGetFriendInfoRspCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBGetFriendInfoRspCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PBGetFriendInfoRspCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.friend_datas_.Clear();
  _impl_.apply_datas_.Clear();
  _impl_.error_.ClearToEmpty();
  ::memset(&_impl_.uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.code_) -
      reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBGetFriendInfoRspCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBGetFriendInfoRspCmd.error"));
        } else
          goto handle_unusual;
        continue;
      // int64 uid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .PBFriendData friend_datas = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_friend_datas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .PBApplyFriendData apply_datas = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_apply_datas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBGetFriendInfoRspCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBGetFriendInfoRspCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_code(), target);
  }

  // string error = 2;
  if (!this->_internal_error().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error().data(), static_cast<int>(this->_internal_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBGetFriendInfoRspCmd.error");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error(), target);
  }

  // int64 uid = 3;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_uid(), target);
  }

  // repeated .PBFriendData friend_datas = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_friend_datas_size()); i < n; i++) {
    const auto& repfield = this->_internal_friend_datas(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .PBApplyFriendData apply_datas = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_apply_datas_size()); i < n; i++) {
    const auto& repfield = this->_internal_apply_datas(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBGetFriendInfoRspCmd)
  return target;
}

size_t PBGetFriendInfoRspCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBGetFriendInfoRspCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PBFriendData friend_datas = 4;
  total_size += 1UL * this->_internal_friend_datas_size();
  for (const auto& msg : this->_impl_.friend_datas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .PBApplyFriendData apply_datas = 5;
  total_size += 1UL * this->_internal_apply_datas_size();
  for (const auto& msg : this->_impl_.apply_datas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string error = 2;
  if (!this->_internal_error().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error());
  }

  // int64 uid = 3;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBGetFriendInfoRspCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBGetFriendInfoRspCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBGetFriendInfoRspCmd::GetClassData() const { return &_class_data_; }


void PBGetFriendInfoRspCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBGetFriendInfoRspCmd*>(&to_msg);
  auto& from = static_cast<const PBGetFriendInfoRspCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBGetFriendInfoRspCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.friend_datas_.MergeFrom(from._impl_.friend_datas_);
  _this->_impl_.apply_datas_.MergeFrom(from._impl_.apply_datas_);
  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBGetFriendInfoRspCmd::CopyFrom(const PBGetFriendInfoRspCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBGetFriendInfoRspCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBGetFriendInfoRspCmd::IsInitialized() const {
  return true;
}

void PBGetFriendInfoRspCmd::InternalSwap(PBGetFriendInfoRspCmd* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.friend_datas_.InternalSwap(&other->_impl_.friend_datas_);
  _impl_.apply_datas_.InternalSwap(&other->_impl_.apply_datas_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_, lhs_arena,
      &other->_impl_.error_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBGetFriendInfoRspCmd, _impl_.code_)
      + sizeof(PBGetFriendInfoRspCmd::_impl_.code_)
      - PROTOBUF_FIELD_OFFSET(PBGetFriendInfoRspCmd, _impl_.uid_)>(
          reinterpret_cast<char*>(&_impl_.uid_),
          reinterpret_cast<char*>(&other->_impl_.uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBGetFriendInfoRspCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_friend_2eproto_getter, &descriptor_table_friend_2eproto_once,
      file_level_metadata_friend_2eproto[3]);
}

// ===================================================================

class PBApplyFriendReqCmd::_Internal {
 public:
  static const ::PBApplyFriendData& apply_data(const PBApplyFriendReqCmd* msg);
};

const ::PBApplyFriendData&
PBApplyFriendReqCmd::_Internal::apply_data(const PBApplyFriendReqCmd* msg) {
  return *msg->_impl_.apply_data_;
}
PBApplyFriendReqCmd::PBApplyFriendReqCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBApplyFriendReqCmd)
}
PBApplyFriendReqCmd::PBApplyFriendReqCmd(const PBApplyFriendReqCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBApplyFriendReqCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.apply_data_){nullptr}
    , decltype(_impl_.uid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_apply_data()) {
    _this->_impl_.apply_data_ = new ::PBApplyFriendData(*from._impl_.apply_data_);
  }
  _this->_impl_.uid_ = from._impl_.uid_;
  // @@protoc_insertion_point(copy_constructor:PBApplyFriendReqCmd)
}

inline void PBApplyFriendReqCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.apply_data_){nullptr}
    , decltype(_impl_.uid_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PBApplyFriendReqCmd::~PBApplyFriendReqCmd() {
  // @@protoc_insertion_point(destructor:PBApplyFriendReqCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBApplyFriendReqCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.apply_data_;
}

void PBApplyFriendReqCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBApplyFriendReqCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PBApplyFriendReqCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.apply_data_ != nullptr) {
    delete _impl_.apply_data_;
  }
  _impl_.apply_data_ = nullptr;
  _impl_.uid_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBApplyFriendReqCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PBApplyFriendData apply_data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_apply_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBApplyFriendReqCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBApplyFriendReqCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_uid(), target);
  }

  // .PBApplyFriendData apply_data = 2;
  if (this->_internal_has_apply_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::apply_data(this),
        _Internal::apply_data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBApplyFriendReqCmd)
  return target;
}

size_t PBApplyFriendReqCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBApplyFriendReqCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .PBApplyFriendData apply_data = 2;
  if (this->_internal_has_apply_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.apply_data_);
  }

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBApplyFriendReqCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBApplyFriendReqCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBApplyFriendReqCmd::GetClassData() const { return &_class_data_; }


void PBApplyFriendReqCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBApplyFriendReqCmd*>(&to_msg);
  auto& from = static_cast<const PBApplyFriendReqCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBApplyFriendReqCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_apply_data()) {
    _this->_internal_mutable_apply_data()->::PBApplyFriendData::MergeFrom(
        from._internal_apply_data());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBApplyFriendReqCmd::CopyFrom(const PBApplyFriendReqCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBApplyFriendReqCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBApplyFriendReqCmd::IsInitialized() const {
  return true;
}

void PBApplyFriendReqCmd::InternalSwap(PBApplyFriendReqCmd* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBApplyFriendReqCmd, _impl_.uid_)
      + sizeof(PBApplyFriendReqCmd::_impl_.uid_)
      - PROTOBUF_FIELD_OFFSET(PBApplyFriendReqCmd, _impl_.apply_data_)>(
          reinterpret_cast<char*>(&_impl_.apply_data_),
          reinterpret_cast<char*>(&other->_impl_.apply_data_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBApplyFriendReqCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_friend_2eproto_getter, &descriptor_table_friend_2eproto_once,
      file_level_metadata_friend_2eproto[4]);
}

// ===================================================================

class PBApplyFriendRspCmd::_Internal {
 public:
};

PBApplyFriendRspCmd::PBApplyFriendRspCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBApplyFriendRspCmd)
}
PBApplyFriendRspCmd::PBApplyFriendRspCmd(const PBApplyFriendRspCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBApplyFriendRspCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.uid_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error().empty()) {
    _this->_impl_.error_.Set(from._internal_error(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.uid_, &from._impl_.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.code_) -
    reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.code_));
  // @@protoc_insertion_point(copy_constructor:PBApplyFriendRspCmd)
}

inline void PBApplyFriendRspCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.uid_){int64_t{0}}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PBApplyFriendRspCmd::~PBApplyFriendRspCmd() {
  // @@protoc_insertion_point(destructor:PBApplyFriendRspCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBApplyFriendRspCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_.Destroy();
}

void PBApplyFriendRspCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBApplyFriendRspCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PBApplyFriendRspCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_.ClearToEmpty();
  ::memset(&_impl_.uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.code_) -
      reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBApplyFriendRspCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBApplyFriendRspCmd.error"));
        } else
          goto handle_unusual;
        continue;
      // int64 uid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBApplyFriendRspCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBApplyFriendRspCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_code(), target);
  }

  // string error = 2;
  if (!this->_internal_error().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error().data(), static_cast<int>(this->_internal_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBApplyFriendRspCmd.error");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error(), target);
  }

  // int64 uid = 3;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_uid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBApplyFriendRspCmd)
  return target;
}

size_t PBApplyFriendRspCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBApplyFriendRspCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error = 2;
  if (!this->_internal_error().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error());
  }

  // int64 uid = 3;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBApplyFriendRspCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBApplyFriendRspCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBApplyFriendRspCmd::GetClassData() const { return &_class_data_; }


void PBApplyFriendRspCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBApplyFriendRspCmd*>(&to_msg);
  auto& from = static_cast<const PBApplyFriendRspCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBApplyFriendRspCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBApplyFriendRspCmd::CopyFrom(const PBApplyFriendRspCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBApplyFriendRspCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBApplyFriendRspCmd::IsInitialized() const {
  return true;
}

void PBApplyFriendRspCmd::InternalSwap(PBApplyFriendRspCmd* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_, lhs_arena,
      &other->_impl_.error_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBApplyFriendRspCmd, _impl_.code_)
      + sizeof(PBApplyFriendRspCmd::_impl_.code_)
      - PROTOBUF_FIELD_OFFSET(PBApplyFriendRspCmd, _impl_.uid_)>(
          reinterpret_cast<char*>(&_impl_.uid_),
          reinterpret_cast<char*>(&other->_impl_.uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBApplyFriendRspCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_friend_2eproto_getter, &descriptor_table_friend_2eproto_once,
      file_level_metadata_friend_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PBFriendData*
Arena::CreateMaybeMessage< ::PBFriendData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBFriendData >(arena);
}
template<> PROTOBUF_NOINLINE ::PBApplyFriendData*
Arena::CreateMaybeMessage< ::PBApplyFriendData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBApplyFriendData >(arena);
}
template<> PROTOBUF_NOINLINE ::PBGetFriendInfoReqCmd*
Arena::CreateMaybeMessage< ::PBGetFriendInfoReqCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBGetFriendInfoReqCmd >(arena);
}
template<> PROTOBUF_NOINLINE ::PBGetFriendInfoRspCmd*
Arena::CreateMaybeMessage< ::PBGetFriendInfoRspCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBGetFriendInfoRspCmd >(arena);
}
template<> PROTOBUF_NOINLINE ::PBApplyFriendReqCmd*
Arena::CreateMaybeMessage< ::PBApplyFriendReqCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBApplyFriendReqCmd >(arena);
}
template<> PROTOBUF_NOINLINE ::PBApplyFriendRspCmd*
Arena::CreateMaybeMessage< ::PBApplyFriendRspCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBApplyFriendRspCmd >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
