// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_friend_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_friend_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_friend_2eproto COMMONNETUE_API
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct COMMONNETUE_API TableStruct_friend_2eproto {
  static const uint32_t offsets[];
};
COMMONNETUE_API extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_friend_2eproto;
class PBApplyFriendData;
struct PBApplyFriendDataDefaultTypeInternal;
COMMONNETUE_API extern PBApplyFriendDataDefaultTypeInternal _PBApplyFriendData_default_instance_;
class PBApplyFriendReqCmd;
struct PBApplyFriendReqCmdDefaultTypeInternal;
COMMONNETUE_API extern PBApplyFriendReqCmdDefaultTypeInternal _PBApplyFriendReqCmd_default_instance_;
class PBApplyFriendRspCmd;
struct PBApplyFriendRspCmdDefaultTypeInternal;
COMMONNETUE_API extern PBApplyFriendRspCmdDefaultTypeInternal _PBApplyFriendRspCmd_default_instance_;
class PBFriendData;
struct PBFriendDataDefaultTypeInternal;
COMMONNETUE_API extern PBFriendDataDefaultTypeInternal _PBFriendData_default_instance_;
class PBGetFriendInfoReqCmd;
struct PBGetFriendInfoReqCmdDefaultTypeInternal;
COMMONNETUE_API extern PBGetFriendInfoReqCmdDefaultTypeInternal _PBGetFriendInfoReqCmd_default_instance_;
class PBGetFriendInfoRspCmd;
struct PBGetFriendInfoRspCmdDefaultTypeInternal;
COMMONNETUE_API extern PBGetFriendInfoRspCmdDefaultTypeInternal _PBGetFriendInfoRspCmd_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> COMMONNETUE_API ::PBApplyFriendData* Arena::CreateMaybeMessage<::PBApplyFriendData>(Arena*);
template<> COMMONNETUE_API ::PBApplyFriendReqCmd* Arena::CreateMaybeMessage<::PBApplyFriendReqCmd>(Arena*);
template<> COMMONNETUE_API ::PBApplyFriendRspCmd* Arena::CreateMaybeMessage<::PBApplyFriendRspCmd>(Arena*);
template<> COMMONNETUE_API ::PBFriendData* Arena::CreateMaybeMessage<::PBFriendData>(Arena*);
template<> COMMONNETUE_API ::PBGetFriendInfoReqCmd* Arena::CreateMaybeMessage<::PBGetFriendInfoReqCmd>(Arena*);
template<> COMMONNETUE_API ::PBGetFriendInfoRspCmd* Arena::CreateMaybeMessage<::PBGetFriendInfoRspCmd>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class COMMONNETUE_API PBFriendData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBFriendData) */ {
 public:
  inline PBFriendData() : PBFriendData(nullptr) {}
  ~PBFriendData() override;
  explicit PROTOBUF_CONSTEXPR PBFriendData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBFriendData(const PBFriendData& from);
  PBFriendData(PBFriendData&& from) noexcept
    : PBFriendData() {
    *this = ::std::move(from);
  }

  inline PBFriendData& operator=(const PBFriendData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBFriendData& operator=(PBFriendData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBFriendData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBFriendData* internal_default_instance() {
    return reinterpret_cast<const PBFriendData*>(
               &_PBFriendData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PBFriendData& a, PBFriendData& b) {
    a.Swap(&b);
  }
  inline void Swap(PBFriendData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBFriendData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBFriendData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBFriendData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBFriendData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBFriendData& from) {
    PBFriendData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBFriendData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBFriendData";
  }
  protected:
  explicit PBFriendData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNickNameFieldNumber = 3,
    kGuildNameFieldNumber = 11,
    kNameRemarkFieldNumber = 12,
    kUidFieldNumber = 1,
    kHeadIdFieldNumber = 2,
    kAccountLevelFieldNumber = 4,
    kOnlineStateFieldNumber = 5,
    kGroupIdFieldNumber = 6,
    kFriendTimeFieldNumber = 7,
    kHeadFrameFieldNumber = 8,
    kTitleFieldNumber = 9,
    kGuildIdFieldNumber = 10,
  };
  // string nick_name = 3;
  void clear_nick_name();
  const std::string& nick_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nick_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nick_name();
  PROTOBUF_NODISCARD std::string* release_nick_name();
  void set_allocated_nick_name(std::string* nick_name);
  private:
  const std::string& _internal_nick_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nick_name(const std::string& value);
  std::string* _internal_mutable_nick_name();
  public:

  // string guild_name = 11;
  void clear_guild_name();
  const std::string& guild_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_guild_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_guild_name();
  PROTOBUF_NODISCARD std::string* release_guild_name();
  void set_allocated_guild_name(std::string* guild_name);
  private:
  const std::string& _internal_guild_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_guild_name(const std::string& value);
  std::string* _internal_mutable_guild_name();
  public:

  // string name_remark = 12;
  void clear_name_remark();
  const std::string& name_remark() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name_remark(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name_remark();
  PROTOBUF_NODISCARD std::string* release_name_remark();
  void set_allocated_name_remark(std::string* name_remark);
  private:
  const std::string& _internal_name_remark() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name_remark(const std::string& value);
  std::string* _internal_mutable_name_remark();
  public:

  // int64 uid = 1;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // int32 head_id = 2;
  void clear_head_id();
  int32_t head_id() const;
  void set_head_id(int32_t value);
  private:
  int32_t _internal_head_id() const;
  void _internal_set_head_id(int32_t value);
  public:

  // int32 account_level = 4;
  void clear_account_level();
  int32_t account_level() const;
  void set_account_level(int32_t value);
  private:
  int32_t _internal_account_level() const;
  void _internal_set_account_level(int32_t value);
  public:

  // int32 online_state = 5;
  void clear_online_state();
  int32_t online_state() const;
  void set_online_state(int32_t value);
  private:
  int32_t _internal_online_state() const;
  void _internal_set_online_state(int32_t value);
  public:

  // int32 group_id = 6;
  void clear_group_id();
  int32_t group_id() const;
  void set_group_id(int32_t value);
  private:
  int32_t _internal_group_id() const;
  void _internal_set_group_id(int32_t value);
  public:

  // int64 friend_time = 7;
  void clear_friend_time();
  int64_t friend_time() const;
  void set_friend_time(int64_t value);
  private:
  int64_t _internal_friend_time() const;
  void _internal_set_friend_time(int64_t value);
  public:

  // int32 head_frame = 8;
  void clear_head_frame();
  int32_t head_frame() const;
  void set_head_frame(int32_t value);
  private:
  int32_t _internal_head_frame() const;
  void _internal_set_head_frame(int32_t value);
  public:

  // int32 title = 9;
  void clear_title();
  int32_t title() const;
  void set_title(int32_t value);
  private:
  int32_t _internal_title() const;
  void _internal_set_title(int32_t value);
  public:

  // int32 guild_id = 10;
  void clear_guild_id();
  int32_t guild_id() const;
  void set_guild_id(int32_t value);
  private:
  int32_t _internal_guild_id() const;
  void _internal_set_guild_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBFriendData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nick_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr guild_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_remark_;
    int64_t uid_;
    int32_t head_id_;
    int32_t account_level_;
    int32_t online_state_;
    int32_t group_id_;
    int64_t friend_time_;
    int32_t head_frame_;
    int32_t title_;
    int32_t guild_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_friend_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBApplyFriendData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBApplyFriendData) */ {
 public:
  inline PBApplyFriendData() : PBApplyFriendData(nullptr) {}
  ~PBApplyFriendData() override;
  explicit PROTOBUF_CONSTEXPR PBApplyFriendData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBApplyFriendData(const PBApplyFriendData& from);
  PBApplyFriendData(PBApplyFriendData&& from) noexcept
    : PBApplyFriendData() {
    *this = ::std::move(from);
  }

  inline PBApplyFriendData& operator=(const PBApplyFriendData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBApplyFriendData& operator=(PBApplyFriendData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBApplyFriendData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBApplyFriendData* internal_default_instance() {
    return reinterpret_cast<const PBApplyFriendData*>(
               &_PBApplyFriendData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PBApplyFriendData& a, PBApplyFriendData& b) {
    a.Swap(&b);
  }
  inline void Swap(PBApplyFriendData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBApplyFriendData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBApplyFriendData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBApplyFriendData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBApplyFriendData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBApplyFriendData& from) {
    PBApplyFriendData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBApplyFriendData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBApplyFriendData";
  }
  protected:
  explicit PBApplyFriendData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNickNameFieldNumber = 3,
    kGuildNameFieldNumber = 8,
    kUidFieldNumber = 1,
    kHeadIdFieldNumber = 2,
    kAccountLevelFieldNumber = 4,
    kHeadFrameFieldNumber = 5,
    kTitleFieldNumber = 6,
    kGuildIdFieldNumber = 7,
  };
  // string nick_name = 3;
  void clear_nick_name();
  const std::string& nick_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nick_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nick_name();
  PROTOBUF_NODISCARD std::string* release_nick_name();
  void set_allocated_nick_name(std::string* nick_name);
  private:
  const std::string& _internal_nick_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nick_name(const std::string& value);
  std::string* _internal_mutable_nick_name();
  public:

  // string guild_name = 8;
  void clear_guild_name();
  const std::string& guild_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_guild_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_guild_name();
  PROTOBUF_NODISCARD std::string* release_guild_name();
  void set_allocated_guild_name(std::string* guild_name);
  private:
  const std::string& _internal_guild_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_guild_name(const std::string& value);
  std::string* _internal_mutable_guild_name();
  public:

  // int64 uid = 1;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // int32 head_id = 2;
  void clear_head_id();
  int32_t head_id() const;
  void set_head_id(int32_t value);
  private:
  int32_t _internal_head_id() const;
  void _internal_set_head_id(int32_t value);
  public:

  // int32 account_level = 4;
  void clear_account_level();
  int32_t account_level() const;
  void set_account_level(int32_t value);
  private:
  int32_t _internal_account_level() const;
  void _internal_set_account_level(int32_t value);
  public:

  // int32 head_frame = 5;
  void clear_head_frame();
  int32_t head_frame() const;
  void set_head_frame(int32_t value);
  private:
  int32_t _internal_head_frame() const;
  void _internal_set_head_frame(int32_t value);
  public:

  // int32 title = 6;
  void clear_title();
  int32_t title() const;
  void set_title(int32_t value);
  private:
  int32_t _internal_title() const;
  void _internal_set_title(int32_t value);
  public:

  // int32 guild_id = 7;
  void clear_guild_id();
  int32_t guild_id() const;
  void set_guild_id(int32_t value);
  private:
  int32_t _internal_guild_id() const;
  void _internal_set_guild_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBApplyFriendData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nick_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr guild_name_;
    int64_t uid_;
    int32_t head_id_;
    int32_t account_level_;
    int32_t head_frame_;
    int32_t title_;
    int32_t guild_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_friend_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBGetFriendInfoReqCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBGetFriendInfoReqCmd) */ {
 public:
  inline PBGetFriendInfoReqCmd() : PBGetFriendInfoReqCmd(nullptr) {}
  ~PBGetFriendInfoReqCmd() override;
  explicit PROTOBUF_CONSTEXPR PBGetFriendInfoReqCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBGetFriendInfoReqCmd(const PBGetFriendInfoReqCmd& from);
  PBGetFriendInfoReqCmd(PBGetFriendInfoReqCmd&& from) noexcept
    : PBGetFriendInfoReqCmd() {
    *this = ::std::move(from);
  }

  inline PBGetFriendInfoReqCmd& operator=(const PBGetFriendInfoReqCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBGetFriendInfoReqCmd& operator=(PBGetFriendInfoReqCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBGetFriendInfoReqCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBGetFriendInfoReqCmd* internal_default_instance() {
    return reinterpret_cast<const PBGetFriendInfoReqCmd*>(
               &_PBGetFriendInfoReqCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PBGetFriendInfoReqCmd& a, PBGetFriendInfoReqCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(PBGetFriendInfoReqCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBGetFriendInfoReqCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBGetFriendInfoReqCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBGetFriendInfoReqCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBGetFriendInfoReqCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBGetFriendInfoReqCmd& from) {
    PBGetFriendInfoReqCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBGetFriendInfoReqCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBGetFriendInfoReqCmd";
  }
  protected:
  explicit PBGetFriendInfoReqCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUidFieldNumber = 1,
  };
  // int64 uid = 1;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBGetFriendInfoReqCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t uid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_friend_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBGetFriendInfoRspCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBGetFriendInfoRspCmd) */ {
 public:
  inline PBGetFriendInfoRspCmd() : PBGetFriendInfoRspCmd(nullptr) {}
  ~PBGetFriendInfoRspCmd() override;
  explicit PROTOBUF_CONSTEXPR PBGetFriendInfoRspCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBGetFriendInfoRspCmd(const PBGetFriendInfoRspCmd& from);
  PBGetFriendInfoRspCmd(PBGetFriendInfoRspCmd&& from) noexcept
    : PBGetFriendInfoRspCmd() {
    *this = ::std::move(from);
  }

  inline PBGetFriendInfoRspCmd& operator=(const PBGetFriendInfoRspCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBGetFriendInfoRspCmd& operator=(PBGetFriendInfoRspCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBGetFriendInfoRspCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBGetFriendInfoRspCmd* internal_default_instance() {
    return reinterpret_cast<const PBGetFriendInfoRspCmd*>(
               &_PBGetFriendInfoRspCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PBGetFriendInfoRspCmd& a, PBGetFriendInfoRspCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(PBGetFriendInfoRspCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBGetFriendInfoRspCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBGetFriendInfoRspCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBGetFriendInfoRspCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBGetFriendInfoRspCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBGetFriendInfoRspCmd& from) {
    PBGetFriendInfoRspCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBGetFriendInfoRspCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBGetFriendInfoRspCmd";
  }
  protected:
  explicit PBGetFriendInfoRspCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFriendDatasFieldNumber = 4,
    kApplyDatasFieldNumber = 5,
    kErrorFieldNumber = 2,
    kUidFieldNumber = 3,
    kCodeFieldNumber = 1,
  };
  // repeated .PBFriendData friend_datas = 4;
  int friend_datas_size() const;
  private:
  int _internal_friend_datas_size() const;
  public:
  void clear_friend_datas();
  ::PBFriendData* mutable_friend_datas(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBFriendData >*
      mutable_friend_datas();
  private:
  const ::PBFriendData& _internal_friend_datas(int index) const;
  ::PBFriendData* _internal_add_friend_datas();
  public:
  const ::PBFriendData& friend_datas(int index) const;
  ::PBFriendData* add_friend_datas();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBFriendData >&
      friend_datas() const;

  // repeated .PBApplyFriendData apply_datas = 5;
  int apply_datas_size() const;
  private:
  int _internal_apply_datas_size() const;
  public:
  void clear_apply_datas();
  ::PBApplyFriendData* mutable_apply_datas(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBApplyFriendData >*
      mutable_apply_datas();
  private:
  const ::PBApplyFriendData& _internal_apply_datas(int index) const;
  ::PBApplyFriendData* _internal_add_apply_datas();
  public:
  const ::PBApplyFriendData& apply_datas(int index) const;
  ::PBApplyFriendData* add_apply_datas();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBApplyFriendData >&
      apply_datas() const;

  // string error = 2;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // int64 uid = 3;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // int32 code = 1;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBGetFriendInfoRspCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBFriendData > friend_datas_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBApplyFriendData > apply_datas_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    int64_t uid_;
    int32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_friend_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBApplyFriendReqCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBApplyFriendReqCmd) */ {
 public:
  inline PBApplyFriendReqCmd() : PBApplyFriendReqCmd(nullptr) {}
  ~PBApplyFriendReqCmd() override;
  explicit PROTOBUF_CONSTEXPR PBApplyFriendReqCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBApplyFriendReqCmd(const PBApplyFriendReqCmd& from);
  PBApplyFriendReqCmd(PBApplyFriendReqCmd&& from) noexcept
    : PBApplyFriendReqCmd() {
    *this = ::std::move(from);
  }

  inline PBApplyFriendReqCmd& operator=(const PBApplyFriendReqCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBApplyFriendReqCmd& operator=(PBApplyFriendReqCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBApplyFriendReqCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBApplyFriendReqCmd* internal_default_instance() {
    return reinterpret_cast<const PBApplyFriendReqCmd*>(
               &_PBApplyFriendReqCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PBApplyFriendReqCmd& a, PBApplyFriendReqCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(PBApplyFriendReqCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBApplyFriendReqCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBApplyFriendReqCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBApplyFriendReqCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBApplyFriendReqCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBApplyFriendReqCmd& from) {
    PBApplyFriendReqCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBApplyFriendReqCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBApplyFriendReqCmd";
  }
  protected:
  explicit PBApplyFriendReqCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApplyDataFieldNumber = 2,
    kUidFieldNumber = 1,
  };
  // .PBApplyFriendData apply_data = 2;
  bool has_apply_data() const;
  private:
  bool _internal_has_apply_data() const;
  public:
  void clear_apply_data();
  const ::PBApplyFriendData& apply_data() const;
  PROTOBUF_NODISCARD ::PBApplyFriendData* release_apply_data();
  ::PBApplyFriendData* mutable_apply_data();
  void set_allocated_apply_data(::PBApplyFriendData* apply_data);
  private:
  const ::PBApplyFriendData& _internal_apply_data() const;
  ::PBApplyFriendData* _internal_mutable_apply_data();
  public:
  void unsafe_arena_set_allocated_apply_data(
      ::PBApplyFriendData* apply_data);
  ::PBApplyFriendData* unsafe_arena_release_apply_data();

  // int64 uid = 1;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBApplyFriendReqCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PBApplyFriendData* apply_data_;
    int64_t uid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_friend_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBApplyFriendRspCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBApplyFriendRspCmd) */ {
 public:
  inline PBApplyFriendRspCmd() : PBApplyFriendRspCmd(nullptr) {}
  ~PBApplyFriendRspCmd() override;
  explicit PROTOBUF_CONSTEXPR PBApplyFriendRspCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBApplyFriendRspCmd(const PBApplyFriendRspCmd& from);
  PBApplyFriendRspCmd(PBApplyFriendRspCmd&& from) noexcept
    : PBApplyFriendRspCmd() {
    *this = ::std::move(from);
  }

  inline PBApplyFriendRspCmd& operator=(const PBApplyFriendRspCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBApplyFriendRspCmd& operator=(PBApplyFriendRspCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBApplyFriendRspCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBApplyFriendRspCmd* internal_default_instance() {
    return reinterpret_cast<const PBApplyFriendRspCmd*>(
               &_PBApplyFriendRspCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PBApplyFriendRspCmd& a, PBApplyFriendRspCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(PBApplyFriendRspCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBApplyFriendRspCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBApplyFriendRspCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBApplyFriendRspCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBApplyFriendRspCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBApplyFriendRspCmd& from) {
    PBApplyFriendRspCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBApplyFriendRspCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBApplyFriendRspCmd";
  }
  protected:
  explicit PBApplyFriendRspCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 2,
    kUidFieldNumber = 3,
    kCodeFieldNumber = 1,
  };
  // string error = 2;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // int64 uid = 3;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // int32 code = 1;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBApplyFriendRspCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    int64_t uid_;
    int32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_friend_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PBFriendData

// int64 uid = 1;
inline void PBFriendData::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBFriendData::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBFriendData::uid() const {
  // @@protoc_insertion_point(field_get:PBFriendData.uid)
  return _internal_uid();
}
inline void PBFriendData::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBFriendData::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBFriendData.uid)
}

// int32 head_id = 2;
inline void PBFriendData::clear_head_id() {
  _impl_.head_id_ = 0;
}
inline int32_t PBFriendData::_internal_head_id() const {
  return _impl_.head_id_;
}
inline int32_t PBFriendData::head_id() const {
  // @@protoc_insertion_point(field_get:PBFriendData.head_id)
  return _internal_head_id();
}
inline void PBFriendData::_internal_set_head_id(int32_t value) {
  
  _impl_.head_id_ = value;
}
inline void PBFriendData::set_head_id(int32_t value) {
  _internal_set_head_id(value);
  // @@protoc_insertion_point(field_set:PBFriendData.head_id)
}

// string nick_name = 3;
inline void PBFriendData::clear_nick_name() {
  _impl_.nick_name_.ClearToEmpty();
}
inline const std::string& PBFriendData::nick_name() const {
  // @@protoc_insertion_point(field_get:PBFriendData.nick_name)
  return _internal_nick_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBFriendData::set_nick_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nick_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBFriendData.nick_name)
}
inline std::string* PBFriendData::mutable_nick_name() {
  std::string* _s = _internal_mutable_nick_name();
  // @@protoc_insertion_point(field_mutable:PBFriendData.nick_name)
  return _s;
}
inline const std::string& PBFriendData::_internal_nick_name() const {
  return _impl_.nick_name_.Get();
}
inline void PBFriendData::_internal_set_nick_name(const std::string& value) {
  
  _impl_.nick_name_.Set(value, GetArenaForAllocation());
}
inline std::string* PBFriendData::_internal_mutable_nick_name() {
  
  return _impl_.nick_name_.Mutable(GetArenaForAllocation());
}
inline std::string* PBFriendData::release_nick_name() {
  // @@protoc_insertion_point(field_release:PBFriendData.nick_name)
  return _impl_.nick_name_.Release();
}
inline void PBFriendData::set_allocated_nick_name(std::string* nick_name) {
  if (nick_name != nullptr) {
    
  } else {
    
  }
  _impl_.nick_name_.SetAllocated(nick_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nick_name_.IsDefault()) {
    _impl_.nick_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBFriendData.nick_name)
}

// int32 account_level = 4;
inline void PBFriendData::clear_account_level() {
  _impl_.account_level_ = 0;
}
inline int32_t PBFriendData::_internal_account_level() const {
  return _impl_.account_level_;
}
inline int32_t PBFriendData::account_level() const {
  // @@protoc_insertion_point(field_get:PBFriendData.account_level)
  return _internal_account_level();
}
inline void PBFriendData::_internal_set_account_level(int32_t value) {
  
  _impl_.account_level_ = value;
}
inline void PBFriendData::set_account_level(int32_t value) {
  _internal_set_account_level(value);
  // @@protoc_insertion_point(field_set:PBFriendData.account_level)
}

// int32 online_state = 5;
inline void PBFriendData::clear_online_state() {
  _impl_.online_state_ = 0;
}
inline int32_t PBFriendData::_internal_online_state() const {
  return _impl_.online_state_;
}
inline int32_t PBFriendData::online_state() const {
  // @@protoc_insertion_point(field_get:PBFriendData.online_state)
  return _internal_online_state();
}
inline void PBFriendData::_internal_set_online_state(int32_t value) {
  
  _impl_.online_state_ = value;
}
inline void PBFriendData::set_online_state(int32_t value) {
  _internal_set_online_state(value);
  // @@protoc_insertion_point(field_set:PBFriendData.online_state)
}

// int32 group_id = 6;
inline void PBFriendData::clear_group_id() {
  _impl_.group_id_ = 0;
}
inline int32_t PBFriendData::_internal_group_id() const {
  return _impl_.group_id_;
}
inline int32_t PBFriendData::group_id() const {
  // @@protoc_insertion_point(field_get:PBFriendData.group_id)
  return _internal_group_id();
}
inline void PBFriendData::_internal_set_group_id(int32_t value) {
  
  _impl_.group_id_ = value;
}
inline void PBFriendData::set_group_id(int32_t value) {
  _internal_set_group_id(value);
  // @@protoc_insertion_point(field_set:PBFriendData.group_id)
}

// int64 friend_time = 7;
inline void PBFriendData::clear_friend_time() {
  _impl_.friend_time_ = int64_t{0};
}
inline int64_t PBFriendData::_internal_friend_time() const {
  return _impl_.friend_time_;
}
inline int64_t PBFriendData::friend_time() const {
  // @@protoc_insertion_point(field_get:PBFriendData.friend_time)
  return _internal_friend_time();
}
inline void PBFriendData::_internal_set_friend_time(int64_t value) {
  
  _impl_.friend_time_ = value;
}
inline void PBFriendData::set_friend_time(int64_t value) {
  _internal_set_friend_time(value);
  // @@protoc_insertion_point(field_set:PBFriendData.friend_time)
}

// int32 head_frame = 8;
inline void PBFriendData::clear_head_frame() {
  _impl_.head_frame_ = 0;
}
inline int32_t PBFriendData::_internal_head_frame() const {
  return _impl_.head_frame_;
}
inline int32_t PBFriendData::head_frame() const {
  // @@protoc_insertion_point(field_get:PBFriendData.head_frame)
  return _internal_head_frame();
}
inline void PBFriendData::_internal_set_head_frame(int32_t value) {
  
  _impl_.head_frame_ = value;
}
inline void PBFriendData::set_head_frame(int32_t value) {
  _internal_set_head_frame(value);
  // @@protoc_insertion_point(field_set:PBFriendData.head_frame)
}

// int32 title = 9;
inline void PBFriendData::clear_title() {
  _impl_.title_ = 0;
}
inline int32_t PBFriendData::_internal_title() const {
  return _impl_.title_;
}
inline int32_t PBFriendData::title() const {
  // @@protoc_insertion_point(field_get:PBFriendData.title)
  return _internal_title();
}
inline void PBFriendData::_internal_set_title(int32_t value) {
  
  _impl_.title_ = value;
}
inline void PBFriendData::set_title(int32_t value) {
  _internal_set_title(value);
  // @@protoc_insertion_point(field_set:PBFriendData.title)
}

// int32 guild_id = 10;
inline void PBFriendData::clear_guild_id() {
  _impl_.guild_id_ = 0;
}
inline int32_t PBFriendData::_internal_guild_id() const {
  return _impl_.guild_id_;
}
inline int32_t PBFriendData::guild_id() const {
  // @@protoc_insertion_point(field_get:PBFriendData.guild_id)
  return _internal_guild_id();
}
inline void PBFriendData::_internal_set_guild_id(int32_t value) {
  
  _impl_.guild_id_ = value;
}
inline void PBFriendData::set_guild_id(int32_t value) {
  _internal_set_guild_id(value);
  // @@protoc_insertion_point(field_set:PBFriendData.guild_id)
}

// string guild_name = 11;
inline void PBFriendData::clear_guild_name() {
  _impl_.guild_name_.ClearToEmpty();
}
inline const std::string& PBFriendData::guild_name() const {
  // @@protoc_insertion_point(field_get:PBFriendData.guild_name)
  return _internal_guild_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBFriendData::set_guild_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.guild_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBFriendData.guild_name)
}
inline std::string* PBFriendData::mutable_guild_name() {
  std::string* _s = _internal_mutable_guild_name();
  // @@protoc_insertion_point(field_mutable:PBFriendData.guild_name)
  return _s;
}
inline const std::string& PBFriendData::_internal_guild_name() const {
  return _impl_.guild_name_.Get();
}
inline void PBFriendData::_internal_set_guild_name(const std::string& value) {
  
  _impl_.guild_name_.Set(value, GetArenaForAllocation());
}
inline std::string* PBFriendData::_internal_mutable_guild_name() {
  
  return _impl_.guild_name_.Mutable(GetArenaForAllocation());
}
inline std::string* PBFriendData::release_guild_name() {
  // @@protoc_insertion_point(field_release:PBFriendData.guild_name)
  return _impl_.guild_name_.Release();
}
inline void PBFriendData::set_allocated_guild_name(std::string* guild_name) {
  if (guild_name != nullptr) {
    
  } else {
    
  }
  _impl_.guild_name_.SetAllocated(guild_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.guild_name_.IsDefault()) {
    _impl_.guild_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBFriendData.guild_name)
}

// string name_remark = 12;
inline void PBFriendData::clear_name_remark() {
  _impl_.name_remark_.ClearToEmpty();
}
inline const std::string& PBFriendData::name_remark() const {
  // @@protoc_insertion_point(field_get:PBFriendData.name_remark)
  return _internal_name_remark();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBFriendData::set_name_remark(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_remark_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBFriendData.name_remark)
}
inline std::string* PBFriendData::mutable_name_remark() {
  std::string* _s = _internal_mutable_name_remark();
  // @@protoc_insertion_point(field_mutable:PBFriendData.name_remark)
  return _s;
}
inline const std::string& PBFriendData::_internal_name_remark() const {
  return _impl_.name_remark_.Get();
}
inline void PBFriendData::_internal_set_name_remark(const std::string& value) {
  
  _impl_.name_remark_.Set(value, GetArenaForAllocation());
}
inline std::string* PBFriendData::_internal_mutable_name_remark() {
  
  return _impl_.name_remark_.Mutable(GetArenaForAllocation());
}
inline std::string* PBFriendData::release_name_remark() {
  // @@protoc_insertion_point(field_release:PBFriendData.name_remark)
  return _impl_.name_remark_.Release();
}
inline void PBFriendData::set_allocated_name_remark(std::string* name_remark) {
  if (name_remark != nullptr) {
    
  } else {
    
  }
  _impl_.name_remark_.SetAllocated(name_remark, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_remark_.IsDefault()) {
    _impl_.name_remark_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBFriendData.name_remark)
}

// -------------------------------------------------------------------

// PBApplyFriendData

// int64 uid = 1;
inline void PBApplyFriendData::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBApplyFriendData::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBApplyFriendData::uid() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendData.uid)
  return _internal_uid();
}
inline void PBApplyFriendData::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBApplyFriendData::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBApplyFriendData.uid)
}

// int32 head_id = 2;
inline void PBApplyFriendData::clear_head_id() {
  _impl_.head_id_ = 0;
}
inline int32_t PBApplyFriendData::_internal_head_id() const {
  return _impl_.head_id_;
}
inline int32_t PBApplyFriendData::head_id() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendData.head_id)
  return _internal_head_id();
}
inline void PBApplyFriendData::_internal_set_head_id(int32_t value) {
  
  _impl_.head_id_ = value;
}
inline void PBApplyFriendData::set_head_id(int32_t value) {
  _internal_set_head_id(value);
  // @@protoc_insertion_point(field_set:PBApplyFriendData.head_id)
}

// string nick_name = 3;
inline void PBApplyFriendData::clear_nick_name() {
  _impl_.nick_name_.ClearToEmpty();
}
inline const std::string& PBApplyFriendData::nick_name() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendData.nick_name)
  return _internal_nick_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBApplyFriendData::set_nick_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nick_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBApplyFriendData.nick_name)
}
inline std::string* PBApplyFriendData::mutable_nick_name() {
  std::string* _s = _internal_mutable_nick_name();
  // @@protoc_insertion_point(field_mutable:PBApplyFriendData.nick_name)
  return _s;
}
inline const std::string& PBApplyFriendData::_internal_nick_name() const {
  return _impl_.nick_name_.Get();
}
inline void PBApplyFriendData::_internal_set_nick_name(const std::string& value) {
  
  _impl_.nick_name_.Set(value, GetArenaForAllocation());
}
inline std::string* PBApplyFriendData::_internal_mutable_nick_name() {
  
  return _impl_.nick_name_.Mutable(GetArenaForAllocation());
}
inline std::string* PBApplyFriendData::release_nick_name() {
  // @@protoc_insertion_point(field_release:PBApplyFriendData.nick_name)
  return _impl_.nick_name_.Release();
}
inline void PBApplyFriendData::set_allocated_nick_name(std::string* nick_name) {
  if (nick_name != nullptr) {
    
  } else {
    
  }
  _impl_.nick_name_.SetAllocated(nick_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nick_name_.IsDefault()) {
    _impl_.nick_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBApplyFriendData.nick_name)
}

// int32 account_level = 4;
inline void PBApplyFriendData::clear_account_level() {
  _impl_.account_level_ = 0;
}
inline int32_t PBApplyFriendData::_internal_account_level() const {
  return _impl_.account_level_;
}
inline int32_t PBApplyFriendData::account_level() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendData.account_level)
  return _internal_account_level();
}
inline void PBApplyFriendData::_internal_set_account_level(int32_t value) {
  
  _impl_.account_level_ = value;
}
inline void PBApplyFriendData::set_account_level(int32_t value) {
  _internal_set_account_level(value);
  // @@protoc_insertion_point(field_set:PBApplyFriendData.account_level)
}

// int32 head_frame = 5;
inline void PBApplyFriendData::clear_head_frame() {
  _impl_.head_frame_ = 0;
}
inline int32_t PBApplyFriendData::_internal_head_frame() const {
  return _impl_.head_frame_;
}
inline int32_t PBApplyFriendData::head_frame() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendData.head_frame)
  return _internal_head_frame();
}
inline void PBApplyFriendData::_internal_set_head_frame(int32_t value) {
  
  _impl_.head_frame_ = value;
}
inline void PBApplyFriendData::set_head_frame(int32_t value) {
  _internal_set_head_frame(value);
  // @@protoc_insertion_point(field_set:PBApplyFriendData.head_frame)
}

// int32 title = 6;
inline void PBApplyFriendData::clear_title() {
  _impl_.title_ = 0;
}
inline int32_t PBApplyFriendData::_internal_title() const {
  return _impl_.title_;
}
inline int32_t PBApplyFriendData::title() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendData.title)
  return _internal_title();
}
inline void PBApplyFriendData::_internal_set_title(int32_t value) {
  
  _impl_.title_ = value;
}
inline void PBApplyFriendData::set_title(int32_t value) {
  _internal_set_title(value);
  // @@protoc_insertion_point(field_set:PBApplyFriendData.title)
}

// int32 guild_id = 7;
inline void PBApplyFriendData::clear_guild_id() {
  _impl_.guild_id_ = 0;
}
inline int32_t PBApplyFriendData::_internal_guild_id() const {
  return _impl_.guild_id_;
}
inline int32_t PBApplyFriendData::guild_id() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendData.guild_id)
  return _internal_guild_id();
}
inline void PBApplyFriendData::_internal_set_guild_id(int32_t value) {
  
  _impl_.guild_id_ = value;
}
inline void PBApplyFriendData::set_guild_id(int32_t value) {
  _internal_set_guild_id(value);
  // @@protoc_insertion_point(field_set:PBApplyFriendData.guild_id)
}

// string guild_name = 8;
inline void PBApplyFriendData::clear_guild_name() {
  _impl_.guild_name_.ClearToEmpty();
}
inline const std::string& PBApplyFriendData::guild_name() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendData.guild_name)
  return _internal_guild_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBApplyFriendData::set_guild_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.guild_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBApplyFriendData.guild_name)
}
inline std::string* PBApplyFriendData::mutable_guild_name() {
  std::string* _s = _internal_mutable_guild_name();
  // @@protoc_insertion_point(field_mutable:PBApplyFriendData.guild_name)
  return _s;
}
inline const std::string& PBApplyFriendData::_internal_guild_name() const {
  return _impl_.guild_name_.Get();
}
inline void PBApplyFriendData::_internal_set_guild_name(const std::string& value) {
  
  _impl_.guild_name_.Set(value, GetArenaForAllocation());
}
inline std::string* PBApplyFriendData::_internal_mutable_guild_name() {
  
  return _impl_.guild_name_.Mutable(GetArenaForAllocation());
}
inline std::string* PBApplyFriendData::release_guild_name() {
  // @@protoc_insertion_point(field_release:PBApplyFriendData.guild_name)
  return _impl_.guild_name_.Release();
}
inline void PBApplyFriendData::set_allocated_guild_name(std::string* guild_name) {
  if (guild_name != nullptr) {
    
  } else {
    
  }
  _impl_.guild_name_.SetAllocated(guild_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.guild_name_.IsDefault()) {
    _impl_.guild_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBApplyFriendData.guild_name)
}

// -------------------------------------------------------------------

// PBGetFriendInfoReqCmd

// int64 uid = 1;
inline void PBGetFriendInfoReqCmd::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBGetFriendInfoReqCmd::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBGetFriendInfoReqCmd::uid() const {
  // @@protoc_insertion_point(field_get:PBGetFriendInfoReqCmd.uid)
  return _internal_uid();
}
inline void PBGetFriendInfoReqCmd::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBGetFriendInfoReqCmd::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBGetFriendInfoReqCmd.uid)
}

// -------------------------------------------------------------------

// PBGetFriendInfoRspCmd

// int32 code = 1;
inline void PBGetFriendInfoRspCmd::clear_code() {
  _impl_.code_ = 0;
}
inline int32_t PBGetFriendInfoRspCmd::_internal_code() const {
  return _impl_.code_;
}
inline int32_t PBGetFriendInfoRspCmd::code() const {
  // @@protoc_insertion_point(field_get:PBGetFriendInfoRspCmd.code)
  return _internal_code();
}
inline void PBGetFriendInfoRspCmd::_internal_set_code(int32_t value) {
  
  _impl_.code_ = value;
}
inline void PBGetFriendInfoRspCmd::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:PBGetFriendInfoRspCmd.code)
}

// string error = 2;
inline void PBGetFriendInfoRspCmd::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& PBGetFriendInfoRspCmd::error() const {
  // @@protoc_insertion_point(field_get:PBGetFriendInfoRspCmd.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBGetFriendInfoRspCmd::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBGetFriendInfoRspCmd.error)
}
inline std::string* PBGetFriendInfoRspCmd::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:PBGetFriendInfoRspCmd.error)
  return _s;
}
inline const std::string& PBGetFriendInfoRspCmd::_internal_error() const {
  return _impl_.error_.Get();
}
inline void PBGetFriendInfoRspCmd::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* PBGetFriendInfoRspCmd::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* PBGetFriendInfoRspCmd::release_error() {
  // @@protoc_insertion_point(field_release:PBGetFriendInfoRspCmd.error)
  return _impl_.error_.Release();
}
inline void PBGetFriendInfoRspCmd::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBGetFriendInfoRspCmd.error)
}

// int64 uid = 3;
inline void PBGetFriendInfoRspCmd::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBGetFriendInfoRspCmd::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBGetFriendInfoRspCmd::uid() const {
  // @@protoc_insertion_point(field_get:PBGetFriendInfoRspCmd.uid)
  return _internal_uid();
}
inline void PBGetFriendInfoRspCmd::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBGetFriendInfoRspCmd::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBGetFriendInfoRspCmd.uid)
}

// repeated .PBFriendData friend_datas = 4;
inline int PBGetFriendInfoRspCmd::_internal_friend_datas_size() const {
  return _impl_.friend_datas_.size();
}
inline int PBGetFriendInfoRspCmd::friend_datas_size() const {
  return _internal_friend_datas_size();
}
inline void PBGetFriendInfoRspCmd::clear_friend_datas() {
  _impl_.friend_datas_.Clear();
}
inline ::PBFriendData* PBGetFriendInfoRspCmd::mutable_friend_datas(int index) {
  // @@protoc_insertion_point(field_mutable:PBGetFriendInfoRspCmd.friend_datas)
  return _impl_.friend_datas_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBFriendData >*
PBGetFriendInfoRspCmd::mutable_friend_datas() {
  // @@protoc_insertion_point(field_mutable_list:PBGetFriendInfoRspCmd.friend_datas)
  return &_impl_.friend_datas_;
}
inline const ::PBFriendData& PBGetFriendInfoRspCmd::_internal_friend_datas(int index) const {
  return _impl_.friend_datas_.Get(index);
}
inline const ::PBFriendData& PBGetFriendInfoRspCmd::friend_datas(int index) const {
  // @@protoc_insertion_point(field_get:PBGetFriendInfoRspCmd.friend_datas)
  return _internal_friend_datas(index);
}
inline ::PBFriendData* PBGetFriendInfoRspCmd::_internal_add_friend_datas() {
  return _impl_.friend_datas_.Add();
}
inline ::PBFriendData* PBGetFriendInfoRspCmd::add_friend_datas() {
  ::PBFriendData* _add = _internal_add_friend_datas();
  // @@protoc_insertion_point(field_add:PBGetFriendInfoRspCmd.friend_datas)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBFriendData >&
PBGetFriendInfoRspCmd::friend_datas() const {
  // @@protoc_insertion_point(field_list:PBGetFriendInfoRspCmd.friend_datas)
  return _impl_.friend_datas_;
}

// repeated .PBApplyFriendData apply_datas = 5;
inline int PBGetFriendInfoRspCmd::_internal_apply_datas_size() const {
  return _impl_.apply_datas_.size();
}
inline int PBGetFriendInfoRspCmd::apply_datas_size() const {
  return _internal_apply_datas_size();
}
inline void PBGetFriendInfoRspCmd::clear_apply_datas() {
  _impl_.apply_datas_.Clear();
}
inline ::PBApplyFriendData* PBGetFriendInfoRspCmd::mutable_apply_datas(int index) {
  // @@protoc_insertion_point(field_mutable:PBGetFriendInfoRspCmd.apply_datas)
  return _impl_.apply_datas_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBApplyFriendData >*
PBGetFriendInfoRspCmd::mutable_apply_datas() {
  // @@protoc_insertion_point(field_mutable_list:PBGetFriendInfoRspCmd.apply_datas)
  return &_impl_.apply_datas_;
}
inline const ::PBApplyFriendData& PBGetFriendInfoRspCmd::_internal_apply_datas(int index) const {
  return _impl_.apply_datas_.Get(index);
}
inline const ::PBApplyFriendData& PBGetFriendInfoRspCmd::apply_datas(int index) const {
  // @@protoc_insertion_point(field_get:PBGetFriendInfoRspCmd.apply_datas)
  return _internal_apply_datas(index);
}
inline ::PBApplyFriendData* PBGetFriendInfoRspCmd::_internal_add_apply_datas() {
  return _impl_.apply_datas_.Add();
}
inline ::PBApplyFriendData* PBGetFriendInfoRspCmd::add_apply_datas() {
  ::PBApplyFriendData* _add = _internal_add_apply_datas();
  // @@protoc_insertion_point(field_add:PBGetFriendInfoRspCmd.apply_datas)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBApplyFriendData >&
PBGetFriendInfoRspCmd::apply_datas() const {
  // @@protoc_insertion_point(field_list:PBGetFriendInfoRspCmd.apply_datas)
  return _impl_.apply_datas_;
}

// -------------------------------------------------------------------

// PBApplyFriendReqCmd

// int64 uid = 1;
inline void PBApplyFriendReqCmd::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBApplyFriendReqCmd::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBApplyFriendReqCmd::uid() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendReqCmd.uid)
  return _internal_uid();
}
inline void PBApplyFriendReqCmd::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBApplyFriendReqCmd::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBApplyFriendReqCmd.uid)
}

// .PBApplyFriendData apply_data = 2;
inline bool PBApplyFriendReqCmd::_internal_has_apply_data() const {
  return this != internal_default_instance() && _impl_.apply_data_ != nullptr;
}
inline bool PBApplyFriendReqCmd::has_apply_data() const {
  return _internal_has_apply_data();
}
inline void PBApplyFriendReqCmd::clear_apply_data() {
  if (GetArenaForAllocation() == nullptr && _impl_.apply_data_ != nullptr) {
    delete _impl_.apply_data_;
  }
  _impl_.apply_data_ = nullptr;
}
inline const ::PBApplyFriendData& PBApplyFriendReqCmd::_internal_apply_data() const {
  const ::PBApplyFriendData* p = _impl_.apply_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::PBApplyFriendData&>(
      ::_PBApplyFriendData_default_instance_);
}
inline const ::PBApplyFriendData& PBApplyFriendReqCmd::apply_data() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendReqCmd.apply_data)
  return _internal_apply_data();
}
inline void PBApplyFriendReqCmd::unsafe_arena_set_allocated_apply_data(
    ::PBApplyFriendData* apply_data) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.apply_data_);
  }
  _impl_.apply_data_ = apply_data;
  if (apply_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PBApplyFriendReqCmd.apply_data)
}
inline ::PBApplyFriendData* PBApplyFriendReqCmd::release_apply_data() {
  
  ::PBApplyFriendData* temp = _impl_.apply_data_;
  _impl_.apply_data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PBApplyFriendData* PBApplyFriendReqCmd::unsafe_arena_release_apply_data() {
  // @@protoc_insertion_point(field_release:PBApplyFriendReqCmd.apply_data)
  
  ::PBApplyFriendData* temp = _impl_.apply_data_;
  _impl_.apply_data_ = nullptr;
  return temp;
}
inline ::PBApplyFriendData* PBApplyFriendReqCmd::_internal_mutable_apply_data() {
  
  if (_impl_.apply_data_ == nullptr) {
    auto* p = CreateMaybeMessage<::PBApplyFriendData>(GetArenaForAllocation());
    _impl_.apply_data_ = p;
  }
  return _impl_.apply_data_;
}
inline ::PBApplyFriendData* PBApplyFriendReqCmd::mutable_apply_data() {
  ::PBApplyFriendData* _msg = _internal_mutable_apply_data();
  // @@protoc_insertion_point(field_mutable:PBApplyFriendReqCmd.apply_data)
  return _msg;
}
inline void PBApplyFriendReqCmd::set_allocated_apply_data(::PBApplyFriendData* apply_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.apply_data_;
  }
  if (apply_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(apply_data);
    if (message_arena != submessage_arena) {
      apply_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, apply_data, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.apply_data_ = apply_data;
  // @@protoc_insertion_point(field_set_allocated:PBApplyFriendReqCmd.apply_data)
}

// -------------------------------------------------------------------

// PBApplyFriendRspCmd

// int32 code = 1;
inline void PBApplyFriendRspCmd::clear_code() {
  _impl_.code_ = 0;
}
inline int32_t PBApplyFriendRspCmd::_internal_code() const {
  return _impl_.code_;
}
inline int32_t PBApplyFriendRspCmd::code() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendRspCmd.code)
  return _internal_code();
}
inline void PBApplyFriendRspCmd::_internal_set_code(int32_t value) {
  
  _impl_.code_ = value;
}
inline void PBApplyFriendRspCmd::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:PBApplyFriendRspCmd.code)
}

// string error = 2;
inline void PBApplyFriendRspCmd::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& PBApplyFriendRspCmd::error() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendRspCmd.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBApplyFriendRspCmd::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBApplyFriendRspCmd.error)
}
inline std::string* PBApplyFriendRspCmd::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:PBApplyFriendRspCmd.error)
  return _s;
}
inline const std::string& PBApplyFriendRspCmd::_internal_error() const {
  return _impl_.error_.Get();
}
inline void PBApplyFriendRspCmd::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* PBApplyFriendRspCmd::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* PBApplyFriendRspCmd::release_error() {
  // @@protoc_insertion_point(field_release:PBApplyFriendRspCmd.error)
  return _impl_.error_.Release();
}
inline void PBApplyFriendRspCmd::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBApplyFriendRspCmd.error)
}

// int64 uid = 3;
inline void PBApplyFriendRspCmd::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBApplyFriendRspCmd::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBApplyFriendRspCmd::uid() const {
  // @@protoc_insertion_point(field_get:PBApplyFriendRspCmd.uid)
  return _internal_uid();
}
inline void PBApplyFriendRspCmd::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBApplyFriendRspCmd::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBApplyFriendRspCmd.uid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_friend_2eproto
