// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mail.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mail_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mail_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mail_2eproto COMMONNETUE_API
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct COMMONNETUE_API TableStruct_mail_2eproto {
  static const uint32_t offsets[];
};
COMMONNETUE_API extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mail_2eproto;
class PBGetMailItemReqCmd;
struct PBGetMailItemReqCmdDefaultTypeInternal;
COMMONNETUE_API extern PBGetMailItemReqCmdDefaultTypeInternal _PBGetMailItemReqCmd_default_instance_;
class PBGetMailItemRspCmd;
struct PBGetMailItemRspCmdDefaultTypeInternal;
COMMONNETUE_API extern PBGetMailItemRspCmdDefaultTypeInternal _PBGetMailItemRspCmd_default_instance_;
class PBMailData;
struct PBMailDataDefaultTypeInternal;
COMMONNETUE_API extern PBMailDataDefaultTypeInternal _PBMailData_default_instance_;
class PBMailItem;
struct PBMailItemDefaultTypeInternal;
COMMONNETUE_API extern PBMailItemDefaultTypeInternal _PBMailItem_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> COMMONNETUE_API ::PBGetMailItemReqCmd* Arena::CreateMaybeMessage<::PBGetMailItemReqCmd>(Arena*);
template<> COMMONNETUE_API ::PBGetMailItemRspCmd* Arena::CreateMaybeMessage<::PBGetMailItemRspCmd>(Arena*);
template<> COMMONNETUE_API ::PBMailData* Arena::CreateMaybeMessage<::PBMailData>(Arena*);
template<> COMMONNETUE_API ::PBMailItem* Arena::CreateMaybeMessage<::PBMailItem>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class COMMONNETUE_API PBMailItem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBMailItem) */ {
 public:
  inline PBMailItem() : PBMailItem(nullptr) {}
  ~PBMailItem() override;
  explicit PROTOBUF_CONSTEXPR PBMailItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBMailItem(const PBMailItem& from);
  PBMailItem(PBMailItem&& from) noexcept
    : PBMailItem() {
    *this = ::std::move(from);
  }

  inline PBMailItem& operator=(const PBMailItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBMailItem& operator=(PBMailItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBMailItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBMailItem* internal_default_instance() {
    return reinterpret_cast<const PBMailItem*>(
               &_PBMailItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PBMailItem& a, PBMailItem& b) {
    a.Swap(&b);
  }
  inline void Swap(PBMailItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBMailItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBMailItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBMailItem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBMailItem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBMailItem& from) {
    PBMailItem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBMailItem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBMailItem";
  }
  protected:
  explicit PBMailItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemIdFieldNumber = 1,
    kItemCountFieldNumber = 2,
  };
  // int32 item_id = 1;
  void clear_item_id();
  int32_t item_id() const;
  void set_item_id(int32_t value);
  private:
  int32_t _internal_item_id() const;
  void _internal_set_item_id(int32_t value);
  public:

  // int32 item_count = 2;
  void clear_item_count();
  int32_t item_count() const;
  void set_item_count(int32_t value);
  private:
  int32_t _internal_item_count() const;
  void _internal_set_item_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBMailItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t item_id_;
    int32_t item_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mail_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBMailData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBMailData) */ {
 public:
  inline PBMailData() : PBMailData(nullptr) {}
  ~PBMailData() override;
  explicit PROTOBUF_CONSTEXPR PBMailData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBMailData(const PBMailData& from);
  PBMailData(PBMailData&& from) noexcept
    : PBMailData() {
    *this = ::std::move(from);
  }

  inline PBMailData& operator=(const PBMailData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBMailData& operator=(PBMailData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBMailData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBMailData* internal_default_instance() {
    return reinterpret_cast<const PBMailData*>(
               &_PBMailData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PBMailData& a, PBMailData& b) {
    a.Swap(&b);
  }
  inline void Swap(PBMailData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBMailData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBMailData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBMailData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBMailData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBMailData& from) {
    PBMailData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBMailData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBMailData";
  }
  protected:
  explicit PBMailData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 10,
    kMailTitleFieldNumber = 5,
    kMailContentFieldNumber = 6,
    kMailIdFieldNumber = 1,
    kBegTsFieldNumber = 3,
    kEndTsFieldNumber = 4,
    kMailTypeFieldNumber = 2,
    kIsReadFieldNumber = 7,
    kIsGetFieldNumber = 8,
    kIsDelFieldNumber = 9,
  };
  // repeated .PBMailItem items = 10;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::PBMailItem* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBMailItem >*
      mutable_items();
  private:
  const ::PBMailItem& _internal_items(int index) const;
  ::PBMailItem* _internal_add_items();
  public:
  const ::PBMailItem& items(int index) const;
  ::PBMailItem* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBMailItem >&
      items() const;

  // string mail_title = 5;
  void clear_mail_title();
  const std::string& mail_title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mail_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mail_title();
  PROTOBUF_NODISCARD std::string* release_mail_title();
  void set_allocated_mail_title(std::string* mail_title);
  private:
  const std::string& _internal_mail_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mail_title(const std::string& value);
  std::string* _internal_mutable_mail_title();
  public:

  // string mail_content = 6;
  void clear_mail_content();
  const std::string& mail_content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mail_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mail_content();
  PROTOBUF_NODISCARD std::string* release_mail_content();
  void set_allocated_mail_content(std::string* mail_content);
  private:
  const std::string& _internal_mail_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mail_content(const std::string& value);
  std::string* _internal_mutable_mail_content();
  public:

  // int64 mail_id = 1;
  void clear_mail_id();
  int64_t mail_id() const;
  void set_mail_id(int64_t value);
  private:
  int64_t _internal_mail_id() const;
  void _internal_set_mail_id(int64_t value);
  public:

  // int64 beg_ts = 3;
  void clear_beg_ts();
  int64_t beg_ts() const;
  void set_beg_ts(int64_t value);
  private:
  int64_t _internal_beg_ts() const;
  void _internal_set_beg_ts(int64_t value);
  public:

  // int64 end_ts = 4;
  void clear_end_ts();
  int64_t end_ts() const;
  void set_end_ts(int64_t value);
  private:
  int64_t _internal_end_ts() const;
  void _internal_set_end_ts(int64_t value);
  public:

  // int32 mail_type = 2;
  void clear_mail_type();
  int32_t mail_type() const;
  void set_mail_type(int32_t value);
  private:
  int32_t _internal_mail_type() const;
  void _internal_set_mail_type(int32_t value);
  public:

  // int32 is_read = 7;
  void clear_is_read();
  int32_t is_read() const;
  void set_is_read(int32_t value);
  private:
  int32_t _internal_is_read() const;
  void _internal_set_is_read(int32_t value);
  public:

  // int32 is_get = 8;
  void clear_is_get();
  int32_t is_get() const;
  void set_is_get(int32_t value);
  private:
  int32_t _internal_is_get() const;
  void _internal_set_is_get(int32_t value);
  public:

  // int32 is_del = 9;
  void clear_is_del();
  int32_t is_del() const;
  void set_is_del(int32_t value);
  private:
  int32_t _internal_is_del() const;
  void _internal_set_is_del(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBMailData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBMailItem > items_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mail_title_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mail_content_;
    int64_t mail_id_;
    int64_t beg_ts_;
    int64_t end_ts_;
    int32_t mail_type_;
    int32_t is_read_;
    int32_t is_get_;
    int32_t is_del_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mail_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBGetMailItemReqCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBGetMailItemReqCmd) */ {
 public:
  inline PBGetMailItemReqCmd() : PBGetMailItemReqCmd(nullptr) {}
  ~PBGetMailItemReqCmd() override;
  explicit PROTOBUF_CONSTEXPR PBGetMailItemReqCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBGetMailItemReqCmd(const PBGetMailItemReqCmd& from);
  PBGetMailItemReqCmd(PBGetMailItemReqCmd&& from) noexcept
    : PBGetMailItemReqCmd() {
    *this = ::std::move(from);
  }

  inline PBGetMailItemReqCmd& operator=(const PBGetMailItemReqCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBGetMailItemReqCmd& operator=(PBGetMailItemReqCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBGetMailItemReqCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBGetMailItemReqCmd* internal_default_instance() {
    return reinterpret_cast<const PBGetMailItemReqCmd*>(
               &_PBGetMailItemReqCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PBGetMailItemReqCmd& a, PBGetMailItemReqCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(PBGetMailItemReqCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBGetMailItemReqCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBGetMailItemReqCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBGetMailItemReqCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBGetMailItemReqCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBGetMailItemReqCmd& from) {
    PBGetMailItemReqCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBGetMailItemReqCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBGetMailItemReqCmd";
  }
  protected:
  explicit PBGetMailItemReqCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUidFieldNumber = 1,
    kMailIdFieldNumber = 2,
  };
  // int64 uid = 1;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // int64 mail_id = 2;
  void clear_mail_id();
  int64_t mail_id() const;
  void set_mail_id(int64_t value);
  private:
  int64_t _internal_mail_id() const;
  void _internal_set_mail_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBGetMailItemReqCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t uid_;
    int64_t mail_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mail_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBGetMailItemRspCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBGetMailItemRspCmd) */ {
 public:
  inline PBGetMailItemRspCmd() : PBGetMailItemRspCmd(nullptr) {}
  ~PBGetMailItemRspCmd() override;
  explicit PROTOBUF_CONSTEXPR PBGetMailItemRspCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBGetMailItemRspCmd(const PBGetMailItemRspCmd& from);
  PBGetMailItemRspCmd(PBGetMailItemRspCmd&& from) noexcept
    : PBGetMailItemRspCmd() {
    *this = ::std::move(from);
  }

  inline PBGetMailItemRspCmd& operator=(const PBGetMailItemRspCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBGetMailItemRspCmd& operator=(PBGetMailItemRspCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBGetMailItemRspCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBGetMailItemRspCmd* internal_default_instance() {
    return reinterpret_cast<const PBGetMailItemRspCmd*>(
               &_PBGetMailItemRspCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PBGetMailItemRspCmd& a, PBGetMailItemRspCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(PBGetMailItemRspCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBGetMailItemRspCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBGetMailItemRspCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBGetMailItemRspCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBGetMailItemRspCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBGetMailItemRspCmd& from) {
    PBGetMailItemRspCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBGetMailItemRspCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBGetMailItemRspCmd";
  }
  protected:
  explicit PBGetMailItemRspCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 2,
    kMailDataFieldNumber = 4,
    kUidFieldNumber = 3,
    kCodeFieldNumber = 1,
  };
  // string error = 2;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // .PBMailData mail_data = 4;
  bool has_mail_data() const;
  private:
  bool _internal_has_mail_data() const;
  public:
  void clear_mail_data();
  const ::PBMailData& mail_data() const;
  PROTOBUF_NODISCARD ::PBMailData* release_mail_data();
  ::PBMailData* mutable_mail_data();
  void set_allocated_mail_data(::PBMailData* mail_data);
  private:
  const ::PBMailData& _internal_mail_data() const;
  ::PBMailData* _internal_mutable_mail_data();
  public:
  void unsafe_arena_set_allocated_mail_data(
      ::PBMailData* mail_data);
  ::PBMailData* unsafe_arena_release_mail_data();

  // int64 uid = 3;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // int32 code = 1;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBGetMailItemRspCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    ::PBMailData* mail_data_;
    int64_t uid_;
    int32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mail_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PBMailItem

// int32 item_id = 1;
inline void PBMailItem::clear_item_id() {
  _impl_.item_id_ = 0;
}
inline int32_t PBMailItem::_internal_item_id() const {
  return _impl_.item_id_;
}
inline int32_t PBMailItem::item_id() const {
  // @@protoc_insertion_point(field_get:PBMailItem.item_id)
  return _internal_item_id();
}
inline void PBMailItem::_internal_set_item_id(int32_t value) {
  
  _impl_.item_id_ = value;
}
inline void PBMailItem::set_item_id(int32_t value) {
  _internal_set_item_id(value);
  // @@protoc_insertion_point(field_set:PBMailItem.item_id)
}

// int32 item_count = 2;
inline void PBMailItem::clear_item_count() {
  _impl_.item_count_ = 0;
}
inline int32_t PBMailItem::_internal_item_count() const {
  return _impl_.item_count_;
}
inline int32_t PBMailItem::item_count() const {
  // @@protoc_insertion_point(field_get:PBMailItem.item_count)
  return _internal_item_count();
}
inline void PBMailItem::_internal_set_item_count(int32_t value) {
  
  _impl_.item_count_ = value;
}
inline void PBMailItem::set_item_count(int32_t value) {
  _internal_set_item_count(value);
  // @@protoc_insertion_point(field_set:PBMailItem.item_count)
}

// -------------------------------------------------------------------

// PBMailData

// int64 mail_id = 1;
inline void PBMailData::clear_mail_id() {
  _impl_.mail_id_ = int64_t{0};
}
inline int64_t PBMailData::_internal_mail_id() const {
  return _impl_.mail_id_;
}
inline int64_t PBMailData::mail_id() const {
  // @@protoc_insertion_point(field_get:PBMailData.mail_id)
  return _internal_mail_id();
}
inline void PBMailData::_internal_set_mail_id(int64_t value) {
  
  _impl_.mail_id_ = value;
}
inline void PBMailData::set_mail_id(int64_t value) {
  _internal_set_mail_id(value);
  // @@protoc_insertion_point(field_set:PBMailData.mail_id)
}

// int32 mail_type = 2;
inline void PBMailData::clear_mail_type() {
  _impl_.mail_type_ = 0;
}
inline int32_t PBMailData::_internal_mail_type() const {
  return _impl_.mail_type_;
}
inline int32_t PBMailData::mail_type() const {
  // @@protoc_insertion_point(field_get:PBMailData.mail_type)
  return _internal_mail_type();
}
inline void PBMailData::_internal_set_mail_type(int32_t value) {
  
  _impl_.mail_type_ = value;
}
inline void PBMailData::set_mail_type(int32_t value) {
  _internal_set_mail_type(value);
  // @@protoc_insertion_point(field_set:PBMailData.mail_type)
}

// int64 beg_ts = 3;
inline void PBMailData::clear_beg_ts() {
  _impl_.beg_ts_ = int64_t{0};
}
inline int64_t PBMailData::_internal_beg_ts() const {
  return _impl_.beg_ts_;
}
inline int64_t PBMailData::beg_ts() const {
  // @@protoc_insertion_point(field_get:PBMailData.beg_ts)
  return _internal_beg_ts();
}
inline void PBMailData::_internal_set_beg_ts(int64_t value) {
  
  _impl_.beg_ts_ = value;
}
inline void PBMailData::set_beg_ts(int64_t value) {
  _internal_set_beg_ts(value);
  // @@protoc_insertion_point(field_set:PBMailData.beg_ts)
}

// int64 end_ts = 4;
inline void PBMailData::clear_end_ts() {
  _impl_.end_ts_ = int64_t{0};
}
inline int64_t PBMailData::_internal_end_ts() const {
  return _impl_.end_ts_;
}
inline int64_t PBMailData::end_ts() const {
  // @@protoc_insertion_point(field_get:PBMailData.end_ts)
  return _internal_end_ts();
}
inline void PBMailData::_internal_set_end_ts(int64_t value) {
  
  _impl_.end_ts_ = value;
}
inline void PBMailData::set_end_ts(int64_t value) {
  _internal_set_end_ts(value);
  // @@protoc_insertion_point(field_set:PBMailData.end_ts)
}

// string mail_title = 5;
inline void PBMailData::clear_mail_title() {
  _impl_.mail_title_.ClearToEmpty();
}
inline const std::string& PBMailData::mail_title() const {
  // @@protoc_insertion_point(field_get:PBMailData.mail_title)
  return _internal_mail_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBMailData::set_mail_title(ArgT0&& arg0, ArgT... args) {
 
 _impl_.mail_title_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBMailData.mail_title)
}
inline std::string* PBMailData::mutable_mail_title() {
  std::string* _s = _internal_mutable_mail_title();
  // @@protoc_insertion_point(field_mutable:PBMailData.mail_title)
  return _s;
}
inline const std::string& PBMailData::_internal_mail_title() const {
  return _impl_.mail_title_.Get();
}
inline void PBMailData::_internal_set_mail_title(const std::string& value) {
  
  _impl_.mail_title_.Set(value, GetArenaForAllocation());
}
inline std::string* PBMailData::_internal_mutable_mail_title() {
  
  return _impl_.mail_title_.Mutable(GetArenaForAllocation());
}
inline std::string* PBMailData::release_mail_title() {
  // @@protoc_insertion_point(field_release:PBMailData.mail_title)
  return _impl_.mail_title_.Release();
}
inline void PBMailData::set_allocated_mail_title(std::string* mail_title) {
  if (mail_title != nullptr) {
    
  } else {
    
  }
  _impl_.mail_title_.SetAllocated(mail_title, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.mail_title_.IsDefault()) {
    _impl_.mail_title_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBMailData.mail_title)
}

// string mail_content = 6;
inline void PBMailData::clear_mail_content() {
  _impl_.mail_content_.ClearToEmpty();
}
inline const std::string& PBMailData::mail_content() const {
  // @@protoc_insertion_point(field_get:PBMailData.mail_content)
  return _internal_mail_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBMailData::set_mail_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.mail_content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBMailData.mail_content)
}
inline std::string* PBMailData::mutable_mail_content() {
  std::string* _s = _internal_mutable_mail_content();
  // @@protoc_insertion_point(field_mutable:PBMailData.mail_content)
  return _s;
}
inline const std::string& PBMailData::_internal_mail_content() const {
  return _impl_.mail_content_.Get();
}
inline void PBMailData::_internal_set_mail_content(const std::string& value) {
  
  _impl_.mail_content_.Set(value, GetArenaForAllocation());
}
inline std::string* PBMailData::_internal_mutable_mail_content() {
  
  return _impl_.mail_content_.Mutable(GetArenaForAllocation());
}
inline std::string* PBMailData::release_mail_content() {
  // @@protoc_insertion_point(field_release:PBMailData.mail_content)
  return _impl_.mail_content_.Release();
}
inline void PBMailData::set_allocated_mail_content(std::string* mail_content) {
  if (mail_content != nullptr) {
    
  } else {
    
  }
  _impl_.mail_content_.SetAllocated(mail_content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.mail_content_.IsDefault()) {
    _impl_.mail_content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBMailData.mail_content)
}

// int32 is_read = 7;
inline void PBMailData::clear_is_read() {
  _impl_.is_read_ = 0;
}
inline int32_t PBMailData::_internal_is_read() const {
  return _impl_.is_read_;
}
inline int32_t PBMailData::is_read() const {
  // @@protoc_insertion_point(field_get:PBMailData.is_read)
  return _internal_is_read();
}
inline void PBMailData::_internal_set_is_read(int32_t value) {
  
  _impl_.is_read_ = value;
}
inline void PBMailData::set_is_read(int32_t value) {
  _internal_set_is_read(value);
  // @@protoc_insertion_point(field_set:PBMailData.is_read)
}

// int32 is_get = 8;
inline void PBMailData::clear_is_get() {
  _impl_.is_get_ = 0;
}
inline int32_t PBMailData::_internal_is_get() const {
  return _impl_.is_get_;
}
inline int32_t PBMailData::is_get() const {
  // @@protoc_insertion_point(field_get:PBMailData.is_get)
  return _internal_is_get();
}
inline void PBMailData::_internal_set_is_get(int32_t value) {
  
  _impl_.is_get_ = value;
}
inline void PBMailData::set_is_get(int32_t value) {
  _internal_set_is_get(value);
  // @@protoc_insertion_point(field_set:PBMailData.is_get)
}

// int32 is_del = 9;
inline void PBMailData::clear_is_del() {
  _impl_.is_del_ = 0;
}
inline int32_t PBMailData::_internal_is_del() const {
  return _impl_.is_del_;
}
inline int32_t PBMailData::is_del() const {
  // @@protoc_insertion_point(field_get:PBMailData.is_del)
  return _internal_is_del();
}
inline void PBMailData::_internal_set_is_del(int32_t value) {
  
  _impl_.is_del_ = value;
}
inline void PBMailData::set_is_del(int32_t value) {
  _internal_set_is_del(value);
  // @@protoc_insertion_point(field_set:PBMailData.is_del)
}

// repeated .PBMailItem items = 10;
inline int PBMailData::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int PBMailData::items_size() const {
  return _internal_items_size();
}
inline void PBMailData::clear_items() {
  _impl_.items_.Clear();
}
inline ::PBMailItem* PBMailData::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:PBMailData.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBMailItem >*
PBMailData::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:PBMailData.items)
  return &_impl_.items_;
}
inline const ::PBMailItem& PBMailData::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::PBMailItem& PBMailData::items(int index) const {
  // @@protoc_insertion_point(field_get:PBMailData.items)
  return _internal_items(index);
}
inline ::PBMailItem* PBMailData::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::PBMailItem* PBMailData::add_items() {
  ::PBMailItem* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:PBMailData.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBMailItem >&
PBMailData::items() const {
  // @@protoc_insertion_point(field_list:PBMailData.items)
  return _impl_.items_;
}

// -------------------------------------------------------------------

// PBGetMailItemReqCmd

// int64 uid = 1;
inline void PBGetMailItemReqCmd::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBGetMailItemReqCmd::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBGetMailItemReqCmd::uid() const {
  // @@protoc_insertion_point(field_get:PBGetMailItemReqCmd.uid)
  return _internal_uid();
}
inline void PBGetMailItemReqCmd::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBGetMailItemReqCmd::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBGetMailItemReqCmd.uid)
}

// int64 mail_id = 2;
inline void PBGetMailItemReqCmd::clear_mail_id() {
  _impl_.mail_id_ = int64_t{0};
}
inline int64_t PBGetMailItemReqCmd::_internal_mail_id() const {
  return _impl_.mail_id_;
}
inline int64_t PBGetMailItemReqCmd::mail_id() const {
  // @@protoc_insertion_point(field_get:PBGetMailItemReqCmd.mail_id)
  return _internal_mail_id();
}
inline void PBGetMailItemReqCmd::_internal_set_mail_id(int64_t value) {
  
  _impl_.mail_id_ = value;
}
inline void PBGetMailItemReqCmd::set_mail_id(int64_t value) {
  _internal_set_mail_id(value);
  // @@protoc_insertion_point(field_set:PBGetMailItemReqCmd.mail_id)
}

// -------------------------------------------------------------------

// PBGetMailItemRspCmd

// int32 code = 1;
inline void PBGetMailItemRspCmd::clear_code() {
  _impl_.code_ = 0;
}
inline int32_t PBGetMailItemRspCmd::_internal_code() const {
  return _impl_.code_;
}
inline int32_t PBGetMailItemRspCmd::code() const {
  // @@protoc_insertion_point(field_get:PBGetMailItemRspCmd.code)
  return _internal_code();
}
inline void PBGetMailItemRspCmd::_internal_set_code(int32_t value) {
  
  _impl_.code_ = value;
}
inline void PBGetMailItemRspCmd::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:PBGetMailItemRspCmd.code)
}

// string error = 2;
inline void PBGetMailItemRspCmd::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& PBGetMailItemRspCmd::error() const {
  // @@protoc_insertion_point(field_get:PBGetMailItemRspCmd.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBGetMailItemRspCmd::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBGetMailItemRspCmd.error)
}
inline std::string* PBGetMailItemRspCmd::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:PBGetMailItemRspCmd.error)
  return _s;
}
inline const std::string& PBGetMailItemRspCmd::_internal_error() const {
  return _impl_.error_.Get();
}
inline void PBGetMailItemRspCmd::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* PBGetMailItemRspCmd::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* PBGetMailItemRspCmd::release_error() {
  // @@protoc_insertion_point(field_release:PBGetMailItemRspCmd.error)
  return _impl_.error_.Release();
}
inline void PBGetMailItemRspCmd::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBGetMailItemRspCmd.error)
}

// int64 uid = 3;
inline void PBGetMailItemRspCmd::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBGetMailItemRspCmd::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBGetMailItemRspCmd::uid() const {
  // @@protoc_insertion_point(field_get:PBGetMailItemRspCmd.uid)
  return _internal_uid();
}
inline void PBGetMailItemRspCmd::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBGetMailItemRspCmd::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBGetMailItemRspCmd.uid)
}

// .PBMailData mail_data = 4;
inline bool PBGetMailItemRspCmd::_internal_has_mail_data() const {
  return this != internal_default_instance() && _impl_.mail_data_ != nullptr;
}
inline bool PBGetMailItemRspCmd::has_mail_data() const {
  return _internal_has_mail_data();
}
inline void PBGetMailItemRspCmd::clear_mail_data() {
  if (GetArenaForAllocation() == nullptr && _impl_.mail_data_ != nullptr) {
    delete _impl_.mail_data_;
  }
  _impl_.mail_data_ = nullptr;
}
inline const ::PBMailData& PBGetMailItemRspCmd::_internal_mail_data() const {
  const ::PBMailData* p = _impl_.mail_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::PBMailData&>(
      ::_PBMailData_default_instance_);
}
inline const ::PBMailData& PBGetMailItemRspCmd::mail_data() const {
  // @@protoc_insertion_point(field_get:PBGetMailItemRspCmd.mail_data)
  return _internal_mail_data();
}
inline void PBGetMailItemRspCmd::unsafe_arena_set_allocated_mail_data(
    ::PBMailData* mail_data) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.mail_data_);
  }
  _impl_.mail_data_ = mail_data;
  if (mail_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PBGetMailItemRspCmd.mail_data)
}
inline ::PBMailData* PBGetMailItemRspCmd::release_mail_data() {
  
  ::PBMailData* temp = _impl_.mail_data_;
  _impl_.mail_data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PBMailData* PBGetMailItemRspCmd::unsafe_arena_release_mail_data() {
  // @@protoc_insertion_point(field_release:PBGetMailItemRspCmd.mail_data)
  
  ::PBMailData* temp = _impl_.mail_data_;
  _impl_.mail_data_ = nullptr;
  return temp;
}
inline ::PBMailData* PBGetMailItemRspCmd::_internal_mutable_mail_data() {
  
  if (_impl_.mail_data_ == nullptr) {
    auto* p = CreateMaybeMessage<::PBMailData>(GetArenaForAllocation());
    _impl_.mail_data_ = p;
  }
  return _impl_.mail_data_;
}
inline ::PBMailData* PBGetMailItemRspCmd::mutable_mail_data() {
  ::PBMailData* _msg = _internal_mutable_mail_data();
  // @@protoc_insertion_point(field_mutable:PBGetMailItemRspCmd.mail_data)
  return _msg;
}
inline void PBGetMailItemRspCmd::set_allocated_mail_data(::PBMailData* mail_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.mail_data_;
  }
  if (mail_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(mail_data);
    if (message_arena != submessage_arena) {
      mail_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, mail_data, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.mail_data_ = mail_data;
  // @@protoc_insertion_point(field_set_allocated:PBGetMailItemRspCmd.mail_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mail_2eproto
