#pragma once
#include "CoreMinimal.h"
#include "Net/ProtobufMessage.h"
#include "mission.generated.h"

// Generated by Proto3 to UE5 Struct Converter



USTRUCT(BlueprintType)
struct FPBConditionData
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 CondId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 CondType = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 CondTarget = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 Progress = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 IsComplete = 0;
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCondId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCondType = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCondTarget = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasProgress = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasIsComplete = false;
};

USTRUCT(BlueprintType)
struct FPBMissionData
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 MissionId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 MissionType = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 IsComplete = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 IsGet = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 BegTs = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 EndTs = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	TArray<FPBConditionData> CondDatas = {};
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasMissionId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasMissionType = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasIsComplete = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasIsGet = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasBegTs = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasEndTs = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCondDatas = false;
};
// 更新任务进度
UCLASS(BlueprintType)
class UPBUpdateMissionSeverSyncCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	// 协议数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 Uid = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 CondId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 CondType = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 UpdateProgress = 0;
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUid = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCondId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCondType = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUpdateProgress = false;
};
// 更新任务进度 通知玩家
UCLASS(BlueprintType)
class UPBUpdateMissionClientSyncCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	//好友数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	TArray<FPBMissionData> UpdateMissionDatas = {};
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUpdateMissionDatas = false;
};
