#pragma once
#include "CoreMinimal.h"
#include "Net/ProtobufMessage.h"
#include "rank.generated.h"

// Generated by Proto3 to UE5 Struct Converter



USTRUCT(BlueprintType)
struct FPBRankData
{
	GENERATED_BODY()

	//宗门id或者玩家id
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 Id = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 Idx = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 Score = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	FString RankData = TEXT("");
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasIdx = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasScore = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasRankData = false;
};

USTRUCT(BlueprintType)
struct FPBRankInfo
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 RankId = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 BegTs = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 EndTs = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	TArray<FPBRankData> Datas = {};
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasRankId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasBegTs = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasEndTs = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasDatas = false;
};
// 客户端请求排行榜数据
UCLASS(BlueprintType)
class UPBGetRankInfoReqCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	// 协议数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 Uid = 0LL;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 RankId = 0;
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUid = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasRankId = false;
};
// 客户端请求排行榜数据 返回信息
UCLASS(BlueprintType)
class UPBGetRankInfoRspCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	// 服务器返回,0成功,其他失败
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 Code = 0;
	// 错误信息
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	FString Error = TEXT("");
	// 协议数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 Uid = 0LL;
	//排行榜数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	FPBRankInfo RankInfo = {};
	//本榜中玩家自身数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	FPBRankData SelfData = {};
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCode = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasError = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUid = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasRankInfo = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasSelfData = false;
};
