// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rank_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rank_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rank_2eproto COMMONNETUE_API
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct COMMONNETUE_API TableStruct_rank_2eproto {
  static const uint32_t offsets[];
};
COMMONNETUE_API extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rank_2eproto;
class PBGetRankInfoReqCmd;
struct PBGetRankInfoReqCmdDefaultTypeInternal;
COMMONNETUE_API extern PBGetRankInfoReqCmdDefaultTypeInternal _PBGetRankInfoReqCmd_default_instance_;
class PBGetRankInfoRspCmd;
struct PBGetRankInfoRspCmdDefaultTypeInternal;
COMMONNETUE_API extern PBGetRankInfoRspCmdDefaultTypeInternal _PBGetRankInfoRspCmd_default_instance_;
class PBRankData;
struct PBRankDataDefaultTypeInternal;
COMMONNETUE_API extern PBRankDataDefaultTypeInternal _PBRankData_default_instance_;
class PBRankInfo;
struct PBRankInfoDefaultTypeInternal;
COMMONNETUE_API extern PBRankInfoDefaultTypeInternal _PBRankInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> COMMONNETUE_API ::PBGetRankInfoReqCmd* Arena::CreateMaybeMessage<::PBGetRankInfoReqCmd>(Arena*);
template<> COMMONNETUE_API ::PBGetRankInfoRspCmd* Arena::CreateMaybeMessage<::PBGetRankInfoRspCmd>(Arena*);
template<> COMMONNETUE_API ::PBRankData* Arena::CreateMaybeMessage<::PBRankData>(Arena*);
template<> COMMONNETUE_API ::PBRankInfo* Arena::CreateMaybeMessage<::PBRankInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class COMMONNETUE_API PBRankData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBRankData) */ {
 public:
  inline PBRankData() : PBRankData(nullptr) {}
  ~PBRankData() override;
  explicit PROTOBUF_CONSTEXPR PBRankData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBRankData(const PBRankData& from);
  PBRankData(PBRankData&& from) noexcept
    : PBRankData() {
    *this = ::std::move(from);
  }

  inline PBRankData& operator=(const PBRankData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBRankData& operator=(PBRankData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBRankData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBRankData* internal_default_instance() {
    return reinterpret_cast<const PBRankData*>(
               &_PBRankData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PBRankData& a, PBRankData& b) {
    a.Swap(&b);
  }
  inline void Swap(PBRankData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBRankData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBRankData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBRankData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBRankData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBRankData& from) {
    PBRankData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBRankData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBRankData";
  }
  protected:
  explicit PBRankData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRankDataFieldNumber = 4,
    kIdFieldNumber = 1,
    kScoreFieldNumber = 3,
    kIdxFieldNumber = 2,
  };
  // string rank_data = 4;
  void clear_rank_data();
  const std::string& rank_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_rank_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_rank_data();
  PROTOBUF_NODISCARD std::string* release_rank_data();
  void set_allocated_rank_data(std::string* rank_data);
  private:
  const std::string& _internal_rank_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rank_data(const std::string& value);
  std::string* _internal_mutable_rank_data();
  public:

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // int64 score = 3;
  void clear_score();
  int64_t score() const;
  void set_score(int64_t value);
  private:
  int64_t _internal_score() const;
  void _internal_set_score(int64_t value);
  public:

  // int32 idx = 2;
  void clear_idx();
  int32_t idx() const;
  void set_idx(int32_t value);
  private:
  int32_t _internal_idx() const;
  void _internal_set_idx(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBRankData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rank_data_;
    int64_t id_;
    int64_t score_;
    int32_t idx_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rank_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBRankInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBRankInfo) */ {
 public:
  inline PBRankInfo() : PBRankInfo(nullptr) {}
  ~PBRankInfo() override;
  explicit PROTOBUF_CONSTEXPR PBRankInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBRankInfo(const PBRankInfo& from);
  PBRankInfo(PBRankInfo&& from) noexcept
    : PBRankInfo() {
    *this = ::std::move(from);
  }

  inline PBRankInfo& operator=(const PBRankInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBRankInfo& operator=(PBRankInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBRankInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBRankInfo* internal_default_instance() {
    return reinterpret_cast<const PBRankInfo*>(
               &_PBRankInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PBRankInfo& a, PBRankInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PBRankInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBRankInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBRankInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBRankInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBRankInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBRankInfo& from) {
    PBRankInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBRankInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBRankInfo";
  }
  protected:
  explicit PBRankInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDatasFieldNumber = 4,
    kRankIdFieldNumber = 1,
    kBegTsFieldNumber = 2,
    kEndTsFieldNumber = 3,
  };
  // repeated .PBRankData datas = 4;
  int datas_size() const;
  private:
  int _internal_datas_size() const;
  public:
  void clear_datas();
  ::PBRankData* mutable_datas(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBRankData >*
      mutable_datas();
  private:
  const ::PBRankData& _internal_datas(int index) const;
  ::PBRankData* _internal_add_datas();
  public:
  const ::PBRankData& datas(int index) const;
  ::PBRankData* add_datas();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBRankData >&
      datas() const;

  // int64 rank_id = 1;
  void clear_rank_id();
  int64_t rank_id() const;
  void set_rank_id(int64_t value);
  private:
  int64_t _internal_rank_id() const;
  void _internal_set_rank_id(int64_t value);
  public:

  // int64 beg_ts = 2;
  void clear_beg_ts();
  int64_t beg_ts() const;
  void set_beg_ts(int64_t value);
  private:
  int64_t _internal_beg_ts() const;
  void _internal_set_beg_ts(int64_t value);
  public:

  // int64 end_ts = 3;
  void clear_end_ts();
  int64_t end_ts() const;
  void set_end_ts(int64_t value);
  private:
  int64_t _internal_end_ts() const;
  void _internal_set_end_ts(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBRankInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBRankData > datas_;
    int64_t rank_id_;
    int64_t beg_ts_;
    int64_t end_ts_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rank_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBGetRankInfoReqCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBGetRankInfoReqCmd) */ {
 public:
  inline PBGetRankInfoReqCmd() : PBGetRankInfoReqCmd(nullptr) {}
  ~PBGetRankInfoReqCmd() override;
  explicit PROTOBUF_CONSTEXPR PBGetRankInfoReqCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBGetRankInfoReqCmd(const PBGetRankInfoReqCmd& from);
  PBGetRankInfoReqCmd(PBGetRankInfoReqCmd&& from) noexcept
    : PBGetRankInfoReqCmd() {
    *this = ::std::move(from);
  }

  inline PBGetRankInfoReqCmd& operator=(const PBGetRankInfoReqCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBGetRankInfoReqCmd& operator=(PBGetRankInfoReqCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBGetRankInfoReqCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBGetRankInfoReqCmd* internal_default_instance() {
    return reinterpret_cast<const PBGetRankInfoReqCmd*>(
               &_PBGetRankInfoReqCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PBGetRankInfoReqCmd& a, PBGetRankInfoReqCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(PBGetRankInfoReqCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBGetRankInfoReqCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBGetRankInfoReqCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBGetRankInfoReqCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBGetRankInfoReqCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBGetRankInfoReqCmd& from) {
    PBGetRankInfoReqCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBGetRankInfoReqCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBGetRankInfoReqCmd";
  }
  protected:
  explicit PBGetRankInfoReqCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUidFieldNumber = 1,
    kRankIdFieldNumber = 2,
  };
  // int64 uid = 1;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // int32 rank_id = 2;
  void clear_rank_id();
  int32_t rank_id() const;
  void set_rank_id(int32_t value);
  private:
  int32_t _internal_rank_id() const;
  void _internal_set_rank_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBGetRankInfoReqCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t uid_;
    int32_t rank_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rank_2eproto;
};
// -------------------------------------------------------------------

class COMMONNETUE_API PBGetRankInfoRspCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBGetRankInfoRspCmd) */ {
 public:
  inline PBGetRankInfoRspCmd() : PBGetRankInfoRspCmd(nullptr) {}
  ~PBGetRankInfoRspCmd() override;
  explicit PROTOBUF_CONSTEXPR PBGetRankInfoRspCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBGetRankInfoRspCmd(const PBGetRankInfoRspCmd& from);
  PBGetRankInfoRspCmd(PBGetRankInfoRspCmd&& from) noexcept
    : PBGetRankInfoRspCmd() {
    *this = ::std::move(from);
  }

  inline PBGetRankInfoRspCmd& operator=(const PBGetRankInfoRspCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBGetRankInfoRspCmd& operator=(PBGetRankInfoRspCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBGetRankInfoRspCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBGetRankInfoRspCmd* internal_default_instance() {
    return reinterpret_cast<const PBGetRankInfoRspCmd*>(
               &_PBGetRankInfoRspCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PBGetRankInfoRspCmd& a, PBGetRankInfoRspCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(PBGetRankInfoRspCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBGetRankInfoRspCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBGetRankInfoRspCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBGetRankInfoRspCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBGetRankInfoRspCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBGetRankInfoRspCmd& from) {
    PBGetRankInfoRspCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBGetRankInfoRspCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBGetRankInfoRspCmd";
  }
  protected:
  explicit PBGetRankInfoRspCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 2,
    kRankInfoFieldNumber = 4,
    kSelfDataFieldNumber = 5,
    kUidFieldNumber = 3,
    kCodeFieldNumber = 1,
  };
  // string error = 2;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // .PBRankInfo rank_info = 4;
  bool has_rank_info() const;
  private:
  bool _internal_has_rank_info() const;
  public:
  void clear_rank_info();
  const ::PBRankInfo& rank_info() const;
  PROTOBUF_NODISCARD ::PBRankInfo* release_rank_info();
  ::PBRankInfo* mutable_rank_info();
  void set_allocated_rank_info(::PBRankInfo* rank_info);
  private:
  const ::PBRankInfo& _internal_rank_info() const;
  ::PBRankInfo* _internal_mutable_rank_info();
  public:
  void unsafe_arena_set_allocated_rank_info(
      ::PBRankInfo* rank_info);
  ::PBRankInfo* unsafe_arena_release_rank_info();

  // .PBRankData self_data = 5;
  bool has_self_data() const;
  private:
  bool _internal_has_self_data() const;
  public:
  void clear_self_data();
  const ::PBRankData& self_data() const;
  PROTOBUF_NODISCARD ::PBRankData* release_self_data();
  ::PBRankData* mutable_self_data();
  void set_allocated_self_data(::PBRankData* self_data);
  private:
  const ::PBRankData& _internal_self_data() const;
  ::PBRankData* _internal_mutable_self_data();
  public:
  void unsafe_arena_set_allocated_self_data(
      ::PBRankData* self_data);
  ::PBRankData* unsafe_arena_release_self_data();

  // int64 uid = 3;
  void clear_uid();
  int64_t uid() const;
  void set_uid(int64_t value);
  private:
  int64_t _internal_uid() const;
  void _internal_set_uid(int64_t value);
  public:

  // int32 code = 1;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PBGetRankInfoRspCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    ::PBRankInfo* rank_info_;
    ::PBRankData* self_data_;
    int64_t uid_;
    int32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rank_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PBRankData

// int64 id = 1;
inline void PBRankData::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t PBRankData::_internal_id() const {
  return _impl_.id_;
}
inline int64_t PBRankData::id() const {
  // @@protoc_insertion_point(field_get:PBRankData.id)
  return _internal_id();
}
inline void PBRankData::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void PBRankData::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:PBRankData.id)
}

// int32 idx = 2;
inline void PBRankData::clear_idx() {
  _impl_.idx_ = 0;
}
inline int32_t PBRankData::_internal_idx() const {
  return _impl_.idx_;
}
inline int32_t PBRankData::idx() const {
  // @@protoc_insertion_point(field_get:PBRankData.idx)
  return _internal_idx();
}
inline void PBRankData::_internal_set_idx(int32_t value) {
  
  _impl_.idx_ = value;
}
inline void PBRankData::set_idx(int32_t value) {
  _internal_set_idx(value);
  // @@protoc_insertion_point(field_set:PBRankData.idx)
}

// int64 score = 3;
inline void PBRankData::clear_score() {
  _impl_.score_ = int64_t{0};
}
inline int64_t PBRankData::_internal_score() const {
  return _impl_.score_;
}
inline int64_t PBRankData::score() const {
  // @@protoc_insertion_point(field_get:PBRankData.score)
  return _internal_score();
}
inline void PBRankData::_internal_set_score(int64_t value) {
  
  _impl_.score_ = value;
}
inline void PBRankData::set_score(int64_t value) {
  _internal_set_score(value);
  // @@protoc_insertion_point(field_set:PBRankData.score)
}

// string rank_data = 4;
inline void PBRankData::clear_rank_data() {
  _impl_.rank_data_.ClearToEmpty();
}
inline const std::string& PBRankData::rank_data() const {
  // @@protoc_insertion_point(field_get:PBRankData.rank_data)
  return _internal_rank_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBRankData::set_rank_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.rank_data_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBRankData.rank_data)
}
inline std::string* PBRankData::mutable_rank_data() {
  std::string* _s = _internal_mutable_rank_data();
  // @@protoc_insertion_point(field_mutable:PBRankData.rank_data)
  return _s;
}
inline const std::string& PBRankData::_internal_rank_data() const {
  return _impl_.rank_data_.Get();
}
inline void PBRankData::_internal_set_rank_data(const std::string& value) {
  
  _impl_.rank_data_.Set(value, GetArenaForAllocation());
}
inline std::string* PBRankData::_internal_mutable_rank_data() {
  
  return _impl_.rank_data_.Mutable(GetArenaForAllocation());
}
inline std::string* PBRankData::release_rank_data() {
  // @@protoc_insertion_point(field_release:PBRankData.rank_data)
  return _impl_.rank_data_.Release();
}
inline void PBRankData::set_allocated_rank_data(std::string* rank_data) {
  if (rank_data != nullptr) {
    
  } else {
    
  }
  _impl_.rank_data_.SetAllocated(rank_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.rank_data_.IsDefault()) {
    _impl_.rank_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBRankData.rank_data)
}

// -------------------------------------------------------------------

// PBRankInfo

// int64 rank_id = 1;
inline void PBRankInfo::clear_rank_id() {
  _impl_.rank_id_ = int64_t{0};
}
inline int64_t PBRankInfo::_internal_rank_id() const {
  return _impl_.rank_id_;
}
inline int64_t PBRankInfo::rank_id() const {
  // @@protoc_insertion_point(field_get:PBRankInfo.rank_id)
  return _internal_rank_id();
}
inline void PBRankInfo::_internal_set_rank_id(int64_t value) {
  
  _impl_.rank_id_ = value;
}
inline void PBRankInfo::set_rank_id(int64_t value) {
  _internal_set_rank_id(value);
  // @@protoc_insertion_point(field_set:PBRankInfo.rank_id)
}

// int64 beg_ts = 2;
inline void PBRankInfo::clear_beg_ts() {
  _impl_.beg_ts_ = int64_t{0};
}
inline int64_t PBRankInfo::_internal_beg_ts() const {
  return _impl_.beg_ts_;
}
inline int64_t PBRankInfo::beg_ts() const {
  // @@protoc_insertion_point(field_get:PBRankInfo.beg_ts)
  return _internal_beg_ts();
}
inline void PBRankInfo::_internal_set_beg_ts(int64_t value) {
  
  _impl_.beg_ts_ = value;
}
inline void PBRankInfo::set_beg_ts(int64_t value) {
  _internal_set_beg_ts(value);
  // @@protoc_insertion_point(field_set:PBRankInfo.beg_ts)
}

// int64 end_ts = 3;
inline void PBRankInfo::clear_end_ts() {
  _impl_.end_ts_ = int64_t{0};
}
inline int64_t PBRankInfo::_internal_end_ts() const {
  return _impl_.end_ts_;
}
inline int64_t PBRankInfo::end_ts() const {
  // @@protoc_insertion_point(field_get:PBRankInfo.end_ts)
  return _internal_end_ts();
}
inline void PBRankInfo::_internal_set_end_ts(int64_t value) {
  
  _impl_.end_ts_ = value;
}
inline void PBRankInfo::set_end_ts(int64_t value) {
  _internal_set_end_ts(value);
  // @@protoc_insertion_point(field_set:PBRankInfo.end_ts)
}

// repeated .PBRankData datas = 4;
inline int PBRankInfo::_internal_datas_size() const {
  return _impl_.datas_.size();
}
inline int PBRankInfo::datas_size() const {
  return _internal_datas_size();
}
inline void PBRankInfo::clear_datas() {
  _impl_.datas_.Clear();
}
inline ::PBRankData* PBRankInfo::mutable_datas(int index) {
  // @@protoc_insertion_point(field_mutable:PBRankInfo.datas)
  return _impl_.datas_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBRankData >*
PBRankInfo::mutable_datas() {
  // @@protoc_insertion_point(field_mutable_list:PBRankInfo.datas)
  return &_impl_.datas_;
}
inline const ::PBRankData& PBRankInfo::_internal_datas(int index) const {
  return _impl_.datas_.Get(index);
}
inline const ::PBRankData& PBRankInfo::datas(int index) const {
  // @@protoc_insertion_point(field_get:PBRankInfo.datas)
  return _internal_datas(index);
}
inline ::PBRankData* PBRankInfo::_internal_add_datas() {
  return _impl_.datas_.Add();
}
inline ::PBRankData* PBRankInfo::add_datas() {
  ::PBRankData* _add = _internal_add_datas();
  // @@protoc_insertion_point(field_add:PBRankInfo.datas)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PBRankData >&
PBRankInfo::datas() const {
  // @@protoc_insertion_point(field_list:PBRankInfo.datas)
  return _impl_.datas_;
}

// -------------------------------------------------------------------

// PBGetRankInfoReqCmd

// int64 uid = 1;
inline void PBGetRankInfoReqCmd::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBGetRankInfoReqCmd::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBGetRankInfoReqCmd::uid() const {
  // @@protoc_insertion_point(field_get:PBGetRankInfoReqCmd.uid)
  return _internal_uid();
}
inline void PBGetRankInfoReqCmd::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBGetRankInfoReqCmd::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBGetRankInfoReqCmd.uid)
}

// int32 rank_id = 2;
inline void PBGetRankInfoReqCmd::clear_rank_id() {
  _impl_.rank_id_ = 0;
}
inline int32_t PBGetRankInfoReqCmd::_internal_rank_id() const {
  return _impl_.rank_id_;
}
inline int32_t PBGetRankInfoReqCmd::rank_id() const {
  // @@protoc_insertion_point(field_get:PBGetRankInfoReqCmd.rank_id)
  return _internal_rank_id();
}
inline void PBGetRankInfoReqCmd::_internal_set_rank_id(int32_t value) {
  
  _impl_.rank_id_ = value;
}
inline void PBGetRankInfoReqCmd::set_rank_id(int32_t value) {
  _internal_set_rank_id(value);
  // @@protoc_insertion_point(field_set:PBGetRankInfoReqCmd.rank_id)
}

// -------------------------------------------------------------------

// PBGetRankInfoRspCmd

// int32 code = 1;
inline void PBGetRankInfoRspCmd::clear_code() {
  _impl_.code_ = 0;
}
inline int32_t PBGetRankInfoRspCmd::_internal_code() const {
  return _impl_.code_;
}
inline int32_t PBGetRankInfoRspCmd::code() const {
  // @@protoc_insertion_point(field_get:PBGetRankInfoRspCmd.code)
  return _internal_code();
}
inline void PBGetRankInfoRspCmd::_internal_set_code(int32_t value) {
  
  _impl_.code_ = value;
}
inline void PBGetRankInfoRspCmd::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:PBGetRankInfoRspCmd.code)
}

// string error = 2;
inline void PBGetRankInfoRspCmd::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& PBGetRankInfoRspCmd::error() const {
  // @@protoc_insertion_point(field_get:PBGetRankInfoRspCmd.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PBGetRankInfoRspCmd::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PBGetRankInfoRspCmd.error)
}
inline std::string* PBGetRankInfoRspCmd::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:PBGetRankInfoRspCmd.error)
  return _s;
}
inline const std::string& PBGetRankInfoRspCmd::_internal_error() const {
  return _impl_.error_.Get();
}
inline void PBGetRankInfoRspCmd::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* PBGetRankInfoRspCmd::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* PBGetRankInfoRspCmd::release_error() {
  // @@protoc_insertion_point(field_release:PBGetRankInfoRspCmd.error)
  return _impl_.error_.Release();
}
inline void PBGetRankInfoRspCmd::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PBGetRankInfoRspCmd.error)
}

// int64 uid = 3;
inline void PBGetRankInfoRspCmd::clear_uid() {
  _impl_.uid_ = int64_t{0};
}
inline int64_t PBGetRankInfoRspCmd::_internal_uid() const {
  return _impl_.uid_;
}
inline int64_t PBGetRankInfoRspCmd::uid() const {
  // @@protoc_insertion_point(field_get:PBGetRankInfoRspCmd.uid)
  return _internal_uid();
}
inline void PBGetRankInfoRspCmd::_internal_set_uid(int64_t value) {
  
  _impl_.uid_ = value;
}
inline void PBGetRankInfoRspCmd::set_uid(int64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:PBGetRankInfoRspCmd.uid)
}

// .PBRankInfo rank_info = 4;
inline bool PBGetRankInfoRspCmd::_internal_has_rank_info() const {
  return this != internal_default_instance() && _impl_.rank_info_ != nullptr;
}
inline bool PBGetRankInfoRspCmd::has_rank_info() const {
  return _internal_has_rank_info();
}
inline void PBGetRankInfoRspCmd::clear_rank_info() {
  if (GetArenaForAllocation() == nullptr && _impl_.rank_info_ != nullptr) {
    delete _impl_.rank_info_;
  }
  _impl_.rank_info_ = nullptr;
}
inline const ::PBRankInfo& PBGetRankInfoRspCmd::_internal_rank_info() const {
  const ::PBRankInfo* p = _impl_.rank_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::PBRankInfo&>(
      ::_PBRankInfo_default_instance_);
}
inline const ::PBRankInfo& PBGetRankInfoRspCmd::rank_info() const {
  // @@protoc_insertion_point(field_get:PBGetRankInfoRspCmd.rank_info)
  return _internal_rank_info();
}
inline void PBGetRankInfoRspCmd::unsafe_arena_set_allocated_rank_info(
    ::PBRankInfo* rank_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rank_info_);
  }
  _impl_.rank_info_ = rank_info;
  if (rank_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PBGetRankInfoRspCmd.rank_info)
}
inline ::PBRankInfo* PBGetRankInfoRspCmd::release_rank_info() {
  
  ::PBRankInfo* temp = _impl_.rank_info_;
  _impl_.rank_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PBRankInfo* PBGetRankInfoRspCmd::unsafe_arena_release_rank_info() {
  // @@protoc_insertion_point(field_release:PBGetRankInfoRspCmd.rank_info)
  
  ::PBRankInfo* temp = _impl_.rank_info_;
  _impl_.rank_info_ = nullptr;
  return temp;
}
inline ::PBRankInfo* PBGetRankInfoRspCmd::_internal_mutable_rank_info() {
  
  if (_impl_.rank_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::PBRankInfo>(GetArenaForAllocation());
    _impl_.rank_info_ = p;
  }
  return _impl_.rank_info_;
}
inline ::PBRankInfo* PBGetRankInfoRspCmd::mutable_rank_info() {
  ::PBRankInfo* _msg = _internal_mutable_rank_info();
  // @@protoc_insertion_point(field_mutable:PBGetRankInfoRspCmd.rank_info)
  return _msg;
}
inline void PBGetRankInfoRspCmd::set_allocated_rank_info(::PBRankInfo* rank_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.rank_info_;
  }
  if (rank_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(rank_info);
    if (message_arena != submessage_arena) {
      rank_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rank_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.rank_info_ = rank_info;
  // @@protoc_insertion_point(field_set_allocated:PBGetRankInfoRspCmd.rank_info)
}

// .PBRankData self_data = 5;
inline bool PBGetRankInfoRspCmd::_internal_has_self_data() const {
  return this != internal_default_instance() && _impl_.self_data_ != nullptr;
}
inline bool PBGetRankInfoRspCmd::has_self_data() const {
  return _internal_has_self_data();
}
inline void PBGetRankInfoRspCmd::clear_self_data() {
  if (GetArenaForAllocation() == nullptr && _impl_.self_data_ != nullptr) {
    delete _impl_.self_data_;
  }
  _impl_.self_data_ = nullptr;
}
inline const ::PBRankData& PBGetRankInfoRspCmd::_internal_self_data() const {
  const ::PBRankData* p = _impl_.self_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::PBRankData&>(
      ::_PBRankData_default_instance_);
}
inline const ::PBRankData& PBGetRankInfoRspCmd::self_data() const {
  // @@protoc_insertion_point(field_get:PBGetRankInfoRspCmd.self_data)
  return _internal_self_data();
}
inline void PBGetRankInfoRspCmd::unsafe_arena_set_allocated_self_data(
    ::PBRankData* self_data) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.self_data_);
  }
  _impl_.self_data_ = self_data;
  if (self_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PBGetRankInfoRspCmd.self_data)
}
inline ::PBRankData* PBGetRankInfoRspCmd::release_self_data() {
  
  ::PBRankData* temp = _impl_.self_data_;
  _impl_.self_data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PBRankData* PBGetRankInfoRspCmd::unsafe_arena_release_self_data() {
  // @@protoc_insertion_point(field_release:PBGetRankInfoRspCmd.self_data)
  
  ::PBRankData* temp = _impl_.self_data_;
  _impl_.self_data_ = nullptr;
  return temp;
}
inline ::PBRankData* PBGetRankInfoRspCmd::_internal_mutable_self_data() {
  
  if (_impl_.self_data_ == nullptr) {
    auto* p = CreateMaybeMessage<::PBRankData>(GetArenaForAllocation());
    _impl_.self_data_ = p;
  }
  return _impl_.self_data_;
}
inline ::PBRankData* PBGetRankInfoRspCmd::mutable_self_data() {
  ::PBRankData* _msg = _internal_mutable_self_data();
  // @@protoc_insertion_point(field_mutable:PBGetRankInfoRspCmd.self_data)
  return _msg;
}
inline void PBGetRankInfoRspCmd::set_allocated_self_data(::PBRankData* self_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.self_data_;
  }
  if (self_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(self_data);
    if (message_arena != submessage_arena) {
      self_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, self_data, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.self_data_ = self_data;
  // @@protoc_insertion_point(field_set_allocated:PBGetRankInfoRspCmd.self_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rank_2eproto
