// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

#ifdef _MSC_VER
#	pragma warning(disable: 4125)
#	pragma warning(disable: 4647)
#	pragma warning(disable: 4668)
#	pragma warning(disable: 4800)
#	pragma warning(disable: 4946)
#endif

#include "rank.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR PBRankData::PBRankData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.rank_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/int64_t{0}
  , /*decltype(_impl_.score_)*/int64_t{0}
  , /*decltype(_impl_.idx_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBRankDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBRankDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBRankDataDefaultTypeInternal() {}
  union {
    PBRankData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBRankDataDefaultTypeInternal _PBRankData_default_instance_;
PROTOBUF_CONSTEXPR PBRankInfo::PBRankInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.datas_)*/{}
  , /*decltype(_impl_.rank_id_)*/int64_t{0}
  , /*decltype(_impl_.beg_ts_)*/int64_t{0}
  , /*decltype(_impl_.end_ts_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBRankInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBRankInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBRankInfoDefaultTypeInternal() {}
  union {
    PBRankInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBRankInfoDefaultTypeInternal _PBRankInfo_default_instance_;
PROTOBUF_CONSTEXPR PBGetRankInfoReqCmd::PBGetRankInfoReqCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_.rank_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBGetRankInfoReqCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBGetRankInfoReqCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBGetRankInfoReqCmdDefaultTypeInternal() {}
  union {
    PBGetRankInfoReqCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBGetRankInfoReqCmdDefaultTypeInternal _PBGetRankInfoReqCmd_default_instance_;
PROTOBUF_CONSTEXPR PBGetRankInfoRspCmd::PBGetRankInfoRspCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rank_info_)*/nullptr
  , /*decltype(_impl_.self_data_)*/nullptr
  , /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBGetRankInfoRspCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBGetRankInfoRspCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBGetRankInfoRspCmdDefaultTypeInternal() {}
  union {
    PBGetRankInfoRspCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBGetRankInfoRspCmdDefaultTypeInternal _PBGetRankInfoRspCmd_default_instance_;
static ::_pb::Metadata file_level_metadata_rank_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_rank_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_rank_2eproto = nullptr;

const uint32_t TableStruct_rank_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBRankData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBRankData, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::PBRankData, _impl_.idx_),
  PROTOBUF_FIELD_OFFSET(::PBRankData, _impl_.score_),
  PROTOBUF_FIELD_OFFSET(::PBRankData, _impl_.rank_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBRankInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBRankInfo, _impl_.rank_id_),
  PROTOBUF_FIELD_OFFSET(::PBRankInfo, _impl_.beg_ts_),
  PROTOBUF_FIELD_OFFSET(::PBRankInfo, _impl_.end_ts_),
  PROTOBUF_FIELD_OFFSET(::PBRankInfo, _impl_.datas_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBGetRankInfoReqCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBGetRankInfoReqCmd, _impl_.uid_),
  PROTOBUF_FIELD_OFFSET(::PBGetRankInfoReqCmd, _impl_.rank_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBGetRankInfoRspCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBGetRankInfoRspCmd, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::PBGetRankInfoRspCmd, _impl_.error_),
  PROTOBUF_FIELD_OFFSET(::PBGetRankInfoRspCmd, _impl_.uid_),
  PROTOBUF_FIELD_OFFSET(::PBGetRankInfoRspCmd, _impl_.rank_info_),
  PROTOBUF_FIELD_OFFSET(::PBGetRankInfoRspCmd, _impl_.self_data_),
};
static const ::_pbi::MigrationSchema schemas_rank_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::PBRankData)},
  { 10, -1, -1, sizeof(::PBRankInfo)},
  { 20, -1, -1, sizeof(::PBGetRankInfoReqCmd)},
  { 28, -1, -1, sizeof(::PBGetRankInfoRspCmd)},
};

static const ::_pb::Message* const file_default_instances_rank_2eproto[] = {
  &::_PBRankData_default_instance_._instance,
  &::_PBRankInfo_default_instance_._instance,
  &::_PBGetRankInfoReqCmd_default_instance_._instance,
  &::_PBGetRankInfoRspCmd_default_instance_._instance,
};

const char descriptor_table_protodef_rank_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nrank.proto\"G\n\nPBRankData\022\n\n\002id\030\001 \001(\003\022\013"
  "\n\003idx\030\002 \001(\005\022\r\n\005score\030\003 \001(\003\022\021\n\trank_data\030"
  "\004 \001(\t\"Y\n\nPBRankInfo\022\017\n\007rank_id\030\001 \001(\003\022\016\n\006"
  "beg_ts\030\002 \001(\003\022\016\n\006end_ts\030\003 \001(\003\022\032\n\005datas\030\004 "
  "\003(\0132\013.PBRankData\"3\n\023PBGetRankInfoReqCmd\022"
  "\013\n\003uid\030\001 \001(\003\022\017\n\007rank_id\030\002 \001(\005\"\177\n\023PBGetRa"
  "nkInfoRspCmd\022\014\n\004code\030\001 \001(\005\022\r\n\005error\030\002 \001("
  "\t\022\013\n\003uid\030\003 \001(\003\022\036\n\trank_info\030\004 \001(\0132\013.PBRa"
  "nkInfo\022\036\n\tself_data\030\005 \001(\0132\013.PBRankDatab\006"
  "proto3"
  ;
static ::_pbi::once_flag descriptor_table_rank_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_rank_2eproto = {
    false, false, 366, descriptor_table_protodef_rank_2eproto,
    "rank.proto",
    &descriptor_table_rank_2eproto_once, nullptr, 0, 4,
    schemas_rank_2eproto, file_default_instances_rank_2eproto, TableStruct_rank_2eproto::offsets,
    file_level_metadata_rank_2eproto, file_level_enum_descriptors_rank_2eproto,
    file_level_service_descriptors_rank_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_rank_2eproto_getter() {
  return &descriptor_table_rank_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_rank_2eproto(&descriptor_table_rank_2eproto);

// ===================================================================

class PBRankData::_Internal {
 public:
};

PBRankData::PBRankData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBRankData)
}
PBRankData::PBRankData(const PBRankData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBRankData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.rank_data_){}
    , decltype(_impl_.id_){}
    , decltype(_impl_.score_){}
    , decltype(_impl_.idx_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.rank_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rank_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rank_data().empty()) {
    _this->_impl_.rank_data_.Set(from._internal_rank_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.idx_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.idx_));
  // @@protoc_insertion_point(copy_constructor:PBRankData)
}

inline void PBRankData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.rank_data_){}
    , decltype(_impl_.id_){int64_t{0}}
    , decltype(_impl_.score_){int64_t{0}}
    , decltype(_impl_.idx_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.rank_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rank_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PBRankData::~PBRankData() {
  // @@protoc_insertion_point(destructor:PBRankData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBRankData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.rank_data_.Destroy();
}

void PBRankData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBRankData::Clear() {
// @@protoc_insertion_point(message_clear_start:PBRankData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rank_data_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.idx_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.idx_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBRankData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 idx = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.idx_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 score = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.score_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string rank_data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_rank_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBRankData.rank_data"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBRankData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBRankData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_id(), target);
  }

  // int32 idx = 2;
  if (this->_internal_idx() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_idx(), target);
  }

  // int64 score = 3;
  if (this->_internal_score() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_score(), target);
  }

  // string rank_data = 4;
  if (!this->_internal_rank_data().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_rank_data().data(), static_cast<int>(this->_internal_rank_data().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBRankData.rank_data");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_rank_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBRankData)
  return target;
}

size_t PBRankData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBRankData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string rank_data = 4;
  if (!this->_internal_rank_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rank_data());
  }

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_id());
  }

  // int64 score = 3;
  if (this->_internal_score() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_score());
  }

  // int32 idx = 2;
  if (this->_internal_idx() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_idx());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBRankData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBRankData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBRankData::GetClassData() const { return &_class_data_; }


void PBRankData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBRankData*>(&to_msg);
  auto& from = static_cast<const PBRankData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBRankData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_rank_data().empty()) {
    _this->_internal_set_rank_data(from._internal_rank_data());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_score() != 0) {
    _this->_internal_set_score(from._internal_score());
  }
  if (from._internal_idx() != 0) {
    _this->_internal_set_idx(from._internal_idx());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBRankData::CopyFrom(const PBRankData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBRankData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBRankData::IsInitialized() const {
  return true;
}

void PBRankData::InternalSwap(PBRankData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rank_data_, lhs_arena,
      &other->_impl_.rank_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBRankData, _impl_.idx_)
      + sizeof(PBRankData::_impl_.idx_)
      - PROTOBUF_FIELD_OFFSET(PBRankData, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBRankData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rank_2eproto_getter, &descriptor_table_rank_2eproto_once,
      file_level_metadata_rank_2eproto[0]);
}

// ===================================================================

class PBRankInfo::_Internal {
 public:
};

PBRankInfo::PBRankInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBRankInfo)
}
PBRankInfo::PBRankInfo(const PBRankInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBRankInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.datas_){from._impl_.datas_}
    , decltype(_impl_.rank_id_){}
    , decltype(_impl_.beg_ts_){}
    , decltype(_impl_.end_ts_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.rank_id_, &from._impl_.rank_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.end_ts_) -
    reinterpret_cast<char*>(&_impl_.rank_id_)) + sizeof(_impl_.end_ts_));
  // @@protoc_insertion_point(copy_constructor:PBRankInfo)
}

inline void PBRankInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.datas_){arena}
    , decltype(_impl_.rank_id_){int64_t{0}}
    , decltype(_impl_.beg_ts_){int64_t{0}}
    , decltype(_impl_.end_ts_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PBRankInfo::~PBRankInfo() {
  // @@protoc_insertion_point(destructor:PBRankInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBRankInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.datas_.~RepeatedPtrField();
}

void PBRankInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBRankInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:PBRankInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.datas_.Clear();
  ::memset(&_impl_.rank_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.end_ts_) -
      reinterpret_cast<char*>(&_impl_.rank_id_)) + sizeof(_impl_.end_ts_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBRankInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 rank_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.rank_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 beg_ts = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.beg_ts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 end_ts = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.end_ts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .PBRankData datas = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_datas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBRankInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBRankInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 rank_id = 1;
  if (this->_internal_rank_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_rank_id(), target);
  }

  // int64 beg_ts = 2;
  if (this->_internal_beg_ts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_beg_ts(), target);
  }

  // int64 end_ts = 3;
  if (this->_internal_end_ts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_end_ts(), target);
  }

  // repeated .PBRankData datas = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_datas_size()); i < n; i++) {
    const auto& repfield = this->_internal_datas(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBRankInfo)
  return target;
}

size_t PBRankInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBRankInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PBRankData datas = 4;
  total_size += 1UL * this->_internal_datas_size();
  for (const auto& msg : this->_impl_.datas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int64 rank_id = 1;
  if (this->_internal_rank_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_rank_id());
  }

  // int64 beg_ts = 2;
  if (this->_internal_beg_ts() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_beg_ts());
  }

  // int64 end_ts = 3;
  if (this->_internal_end_ts() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_end_ts());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBRankInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBRankInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBRankInfo::GetClassData() const { return &_class_data_; }


void PBRankInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBRankInfo*>(&to_msg);
  auto& from = static_cast<const PBRankInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBRankInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.datas_.MergeFrom(from._impl_.datas_);
  if (from._internal_rank_id() != 0) {
    _this->_internal_set_rank_id(from._internal_rank_id());
  }
  if (from._internal_beg_ts() != 0) {
    _this->_internal_set_beg_ts(from._internal_beg_ts());
  }
  if (from._internal_end_ts() != 0) {
    _this->_internal_set_end_ts(from._internal_end_ts());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBRankInfo::CopyFrom(const PBRankInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBRankInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBRankInfo::IsInitialized() const {
  return true;
}

void PBRankInfo::InternalSwap(PBRankInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.datas_.InternalSwap(&other->_impl_.datas_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBRankInfo, _impl_.end_ts_)
      + sizeof(PBRankInfo::_impl_.end_ts_)
      - PROTOBUF_FIELD_OFFSET(PBRankInfo, _impl_.rank_id_)>(
          reinterpret_cast<char*>(&_impl_.rank_id_),
          reinterpret_cast<char*>(&other->_impl_.rank_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBRankInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rank_2eproto_getter, &descriptor_table_rank_2eproto_once,
      file_level_metadata_rank_2eproto[1]);
}

// ===================================================================

class PBGetRankInfoReqCmd::_Internal {
 public:
};

PBGetRankInfoReqCmd::PBGetRankInfoReqCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBGetRankInfoReqCmd)
}
PBGetRankInfoReqCmd::PBGetRankInfoReqCmd(const PBGetRankInfoReqCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBGetRankInfoReqCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.uid_){}
    , decltype(_impl_.rank_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.uid_, &from._impl_.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.rank_id_) -
    reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.rank_id_));
  // @@protoc_insertion_point(copy_constructor:PBGetRankInfoReqCmd)
}

inline void PBGetRankInfoReqCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.uid_){int64_t{0}}
    , decltype(_impl_.rank_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PBGetRankInfoReqCmd::~PBGetRankInfoReqCmd() {
  // @@protoc_insertion_point(destructor:PBGetRankInfoReqCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBGetRankInfoReqCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PBGetRankInfoReqCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBGetRankInfoReqCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PBGetRankInfoReqCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.rank_id_) -
      reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.rank_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBGetRankInfoReqCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 rank_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.rank_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBGetRankInfoReqCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBGetRankInfoReqCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_uid(), target);
  }

  // int32 rank_id = 2;
  if (this->_internal_rank_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_rank_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBGetRankInfoReqCmd)
  return target;
}

size_t PBGetRankInfoReqCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBGetRankInfoReqCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  // int32 rank_id = 2;
  if (this->_internal_rank_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_rank_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBGetRankInfoReqCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBGetRankInfoReqCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBGetRankInfoReqCmd::GetClassData() const { return &_class_data_; }


void PBGetRankInfoReqCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBGetRankInfoReqCmd*>(&to_msg);
  auto& from = static_cast<const PBGetRankInfoReqCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBGetRankInfoReqCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (from._internal_rank_id() != 0) {
    _this->_internal_set_rank_id(from._internal_rank_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBGetRankInfoReqCmd::CopyFrom(const PBGetRankInfoReqCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBGetRankInfoReqCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBGetRankInfoReqCmd::IsInitialized() const {
  return true;
}

void PBGetRankInfoReqCmd::InternalSwap(PBGetRankInfoReqCmd* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBGetRankInfoReqCmd, _impl_.rank_id_)
      + sizeof(PBGetRankInfoReqCmd::_impl_.rank_id_)
      - PROTOBUF_FIELD_OFFSET(PBGetRankInfoReqCmd, _impl_.uid_)>(
          reinterpret_cast<char*>(&_impl_.uid_),
          reinterpret_cast<char*>(&other->_impl_.uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBGetRankInfoReqCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rank_2eproto_getter, &descriptor_table_rank_2eproto_once,
      file_level_metadata_rank_2eproto[2]);
}

// ===================================================================

class PBGetRankInfoRspCmd::_Internal {
 public:
  static const ::PBRankInfo& rank_info(const PBGetRankInfoRspCmd* msg);
  static const ::PBRankData& self_data(const PBGetRankInfoRspCmd* msg);
};

const ::PBRankInfo&
PBGetRankInfoRspCmd::_Internal::rank_info(const PBGetRankInfoRspCmd* msg) {
  return *msg->_impl_.rank_info_;
}
const ::PBRankData&
PBGetRankInfoRspCmd::_Internal::self_data(const PBGetRankInfoRspCmd* msg) {
  return *msg->_impl_.self_data_;
}
PBGetRankInfoRspCmd::PBGetRankInfoRspCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBGetRankInfoRspCmd)
}
PBGetRankInfoRspCmd::PBGetRankInfoRspCmd(const PBGetRankInfoRspCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBGetRankInfoRspCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.rank_info_){nullptr}
    , decltype(_impl_.self_data_){nullptr}
    , decltype(_impl_.uid_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error().empty()) {
    _this->_impl_.error_.Set(from._internal_error(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_rank_info()) {
    _this->_impl_.rank_info_ = new ::PBRankInfo(*from._impl_.rank_info_);
  }
  if (from._internal_has_self_data()) {
    _this->_impl_.self_data_ = new ::PBRankData(*from._impl_.self_data_);
  }
  ::memcpy(&_impl_.uid_, &from._impl_.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.code_) -
    reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.code_));
  // @@protoc_insertion_point(copy_constructor:PBGetRankInfoRspCmd)
}

inline void PBGetRankInfoRspCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.rank_info_){nullptr}
    , decltype(_impl_.self_data_){nullptr}
    , decltype(_impl_.uid_){int64_t{0}}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PBGetRankInfoRspCmd::~PBGetRankInfoRspCmd() {
  // @@protoc_insertion_point(destructor:PBGetRankInfoRspCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBGetRankInfoRspCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_.Destroy();
  if (this != internal_default_instance()) delete _impl_.rank_info_;
  if (this != internal_default_instance()) delete _impl_.self_data_;
}

void PBGetRankInfoRspCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBGetRankInfoRspCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PBGetRankInfoRspCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.rank_info_ != nullptr) {
    delete _impl_.rank_info_;
  }
  _impl_.rank_info_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.self_data_ != nullptr) {
    delete _impl_.self_data_;
  }
  _impl_.self_data_ = nullptr;
  ::memset(&_impl_.uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.code_) -
      reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBGetRankInfoRspCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBGetRankInfoRspCmd.error"));
        } else
          goto handle_unusual;
        continue;
      // int64 uid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PBRankInfo rank_info = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_rank_info(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PBRankData self_data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_self_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBGetRankInfoRspCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBGetRankInfoRspCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_code(), target);
  }

  // string error = 2;
  if (!this->_internal_error().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error().data(), static_cast<int>(this->_internal_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBGetRankInfoRspCmd.error");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error(), target);
  }

  // int64 uid = 3;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_uid(), target);
  }

  // .PBRankInfo rank_info = 4;
  if (this->_internal_has_rank_info()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::rank_info(this),
        _Internal::rank_info(this).GetCachedSize(), target, stream);
  }

  // .PBRankData self_data = 5;
  if (this->_internal_has_self_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::self_data(this),
        _Internal::self_data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBGetRankInfoRspCmd)
  return target;
}

size_t PBGetRankInfoRspCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBGetRankInfoRspCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error = 2;
  if (!this->_internal_error().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error());
  }

  // .PBRankInfo rank_info = 4;
  if (this->_internal_has_rank_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.rank_info_);
  }

  // .PBRankData self_data = 5;
  if (this->_internal_has_self_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.self_data_);
  }

  // int64 uid = 3;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBGetRankInfoRspCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBGetRankInfoRspCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBGetRankInfoRspCmd::GetClassData() const { return &_class_data_; }


void PBGetRankInfoRspCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBGetRankInfoRspCmd*>(&to_msg);
  auto& from = static_cast<const PBGetRankInfoRspCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBGetRankInfoRspCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_has_rank_info()) {
    _this->_internal_mutable_rank_info()->::PBRankInfo::MergeFrom(
        from._internal_rank_info());
  }
  if (from._internal_has_self_data()) {
    _this->_internal_mutable_self_data()->::PBRankData::MergeFrom(
        from._internal_self_data());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBGetRankInfoRspCmd::CopyFrom(const PBGetRankInfoRspCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBGetRankInfoRspCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBGetRankInfoRspCmd::IsInitialized() const {
  return true;
}

void PBGetRankInfoRspCmd::InternalSwap(PBGetRankInfoRspCmd* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_, lhs_arena,
      &other->_impl_.error_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBGetRankInfoRspCmd, _impl_.code_)
      + sizeof(PBGetRankInfoRspCmd::_impl_.code_)
      - PROTOBUF_FIELD_OFFSET(PBGetRankInfoRspCmd, _impl_.rank_info_)>(
          reinterpret_cast<char*>(&_impl_.rank_info_),
          reinterpret_cast<char*>(&other->_impl_.rank_info_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBGetRankInfoRspCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rank_2eproto_getter, &descriptor_table_rank_2eproto_once,
      file_level_metadata_rank_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PBRankData*
Arena::CreateMaybeMessage< ::PBRankData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBRankData >(arena);
}
template<> PROTOBUF_NOINLINE ::PBRankInfo*
Arena::CreateMaybeMessage< ::PBRankInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBRankInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::PBGetRankInfoReqCmd*
Arena::CreateMaybeMessage< ::PBGetRankInfoReqCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBGetRankInfoReqCmd >(arena);
}
template<> PROTOBUF_NOINLINE ::PBGetRankInfoRspCmd*
Arena::CreateMaybeMessage< ::PBGetRankInfoRspCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBGetRankInfoRspCmd >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
