// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: team.proto

#ifdef _MSC_VER
#	pragma warning(disable: 4125)
#	pragma warning(disable: 4647)
#	pragma warning(disable: 4668)
#	pragma warning(disable: 4800)
#	pragma warning(disable: 4946)
#endif

#include "team.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR PBTeamApplyData::PBTeamApplyData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nick_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_.head_id_)*/0
  , /*decltype(_impl_.account_level_)*/0
  , /*decltype(_impl_.head_frame_)*/0
  , /*decltype(_impl_.title_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBTeamApplyDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBTeamApplyDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBTeamApplyDataDefaultTypeInternal() {}
  union {
    PBTeamApplyData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBTeamApplyDataDefaultTypeInternal _PBTeamApplyData_default_instance_;
PROTOBUF_CONSTEXPR PBApplyTeamReqCmd::PBApplyTeamReqCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.apply_info_)*/nullptr
  , /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_.teamid_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBApplyTeamReqCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBApplyTeamReqCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBApplyTeamReqCmdDefaultTypeInternal() {}
  union {
    PBApplyTeamReqCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBApplyTeamReqCmdDefaultTypeInternal _PBApplyTeamReqCmd_default_instance_;
PROTOBUF_CONSTEXPR PBApplyTeamRspCmd::PBApplyTeamRspCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.uid_)*/int64_t{0}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBApplyTeamRspCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBApplyTeamRspCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBApplyTeamRspCmdDefaultTypeInternal() {}
  union {
    PBApplyTeamRspCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBApplyTeamRspCmdDefaultTypeInternal _PBApplyTeamRspCmd_default_instance_;
PROTOBUF_CONSTEXPR PBApplyTeamSyncCmd::PBApplyTeamSyncCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.apply_data_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBApplyTeamSyncCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBApplyTeamSyncCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBApplyTeamSyncCmdDefaultTypeInternal() {}
  union {
    PBApplyTeamSyncCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBApplyTeamSyncCmdDefaultTypeInternal _PBApplyTeamSyncCmd_default_instance_;
static ::_pb::Metadata file_level_metadata_team_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_team_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_team_2eproto = nullptr;

const uint32_t TableStruct_team_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBTeamApplyData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBTeamApplyData, _impl_.uid_),
  PROTOBUF_FIELD_OFFSET(::PBTeamApplyData, _impl_.head_id_),
  PROTOBUF_FIELD_OFFSET(::PBTeamApplyData, _impl_.nick_name_),
  PROTOBUF_FIELD_OFFSET(::PBTeamApplyData, _impl_.account_level_),
  PROTOBUF_FIELD_OFFSET(::PBTeamApplyData, _impl_.head_frame_),
  PROTOBUF_FIELD_OFFSET(::PBTeamApplyData, _impl_.title_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamReqCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamReqCmd, _impl_.uid_),
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamReqCmd, _impl_.teamid_),
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamReqCmd, _impl_.apply_info_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamRspCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamRspCmd, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamRspCmd, _impl_.error_),
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamRspCmd, _impl_.uid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamSyncCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBApplyTeamSyncCmd, _impl_.apply_data_),
};
static const ::_pbi::MigrationSchema schemas_team_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::PBTeamApplyData)},
  { 12, -1, -1, sizeof(::PBApplyTeamReqCmd)},
  { 21, -1, -1, sizeof(::PBApplyTeamRspCmd)},
  { 30, -1, -1, sizeof(::PBApplyTeamSyncCmd)},
};

static const ::_pb::Message* const file_default_instances_team_2eproto[] = {
  &::_PBTeamApplyData_default_instance_._instance,
  &::_PBApplyTeamReqCmd_default_instance_._instance,
  &::_PBApplyTeamRspCmd_default_instance_._instance,
  &::_PBApplyTeamSyncCmd_default_instance_._instance,
};

const char descriptor_table_protodef_team_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nteam.proto\"|\n\017PBTeamApplyData\022\013\n\003uid\030\001"
  " \001(\003\022\017\n\007head_id\030\002 \001(\005\022\021\n\tnick_name\030\003 \001(\t"
  "\022\025\n\raccount_level\030\004 \001(\005\022\022\n\nhead_frame\030\005 "
  "\001(\005\022\r\n\005title\030\006 \001(\005\"V\n\021PBApplyTeamReqCmd\022"
  "\013\n\003uid\030\001 \001(\003\022\016\n\006teamid\030\002 \001(\003\022$\n\napply_in"
  "fo\030\003 \001(\0132\020.PBTeamApplyData\"=\n\021PBApplyTea"
  "mRspCmd\022\014\n\004code\030\001 \001(\005\022\r\n\005error\030\002 \001(\t\022\013\n\003"
  "uid\030\003 \001(\003\":\n\022PBApplyTeamSyncCmd\022$\n\napply"
  "_data\030\001 \001(\0132\020.PBTeamApplyDatab\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_team_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_team_2eproto = {
    false, false, 357, descriptor_table_protodef_team_2eproto,
    "team.proto",
    &descriptor_table_team_2eproto_once, nullptr, 0, 4,
    schemas_team_2eproto, file_default_instances_team_2eproto, TableStruct_team_2eproto::offsets,
    file_level_metadata_team_2eproto, file_level_enum_descriptors_team_2eproto,
    file_level_service_descriptors_team_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_team_2eproto_getter() {
  return &descriptor_table_team_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_team_2eproto(&descriptor_table_team_2eproto);

// ===================================================================

class PBTeamApplyData::_Internal {
 public:
};

PBTeamApplyData::PBTeamApplyData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBTeamApplyData)
}
PBTeamApplyData::PBTeamApplyData(const PBTeamApplyData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBTeamApplyData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nick_name_){}
    , decltype(_impl_.uid_){}
    , decltype(_impl_.head_id_){}
    , decltype(_impl_.account_level_){}
    , decltype(_impl_.head_frame_){}
    , decltype(_impl_.title_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.nick_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nick_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_nick_name().empty()) {
    _this->_impl_.nick_name_.Set(from._internal_nick_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.uid_, &from._impl_.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.title_) -
    reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.title_));
  // @@protoc_insertion_point(copy_constructor:PBTeamApplyData)
}

inline void PBTeamApplyData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nick_name_){}
    , decltype(_impl_.uid_){int64_t{0}}
    , decltype(_impl_.head_id_){0}
    , decltype(_impl_.account_level_){0}
    , decltype(_impl_.head_frame_){0}
    , decltype(_impl_.title_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.nick_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nick_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PBTeamApplyData::~PBTeamApplyData() {
  // @@protoc_insertion_point(destructor:PBTeamApplyData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBTeamApplyData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.nick_name_.Destroy();
}

void PBTeamApplyData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBTeamApplyData::Clear() {
// @@protoc_insertion_point(message_clear_start:PBTeamApplyData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nick_name_.ClearToEmpty();
  ::memset(&_impl_.uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.title_) -
      reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.title_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBTeamApplyData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 head_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.head_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string nick_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_nick_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBTeamApplyData.nick_name"));
        } else
          goto handle_unusual;
        continue;
      // int32 account_level = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.account_level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 head_frame = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.head_frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 title = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.title_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBTeamApplyData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBTeamApplyData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_uid(), target);
  }

  // int32 head_id = 2;
  if (this->_internal_head_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_head_id(), target);
  }

  // string nick_name = 3;
  if (!this->_internal_nick_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nick_name().data(), static_cast<int>(this->_internal_nick_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBTeamApplyData.nick_name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_nick_name(), target);
  }

  // int32 account_level = 4;
  if (this->_internal_account_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_account_level(), target);
  }

  // int32 head_frame = 5;
  if (this->_internal_head_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_head_frame(), target);
  }

  // int32 title = 6;
  if (this->_internal_title() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_title(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBTeamApplyData)
  return target;
}

size_t PBTeamApplyData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBTeamApplyData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string nick_name = 3;
  if (!this->_internal_nick_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_nick_name());
  }

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  // int32 head_id = 2;
  if (this->_internal_head_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_head_id());
  }

  // int32 account_level = 4;
  if (this->_internal_account_level() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_account_level());
  }

  // int32 head_frame = 5;
  if (this->_internal_head_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_head_frame());
  }

  // int32 title = 6;
  if (this->_internal_title() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_title());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBTeamApplyData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBTeamApplyData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBTeamApplyData::GetClassData() const { return &_class_data_; }


void PBTeamApplyData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBTeamApplyData*>(&to_msg);
  auto& from = static_cast<const PBTeamApplyData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBTeamApplyData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nick_name().empty()) {
    _this->_internal_set_nick_name(from._internal_nick_name());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (from._internal_head_id() != 0) {
    _this->_internal_set_head_id(from._internal_head_id());
  }
  if (from._internal_account_level() != 0) {
    _this->_internal_set_account_level(from._internal_account_level());
  }
  if (from._internal_head_frame() != 0) {
    _this->_internal_set_head_frame(from._internal_head_frame());
  }
  if (from._internal_title() != 0) {
    _this->_internal_set_title(from._internal_title());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBTeamApplyData::CopyFrom(const PBTeamApplyData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBTeamApplyData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBTeamApplyData::IsInitialized() const {
  return true;
}

void PBTeamApplyData::InternalSwap(PBTeamApplyData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.nick_name_, lhs_arena,
      &other->_impl_.nick_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBTeamApplyData, _impl_.title_)
      + sizeof(PBTeamApplyData::_impl_.title_)
      - PROTOBUF_FIELD_OFFSET(PBTeamApplyData, _impl_.uid_)>(
          reinterpret_cast<char*>(&_impl_.uid_),
          reinterpret_cast<char*>(&other->_impl_.uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBTeamApplyData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_team_2eproto_getter, &descriptor_table_team_2eproto_once,
      file_level_metadata_team_2eproto[0]);
}

// ===================================================================

class PBApplyTeamReqCmd::_Internal {
 public:
  static const ::PBTeamApplyData& apply_info(const PBApplyTeamReqCmd* msg);
};

const ::PBTeamApplyData&
PBApplyTeamReqCmd::_Internal::apply_info(const PBApplyTeamReqCmd* msg) {
  return *msg->_impl_.apply_info_;
}
PBApplyTeamReqCmd::PBApplyTeamReqCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBApplyTeamReqCmd)
}
PBApplyTeamReqCmd::PBApplyTeamReqCmd(const PBApplyTeamReqCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBApplyTeamReqCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.apply_info_){nullptr}
    , decltype(_impl_.uid_){}
    , decltype(_impl_.teamid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_apply_info()) {
    _this->_impl_.apply_info_ = new ::PBTeamApplyData(*from._impl_.apply_info_);
  }
  ::memcpy(&_impl_.uid_, &from._impl_.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.teamid_) -
    reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.teamid_));
  // @@protoc_insertion_point(copy_constructor:PBApplyTeamReqCmd)
}

inline void PBApplyTeamReqCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.apply_info_){nullptr}
    , decltype(_impl_.uid_){int64_t{0}}
    , decltype(_impl_.teamid_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PBApplyTeamReqCmd::~PBApplyTeamReqCmd() {
  // @@protoc_insertion_point(destructor:PBApplyTeamReqCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBApplyTeamReqCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.apply_info_;
}

void PBApplyTeamReqCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBApplyTeamReqCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PBApplyTeamReqCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.apply_info_ != nullptr) {
    delete _impl_.apply_info_;
  }
  _impl_.apply_info_ = nullptr;
  ::memset(&_impl_.uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.teamid_) -
      reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.teamid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBApplyTeamReqCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 teamid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.teamid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PBTeamApplyData apply_info = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_apply_info(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBApplyTeamReqCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBApplyTeamReqCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_uid(), target);
  }

  // int64 teamid = 2;
  if (this->_internal_teamid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_teamid(), target);
  }

  // .PBTeamApplyData apply_info = 3;
  if (this->_internal_has_apply_info()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::apply_info(this),
        _Internal::apply_info(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBApplyTeamReqCmd)
  return target;
}

size_t PBApplyTeamReqCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBApplyTeamReqCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .PBTeamApplyData apply_info = 3;
  if (this->_internal_has_apply_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.apply_info_);
  }

  // int64 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  // int64 teamid = 2;
  if (this->_internal_teamid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_teamid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBApplyTeamReqCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBApplyTeamReqCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBApplyTeamReqCmd::GetClassData() const { return &_class_data_; }


void PBApplyTeamReqCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBApplyTeamReqCmd*>(&to_msg);
  auto& from = static_cast<const PBApplyTeamReqCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBApplyTeamReqCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_apply_info()) {
    _this->_internal_mutable_apply_info()->::PBTeamApplyData::MergeFrom(
        from._internal_apply_info());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (from._internal_teamid() != 0) {
    _this->_internal_set_teamid(from._internal_teamid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBApplyTeamReqCmd::CopyFrom(const PBApplyTeamReqCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBApplyTeamReqCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBApplyTeamReqCmd::IsInitialized() const {
  return true;
}

void PBApplyTeamReqCmd::InternalSwap(PBApplyTeamReqCmd* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBApplyTeamReqCmd, _impl_.teamid_)
      + sizeof(PBApplyTeamReqCmd::_impl_.teamid_)
      - PROTOBUF_FIELD_OFFSET(PBApplyTeamReqCmd, _impl_.apply_info_)>(
          reinterpret_cast<char*>(&_impl_.apply_info_),
          reinterpret_cast<char*>(&other->_impl_.apply_info_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBApplyTeamReqCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_team_2eproto_getter, &descriptor_table_team_2eproto_once,
      file_level_metadata_team_2eproto[1]);
}

// ===================================================================

class PBApplyTeamRspCmd::_Internal {
 public:
};

PBApplyTeamRspCmd::PBApplyTeamRspCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBApplyTeamRspCmd)
}
PBApplyTeamRspCmd::PBApplyTeamRspCmd(const PBApplyTeamRspCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBApplyTeamRspCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.uid_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error().empty()) {
    _this->_impl_.error_.Set(from._internal_error(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.uid_, &from._impl_.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.code_) -
    reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.code_));
  // @@protoc_insertion_point(copy_constructor:PBApplyTeamRspCmd)
}

inline void PBApplyTeamRspCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.uid_){int64_t{0}}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PBApplyTeamRspCmd::~PBApplyTeamRspCmd() {
  // @@protoc_insertion_point(destructor:PBApplyTeamRspCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBApplyTeamRspCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_.Destroy();
}

void PBApplyTeamRspCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBApplyTeamRspCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PBApplyTeamRspCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_.ClearToEmpty();
  ::memset(&_impl_.uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.code_) -
      reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBApplyTeamRspCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PBApplyTeamRspCmd.error"));
        } else
          goto handle_unusual;
        continue;
      // int64 uid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBApplyTeamRspCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBApplyTeamRspCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_code(), target);
  }

  // string error = 2;
  if (!this->_internal_error().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error().data(), static_cast<int>(this->_internal_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PBApplyTeamRspCmd.error");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error(), target);
  }

  // int64 uid = 3;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_uid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBApplyTeamRspCmd)
  return target;
}

size_t PBApplyTeamRspCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBApplyTeamRspCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error = 2;
  if (!this->_internal_error().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error());
  }

  // int64 uid = 3;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uid());
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBApplyTeamRspCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBApplyTeamRspCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBApplyTeamRspCmd::GetClassData() const { return &_class_data_; }


void PBApplyTeamRspCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBApplyTeamRspCmd*>(&to_msg);
  auto& from = static_cast<const PBApplyTeamRspCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBApplyTeamRspCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBApplyTeamRspCmd::CopyFrom(const PBApplyTeamRspCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBApplyTeamRspCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBApplyTeamRspCmd::IsInitialized() const {
  return true;
}

void PBApplyTeamRspCmd::InternalSwap(PBApplyTeamRspCmd* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_, lhs_arena,
      &other->_impl_.error_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBApplyTeamRspCmd, _impl_.code_)
      + sizeof(PBApplyTeamRspCmd::_impl_.code_)
      - PROTOBUF_FIELD_OFFSET(PBApplyTeamRspCmd, _impl_.uid_)>(
          reinterpret_cast<char*>(&_impl_.uid_),
          reinterpret_cast<char*>(&other->_impl_.uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBApplyTeamRspCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_team_2eproto_getter, &descriptor_table_team_2eproto_once,
      file_level_metadata_team_2eproto[2]);
}

// ===================================================================

class PBApplyTeamSyncCmd::_Internal {
 public:
  static const ::PBTeamApplyData& apply_data(const PBApplyTeamSyncCmd* msg);
};

const ::PBTeamApplyData&
PBApplyTeamSyncCmd::_Internal::apply_data(const PBApplyTeamSyncCmd* msg) {
  return *msg->_impl_.apply_data_;
}
PBApplyTeamSyncCmd::PBApplyTeamSyncCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBApplyTeamSyncCmd)
}
PBApplyTeamSyncCmd::PBApplyTeamSyncCmd(const PBApplyTeamSyncCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBApplyTeamSyncCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.apply_data_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_apply_data()) {
    _this->_impl_.apply_data_ = new ::PBTeamApplyData(*from._impl_.apply_data_);
  }
  // @@protoc_insertion_point(copy_constructor:PBApplyTeamSyncCmd)
}

inline void PBApplyTeamSyncCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.apply_data_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PBApplyTeamSyncCmd::~PBApplyTeamSyncCmd() {
  // @@protoc_insertion_point(destructor:PBApplyTeamSyncCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBApplyTeamSyncCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.apply_data_;
}

void PBApplyTeamSyncCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBApplyTeamSyncCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PBApplyTeamSyncCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.apply_data_ != nullptr) {
    delete _impl_.apply_data_;
  }
  _impl_.apply_data_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBApplyTeamSyncCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .PBTeamApplyData apply_data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_apply_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBApplyTeamSyncCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBApplyTeamSyncCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .PBTeamApplyData apply_data = 1;
  if (this->_internal_has_apply_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::apply_data(this),
        _Internal::apply_data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBApplyTeamSyncCmd)
  return target;
}

size_t PBApplyTeamSyncCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBApplyTeamSyncCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .PBTeamApplyData apply_data = 1;
  if (this->_internal_has_apply_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.apply_data_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBApplyTeamSyncCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBApplyTeamSyncCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBApplyTeamSyncCmd::GetClassData() const { return &_class_data_; }


void PBApplyTeamSyncCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBApplyTeamSyncCmd*>(&to_msg);
  auto& from = static_cast<const PBApplyTeamSyncCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBApplyTeamSyncCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_apply_data()) {
    _this->_internal_mutable_apply_data()->::PBTeamApplyData::MergeFrom(
        from._internal_apply_data());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBApplyTeamSyncCmd::CopyFrom(const PBApplyTeamSyncCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBApplyTeamSyncCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBApplyTeamSyncCmd::IsInitialized() const {
  return true;
}

void PBApplyTeamSyncCmd::InternalSwap(PBApplyTeamSyncCmd* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.apply_data_, other->_impl_.apply_data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PBApplyTeamSyncCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_team_2eproto_getter, &descriptor_table_team_2eproto_once,
      file_level_metadata_team_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PBTeamApplyData*
Arena::CreateMaybeMessage< ::PBTeamApplyData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBTeamApplyData >(arena);
}
template<> PROTOBUF_NOINLINE ::PBApplyTeamReqCmd*
Arena::CreateMaybeMessage< ::PBApplyTeamReqCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBApplyTeamReqCmd >(arena);
}
template<> PROTOBUF_NOINLINE ::PBApplyTeamRspCmd*
Arena::CreateMaybeMessage< ::PBApplyTeamRspCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBApplyTeamRspCmd >(arena);
}
template<> PROTOBUF_NOINLINE ::PBApplyTeamSyncCmd*
Arena::CreateMaybeMessage< ::PBApplyTeamSyncCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBApplyTeamSyncCmd >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
