#pragma once
#include "CoreMinimal.h"
#include "Net/ProtobufMessage.h"
#include "trade.generated.h"

// Generated by Proto3 to UE5 Struct Converter



USTRUCT(BlueprintType)
struct FPBTradeBankProductData
{
	GENERATED_BODY()

	//交易id
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 TradeId = 0LL;
	//商品id(道具的配置id)
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 ProductId = 0;
	//当前剩余数量
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 CurNum = 0;
	//被预订数量
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 BookNum = 0;
	//售出数量
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 SaleNum = 0;
	//单价
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 Price = 0;
	//卖家id
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 Uid = 0;
	//本商品创建时间
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 BegTs = 0LL;
	//本商品下架时间
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 EndTs = 0LL;
	//当前商品状态
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 State = 0;
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasTradeId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasProductId = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCurNum = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasBookNum = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasSaleNum = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasPrice = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUid = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasBegTs = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasEndTs = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasState = false;
};

USTRUCT(BlueprintType)
struct FPBSelfTradeBankData
{
	GENERATED_BODY()

	//交易行货架数
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 BoxCapacity = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	TArray<FPBTradeBankProductData> ProductList = {};
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasBoxCapacity = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasProductList = false;
};
// 客户端请求自己的交易行数据
UCLASS(BlueprintType)
class UPBGetTradeBankInfoReqCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	// 协议数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 Uid = 0LL;
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUid = false;
};
// 客户端请求自己的交易行数据 返回信息
UCLASS(BlueprintType)
class UPBGetTradeBankInfoRspCmd : public UProtobufMessage
{
	GENERATED_BODY()
public:

	// 服务器返回,0成功,其他失败
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int32 Code = 0;
	// 错误信息
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	FString Error = TEXT("");
	// 协议数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	int64 Uid = 0LL;
	//自己的交易行数据
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Protobuf|Property",Transient)
	FPBSelfTradeBankData SelfTradeBankInfo = {};
	// ---------- 属性存在标志 ----------
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasCode = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasError = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasUid = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite,Category="HasProperty")
	bool bHasSelfTradeBankInfo = false;
};
