--- Automatically generated,do not modify.

local M={
    ["PBPacketCmd"] = 1,
    ["PBClientLoginReqCmd"] = 2,
    ["google.protobuf.Any"] = 3,
    ["PBApplyFriendReqCmd"] = 100,
    ["PBApplyFriendRspCmd"] = 101,
    ["PBApplyGuildReqCmd"] = 102,
    ["PBApplyGuildRspCmd"] = 103,
    ["PBApplyRoomReqCmd"] = 104,
    ["PBApplyRoomRspCmd"] = 105,
    ["PBApplyRoomSyncCmd"] = 106,
    ["PBClientGetUsrSimInfoReqCmd"] = 107,
    ["PBClientGetUsrSimInfoRspCmd"] = 108,
    ["PBClientLoginRspCmd"] = 109,
    ["PBCreateRoomReqCmd"] = 110,
    ["PBCreateRoomRspCmd"] = 111,
    ["PBDealApplyRoomReqCmd"] = 112,
    ["PBDealApplyRoomRspCmd"] = 113,
    ["PBDealApplyRoomSyncCmd"] = 114,
    ["PBEnterRoomReqCmd"] = 115,
    ["PBEnterRoomRspCmd"] = 116,
    ["PBEnterRoomSyncCmd"] = 117,
    ["PBExitRoomReqCmd"] = 118,
    ["PBExitRoomRspCmd"] = 119,
    ["PBExitRoomSyncCmd"] = 120,
    ["PBGetActivityInfoReqCmd"] = 121,
    ["PBGetActivityInfoRspCmd"] = 122,
    ["PBGetFriendInfoReqCmd"] = 123,
    ["PBGetFriendInfoRspCmd"] = 124,
    ["PBGetMailItemReqCmd"] = 125,
    ["PBGetMailItemRspCmd"] = 126,
    ["PBGetOpenBoxReqCmd"] = 127,
    ["PBGetOpenBoxRspCmd"] = 128,
    ["PBGetRankInfoReqCmd"] = 129,
    ["PBGetRankInfoRspCmd"] = 130,
    ["PBGetRoomInfoReqCmd"] = 131,
    ["PBGetRoomInfoRspCmd"] = 132,
    ["PBGetTradeBankInfoReqCmd"] = 133,
    ["PBGetTradeBankInfoRspCmd"] = 134,
    ["PBKickRoomReqCmd"] = 135,
    ["PBKickRoomRspCmd"] = 136,
    ["PBKickRoomSyncCmd"] = 137,
    ["PBModRoomReqCmd"] = 138,
    ["PBModRoomRspCmd"] = 139,
    ["PBPingCmd"] = 140,
    ["PBPongCmd"] = 141,
    ["PBReadyRoomReqCmd"] = 142,
    ["PBReadyRoomRspCmd"] = 143,
    ["PBReadyRoomSyncCmd"] = 144,
    ["PBRoomInfoSyncCmd"] = 145,
    ["PBSearchRoomReqCmd"] = 146,
    ["PBSearchRoomRspCmd"] = 147,
    ["PBTeamCreateReqCmd"] = 148,
    ["PBTeamCreateRspCmd"] = 149,
    ["PBTeamExitReqCmd"] = 150,
    ["PBTeamExitRspCmd"] = 151,
    ["PBTeamInfoReqCmd"] = 152,
    ["PBTeamInfoRspCmd"] = 153,
    ["PBTeamJoinReqCmd"] = 154,
    ["PBTeamJoinRspCmd"] = 155,
    ["PBTeamKickoutReqCmd"] = 156,
    ["PBTeamKickoutRspCmd"] = 157,
    ["PBTeamStatusCmd"] = 158,
    ["PBUpdateMissionClientSyncCmd"] = 159,
    ["PBUpdateMissionSeverSyncCmd"] = 160,

}

local forward = {
    PBGetActivityInfoReqCmd = 'addr_activity',
    PBGetActivityInfoRspCmd = 'addr_activity',
    PBClientLoginReqCmd = 'addr_auth',
    PBClientLoginRspCmd = 'addr_auth',
    PBGetFriendInfoReqCmd = 'addr_friend',
    PBGetFriendInfoRspCmd = 'addr_friend',
    PBApplyFriendReqCmd = 'addr_friend',
    PBApplyFriendRspCmd = 'addr_friend',
    PBApplyGuildReqCmd = 'addr_guild',
    PBApplyGuildRspCmd = 'addr_guild',
    PBGetMailItemReqCmd = 'addr_mail',
    PBGetMailItemRspCmd = 'addr_mail',
    PBUpdateMissionSeverSyncCmd = 'addr_mission',
    PBUpdateMissionClientSyncCmd = 'addr_mission',
    PBGetRankInfoReqCmd = 'addr_rank',
    PBGetRankInfoRspCmd = 'addr_rank',
    PBCreateRoomReqCmd = 'addr_room',
    PBCreateRoomRspCmd = 'addr_room',
    PBSearchRoomReqCmd = 'addr_room',
    PBSearchRoomRspCmd = 'addr_room',
    PBModRoomReqCmd = 'addr_room',
    PBModRoomRspCmd = 'addr_room',
    PBRoomInfoSyncCmd = 'addr_room',
    PBApplyRoomReqCmd = 'addr_room',
    PBApplyRoomRspCmd = 'addr_room',
    PBApplyRoomSyncCmd = 'addr_room',
    PBDealApplyRoomReqCmd = 'addr_room',
    PBDealApplyRoomRspCmd = 'addr_room',
    PBDealApplyRoomSyncCmd = 'addr_room',
    PBEnterRoomReqCmd = 'addr_room',
    PBEnterRoomRspCmd = 'addr_room',
    PBEnterRoomSyncCmd = 'addr_room',
    PBExitRoomReqCmd = 'addr_room',
    PBExitRoomRspCmd = 'addr_room',
    PBExitRoomSyncCmd = 'addr_room',
    PBKickRoomReqCmd = 'addr_room',
    PBKickRoomRspCmd = 'addr_room',
    PBKickRoomSyncCmd = 'addr_room',
    PBReadyRoomReqCmd = 'addr_room',
    PBReadyRoomRspCmd = 'addr_room',
    PBReadyRoomSyncCmd = 'addr_room',
    PBGetRoomInfoReqCmd = 'addr_room',
    PBGetRoomInfoRspCmd = 'addr_room',
    PBTeamStatusCmd = 'addr_user',
    PBTeamInfoReqCmd = 'addr_user',
    PBTeamInfoRspCmd = 'addr_user',
    PBTeamCreateReqCmd = 'addr_user',
    PBTeamCreateRspCmd = 'addr_user',
    PBTeamExitReqCmd = 'addr_user',
    PBTeamExitRspCmd = 'addr_user',
    PBTeamKickoutReqCmd = 'addr_user',
    PBTeamKickoutRspCmd = 'addr_user',
    PBTeamJoinReqCmd = 'addr_user',
    PBTeamJoinRspCmd = 'addr_user',
    PBGetTradeBankInfoReqCmd = 'addr_trade',
    PBGetTradeBankInfoRspCmd = 'addr_trade',
    PBGetOpenBoxReqCmd = 'addr_user',
    PBGetOpenBoxRspCmd = 'addr_user',
    PBClientGetUsrSimInfoReqCmd = 'addr_user',
    PBClientGetUsrSimInfoRspCmd = 'addr_user',

}

local mt = { forward = forward }

mt.__newindex = function(_, name, _)
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

mt.__index = function(_, name)
    if name == "forward" then
        return forward
    end
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

return setmetatable(M,mt)
